// GENERATED by scripts/tutorials/gen-index.ts from the files in this directory — do not edit.
// One line per help entry file.
export { default as e_crm_create_estimate } from "./crm/crm-create-estimate";
export { default as e_crm_pricebook_add } from "./crm/crm-pricebook-add";
