/**
 * /api/v1/social-posts — scheduled and published social media posts (social_posts), read as
 * stored: the text, media and destination the user (or the API, source=api) supplied. The
 * social connection's credentials are never part of this.
 *
 * A post without a business (older global posts) has no location: in an agency workspace only
 * an all-clients role reads those.
 */
import { z } from "zod";
import { pool } from "../../db";
import {
  ApiError, OPENAPI, Params, type Scope, dateTime, handler, nullableInt, nullableString, ownerScopeSql, pageSchema, positiveId, requireLocation,
  resource, sendItem, sendList, uuid,
} from "./_shared";

export const SOCIAL_STATES = ["draft", "queued", "submitting", "submitted", "published", "failed", "uncertain", "cancelled"] as const;

const filterSchema = pageSchema.extend({
  locationId: positiveId.optional(),
  state: z.string().trim().max(20).optional(),
  platform: z.string().trim().max(40).optional(),
  since: z.string().datetime().optional(),
});

export const SOCIAL_POST_SCHEMA = { type: "object", properties: {
  id: { type: "string", format: "uuid" }, locationId: nullableInt, requestId: { type: "string" }, destinationKey: { type: "string" },
  platform: nullableString, accountId: nullableString, target: { type: "object", additionalProperties: true, nullable: true },
  text: nullableString, mediaUrls: { type: "array", items: { type: "string" } },
  state: { type: "string", description: `One of ${SOCIAL_STATES.join(", ")}` },
  dueAt: dateTime, scheduledAt: dateTime, approvedAt: dateTime,
  aiGenerated: { type: "boolean" }, autoGenerated: { type: "boolean" }, source: nullableString,
  submissionId: nullableString, publicUrl: nullableString, error: nullableString, createdAt: dateTime, updatedAt: dateTime,
} };

const COLUMNS = "s.id,s.business_id,s.request_id,s.destination_key,s.payload,s.state,s.due_at,s.scheduled_at,s.approved_at,s.ai_generated,s.auto_generated,s.source,s.submission_id,s.public_url,s.error,s.created_at,s.updated_at";

export function socialPostItem(s: Record<string, any>) {
  const post = s.payload?.post ?? {};
  const content = post.content ?? {};
  return {
    id: s.id, locationId: s.business_id, requestId: s.request_id, destinationKey: s.destination_key,
    platform: content.platform ?? null, accountId: post.accountId ?? null, target: post.target ?? null,
    text: content.text ?? null, mediaUrls: Array.isArray(content.mediaUrls) ? content.mediaUrls : [],
    state: s.state, dueAt: s.due_at, scheduledAt: s.scheduled_at, approvedAt: s.approved_at,
    aiGenerated: s.ai_generated, autoGenerated: s.auto_generated, source: s.source,
    submissionId: s.submission_id, publicUrl: s.public_url, error: s.error, createdAt: s.created_at, updatedAt: s.updated_at,
  };
}

async function listSocialPosts(scope: Scope, f: z.infer<typeof filterSchema>) {
  const p = new Params();
  const where = [ownerScopeSql(scope, p, "s", "s.business_id")];
  if (f.locationId) where.push(`s.business_id=${p.add(f.locationId)}`);
  if (f.state) where.push(`s.state=${p.add(f.state)}`);
  if (f.platform) where.push(`s.payload->'post'->'content'->>'platform'=${p.add(f.platform)}`);
  if (f.since) where.push(`s.created_at >= ${p.add(f.since)}::timestamptz`);
  const sql = where.join(" AND ");
  const [{ rows }, { rows: [{ total }] }] = await Promise.all([
    pool.query(`SELECT ${COLUMNS} FROM social_posts s WHERE ${sql} ORDER BY s.due_at DESC, s.id LIMIT ${p.add(f.limit)} OFFSET ${p.add(f.offset)}`, p.values),
    pool.query(`SELECT count(*)::int total FROM social_posts s WHERE ${sql}`, p.values.slice(0, -2)),
  ]);
  return { items: rows.map(socialPostItem), total };
}

const common = { 401: OPENAPI.errors[401], 402: OPENAPI.errors[402], 403: OPENAPI.errors[403], 404: OPENAPI.errors[404], 429: OPENAPI.errors[429] };

export const socialPostsResource = resource("social-posts", {
  tags: [{ name: "Social posts", description: "Scheduled and published social media posts." }],
  paths: {
    "/social-posts": { get: {
      tags: ["Social posts"], summary: "List social posts", operationId: "listSocialPosts",
      parameters: [...OPENAPI.pageParams, OPENAPI.workspaceParam, OPENAPI.query("locationId", { type: "integer" }),
        OPENAPI.query("state", { type: "string", enum: [...SOCIAL_STATES] }), OPENAPI.query("platform", { type: "string" }),
        OPENAPI.query("since", { type: "string", format: "date-time" }, "Created on or after")],
      responses: { ...OPENAPI.list("#/components/schemas/SocialPost"), 400: OPENAPI.errors[400], ...common },
    } },
    "/social-posts/{id}": { get: {
      tags: ["Social posts"], summary: "One social post", operationId: "getSocialPost",
      parameters: [OPENAPI.idParam("id", "string", "uuid"), OPENAPI.workspaceParam],
      responses: { ...OPENAPI.item("#/components/schemas/SocialPost"), 400: OPENAPI.errors[400], ...common },
    } },
  },
  components: { schemas: { ...OPENAPI.baseSchemas, SocialPost: SOCIAL_POST_SCHEMA } },
}, (r) => {
  r.get("/", handler(async (req, res, scope) => {
    const q = filterSchema.parse(req.query ?? {});
    if (q.locationId) await requireLocation(scope, q.locationId);
    const { items, total } = await listSocialPosts(scope, q);
    sendList(res, items, total, q);
  }));

  r.get("/:id", handler(async (req, res, scope) => {
    const id = uuid.parse(req.params.id);
    const p = new Params();
    const where = ownerScopeSql(scope, p, "s", "s.business_id");
    const { rows: [row] } = await pool.query(`SELECT ${COLUMNS} FROM social_posts s WHERE ${where} AND s.id=${p.add(id)}`, p.values);
    if (!row) throw new ApiError(404, "not_found", "Social post not found");
    sendItem(res, socialPostItem(row));
  }));
});
