/**
 * The LIVE-ACTION gator (2026-10-08, the owner's experiment): a photoreal alligator in the brand's hard
 * hat, shades and hi-vis vest, in clips that look like something a person filmed on a phone by accident.
 * The formula of the owner's two reference clips (an AI squirrel "doing parkour" over an AC unit; an AI
 * selfie vlog that goes wrong while its character never stops talking):
 *   · ONE continuous take, 6–15 s; one gag you understand in half a second with the sound off;
 *   · mundane place, flat daylight, imperfect framing; loud natural sound;
 *   · NOTHING burned into the picture — the brand is what he wears, the caption and the account;
 *   · every post is labelled AI-generated by the platform flag and carries #AIContent.
 * THE LINE holds: he is always fine and pops back up; no people are hurt (there are no people); nothing
 * that reads as a real accident, a real animal attack or cruelty; he never bites or threatens; no brands,
 * no real people, nobody else's character. The joke is always on HIS overconfidence — never advice.
 */
import type { Concept, Shot } from "./concepts";

/** The model sheet: drawn once from text, then the reference of every live still. */
export const LIVE_SHEET_PROMPT = "A photograph taken on a phone in flat overcast daylight on a gravel construction lot: a real adult American alligator standing fully upright on its hind legs like a person, facing the camera in a relaxed three-quarter stance, full body in frame from hard hat to feet and tail — photorealistic, real scales, real proportions, dark olive-green hide, pale cream throat and belly, long snout, mouth closed — wearing a clean yellow construction hard hat, dark wraparound safety sunglasses and an orange hi-vis safety vest with silver reflective stripes; its tail rests on the ground behind it. Plain background: a stack of lumber and a chain-link fence, out of the way. Everything in focus, no cinematic lighting, no filter. No people. No text, letters, numbers, logos, brand names or watermarks anywhere.";

const SELFIE = "Selfie taken by the alligator himself: one scaly forearm reaches out to the edge of the frame toward the lens, holding the phone at arm's length; wide-angle front camera; his head, hard hat and shoulders fill the lower two thirds of the frame; he looks straight into the lens with his mouth slightly open, mid-sentence.";
const ONE_TAKE = "ONE continuous handheld selfie take filmed by the alligator himself, no cuts, photorealistic phone footage, natural daylight.";
const ALWAYS = "He is never hurt. His hard hat, dark sunglasses and orange vest stay on the whole time. Exactly one alligator; no people appear. No text, captions, logos or watermarks appear in the picture. Loud natural sound only: his voice and what happens around him — no music.";
const tags = ["contractorlife", "construction", "aicontent", "jobsite", "bluecollar"];

/** A selfie vlog that goes wrong while he keeps talking. `script`: what he says, as checked against the take. */
const selfie = (n: number, id: string, title: string, seconds: number, scene: string, action: string, script: string, caption: string): Concept => {
  const shot: Shot = { id: "s1", look: "live", video: "talk", seconds, use: seconds, rawMotion: true, scene: `${SELFIE} ${scene}`, motion: `${ONE_TAKE} ${action} ${ALWAYS}`, say: { text: script }, beats: [], cues: [] };
  void n;
  return { id, title, format: "job-site pain", cut: "oneshot", look: "live", style: 1, evergreen: true, sample: true, hook: caption, shots: [shot], sound: "His own voice and the disaster, as the model renders them; nothing added.", caption, hashtags: tags, linkedin: null, youtubeTitle: title };
};

export const LIVE_CONCEPTS: Concept[] = [
  selfie(1, "selfie-deck", "Day one, new deck", 10,
    "He stands on a brand-new wooden backyard deck raised about a metre off the ground; behind him the deck boards, a railing and the back wall of a suburban house with a sliding glass door.",
    "He talks fast and cocky straight into the lens: \"Day one. New deck. Solid. I'm tellin' you, this thing ain't goin' nowhere—\" Mid-word the whole deck suddenly drops out from under him with a loud crack and crash of timber; the camera jolts, spins and shakes, a blur of sky, boards and dust; then he rises back into frame from below, covered in sawdust, hard hat crooked, still holding the phone, completely unbothered, and says, deadpan: \"Like I said. Day two.\"",
    "Day one. New deck. Solid. I'm telling you, this thing ain't going nowhere. Like I said. Day two.",
    "Day one on the new deck. He said it was solid."),
  selfie(2, "selfie-roof", "Twenty years", 10,
    "He stands on a low-pitched shingle roof of a single-storey house under a pale sky; behind him the roof slopes away to the gutter, with treetops and a neighbour's roof beyond.",
    "He talks fast and cocky straight into the lens: \"Guy says tie off. I been doin' this twenty years—\" Mid-word his feet go out from under him and he slides backward down the shingles and out of frame; the camera tumbles — a blur of sky, gutter, leaves — and lands in a big green hedge; then his head pops up out of the hedge into frame, leaves on his hard hat, still holding the phone, unhurt and deadpan, and he says: \"Twenty years. Never said good years.\"",
    "Guy says tie off. I been doing this twenty years. Twenty years. Never said good years.",
    "He's been doing this twenty years. (Tie off.)"),
  selfie(3, "selfie-leak", "It's a small leak", 9,
    "He stands in an ordinary small bathroom with white tiles; behind him a white tiled wall with a chrome tap and a faint damp stain on it.",
    "He talks fast and dry straight into the lens: \"Homeowner says it's a small leak—\" Mid-word the tiled wall behind him bursts open and a huge jet of water blasts across the room, hitting him in the back and soaking everything; the camera shakes and is splashed; he does not flinch, water pouring off his hard hat, and after a beat he says, completely deadpan: \"Small.\"",
    "Homeowner says it's a small leak. Small.",
    "The homeowner said it was a small leak."),
];
