/**
 * The other twenty-seven concepts of the writers' room (the three pilots are in concepts.ts). Same
 * house rules, same shape; none of these has been generated yet — every prompt is ready to run.
 */
import type { Concept, Shot, ShotBeat } from "./concepts";
import type { Cue } from "./sound";

const b = (at: number, text: string, accent?: string, pos?: "top" | "low"): ShotBeat => ({ at, text, ...(accent ? { accent } : {}), ...(pos ? { pos } : {}) });
const shot = (id: string, use: number, scene: string, motion: string, beats: ShotBeat[], cues: Cue[]): Shot => ({ id, scene, motion, use, beats, cues });
const TRUCK = "a generic unmarked orange pickup truck";

export const MORE_CONCEPTS: Concept[] = [
  /* ── Job-site pain ─────────────────────────────────────────────────────── */
  {
    id: "permit-office-359", title: "The permit office closes at 4", format: "job-site pain", evergreen: true,
    hook: "3:58 PM. Permit office closes at 4.",
    shots: [
      shot("s1", 3.2, "He sprints along a town pavement toward a plain civic office building with wide steps, a roll of blueprints tucked under one arm, leaning forward at full speed, small dust clouds at his boots. Late-afternoon sun.",
        "He runs flat out toward the building, arms pumping, the blueprints under one arm, dust puffing behind his boots. The camera tracks alongside him.",
        [b(0, "3:58 PM. Permit office closes at 4.", "4.")], [{ type: "beat", at: 0, dur: 3.2, bpm: 150, gain: 0.5 }, { type: "tick", at: 0, every: 0.25, until: 3.1, gain: 0.7 }]),
      shot("s2", 3.0, "He stands at the closed glass doors of the plain civic office, blinds pulled down behind the glass, shoulders dropped, the roll of blueprints hanging limp in one hand, looking back at the viewer, deadpan.",
        "He stands still at the closed doors. The roll of blueprints slowly droops and unrolls to the ground. He turns his head to the viewer, deadpan.",
        [b(0.15, "3:59.", "3:59.", "top")], [{ type: "thud", at: 0.05 }, { type: "sad", at: 0.5 }]),
    ],
    sound: "A fast tick and a racing bed for the sprint; a thud at the doors and the three-note “wah-wah”.",
    caption: "Every contractor has lost this race at least once. Look the office up before you drive across the county.",
    hashtags: ["contractorlife", "buildingpermit", "construction", "contractorhumor", "generalcontractor"],
    linkedin: "Permit counters keep their own hours, and they are rarely the hours on the door. Knowing which office handles the job — and how it takes applications — before the drive is the cheapest hour saved all week.",
    youtubeTitle: "3:58 PM. The permit office closes at 4.",
  },
  {
    id: "monday-vs-friday", title: "Monday 6 AM vs Friday 2 PM", format: "job-site pain", evergreen: false, timing: "Post on a Friday afternoon; the “X vs Y” split is a format that travels now and will date.",
    hook: "Monday, 6 AM.",
    shots: [
      shot("s1", 3.0, `Before dawn, under a single street light, he leans against the closed tailgate of ${TRUCK}, slumped, holding a very large paper coffee cup with both hands, shoulders heavy. Dark blue sky, a little mist.`,
        "He stands slumped, barely moving, and takes one slow, heavy sip of coffee. His head droops, then lifts again. Mist drifts past the street light.",
        [b(0, "Monday, 6 AM.", "Monday,")], [{ type: "air", at: 0, dur: 3.0 }, { type: "tick", at: 0.4, every: 1, until: 2.6, gain: 0.6 }]),
      shot("s2", 3.2, `In bright afternoon sun he walks toward ${TRUCK} with a bounce in his step, a tool bag swinging from one hand, chest out, a wide closed-mouth grin. Blue sky, a tidy finished jobsite behind him.`,
        "He struts toward the truck with a springy, rhythmic walk, swinging the tool bag in time, nodding along. Bright, sunny, upbeat.",
        [b(0.1, "Friday, 2 PM.", "Friday,")], [{ type: "whoosh", at: 0 }, { type: "beat", at: 0.1, dur: 3.1, bpm: 124, gain: 0.7 }]),
    ],
    sound: "Near silence and a slow clock on Monday; a swish and a bright four-on-the-floor bed on Friday.",
    caption: "Same gator. Same truck. Different animal.",
    hashtags: ["contractorlife", "fridayfeeling", "construction", "bluecollar", "contractorhumor"],
    linkedin: null,
    youtubeTitle: "Monday 6 AM vs Friday 2 PM (contractor edition)",
  },
  {
    id: "estimate-vs-change-orders", title: "The estimate vs the change orders", format: "job-site pain", evergreen: true,
    hook: "The estimate.",
    shots: [
      shot("s1", 2.4, "He stands in a half-finished kitchen with bare stud walls, proudly holding up one single blank sheet of paper between two fingers, chest out.",
        "He holds up the single sheet of paper proudly and gives one confident nod. The sheet flutters slightly.",
        [b(0, "The estimate.", "estimate.")], [{ type: "ding", at: 0.2 }, { type: "air", at: 0, dur: 2.4 }]),
      shot("s2", 3.4, "In the same half-finished kitchen he hugs a towering stack of blank paper that reaches above his hard hat, leaning back to balance it, peeking around the side of the stack.",
        "He wobbles left and right, balancing the towering stack of paper. A few blank sheets slide off the top and drift down. He peeks around the stack at the viewer.",
        [b(0.1, "The change orders.", "change")], [{ type: "thud", at: 0.05 }, { type: "beat", at: 0.2, dur: 3.2, bpm: 132, gain: 0.5 }]),
    ],
    sound: "One clean bell for the single sheet; a thud and a wobbling bed for the stack.",
    caption: "Both are honest. One of them just had more time with the house.",
    hashtags: ["contractorlife", "changeorder", "construction", "remodeling", "contractorhumor"],
    linkedin: "An estimate is a snapshot; change orders are the record of what the house taught you afterwards. Writing each one down when it happens, with a price and a signature, is what keeps the final invoice from being a surprise to anyone.",
    youtubeTitle: "The estimate vs the change orders",
  },
  {
    id: "paid-same-day", title: "The client paid the same day", format: "job-site pain", evergreen: true,
    hook: "Client paid the invoice. Same day.",
    shots: [
      shot("s1", 2.2, "On a sunny jobsite he stands holding a phone in one hand close to his snout, frozen in surprise, eyebrows raised above his sunglasses. The phone screen glows and shows nothing readable.",
        "He stares at the glowing phone, frozen, then slowly lifts his head toward the viewer in disbelief.",
        [b(0, "Client paid the invoice. Same day.", "paid")], [{ type: "ding", at: 0.3 }, { type: "air", at: 0, dur: 2.2 }]),
      shot("s2", 3.6, "On the same sunny jobsite he dances, both fists up, one boot off the ground, tail swung out to the side, a huge closed-mouth grin, the phone tucked in his tool belt.",
        "He does a small joyful shuffle dance: stepping side to side, pumping both fists, tail swaying in time. Bright and bouncy.",
        [b(0.1, "Finest. Client. Ever.", "Ever.")], [{ type: "beat", at: 0, dur: 3.6, bpm: 128, gain: 0.8 }]),
    ],
    sound: "A notification bell, a beat of silence, then a bouncy bed for the dance.",
    caption: "To everyone who pays the invoice the day it lands: we see you. We'd build you anything.",
    hashtags: ["contractorlife", "smallbusiness", "construction", "contractorhumor", "bluecollar"],
    linkedin: "Nothing changes a contractor's week like an invoice paid the day it was sent. Clear line items and an easy way to pay make that day more likely — and it is worth saying thank you when it happens.",
    youtubeTitle: "When the client pays the invoice the same day",
  },
  {
    id: "zero-percent-rain", title: "Zero percent chance of rain", format: "job-site pain", evergreen: false, timing: "Seasonal: spring and storm season; any week the weather is the news.",
    hook: "Forecast: 0% chance of rain.",
    shots: [
      shot("s1", 2.6, "He stands on the grass just outside the wooden forms of a freshly poured, perfectly smooth concrete driveway slab — both boots on the grass, not on the concrete — holding a concrete float at his side, pleased, under a bright sky with one small grey cloud directly overhead.",
        "He admires the smooth wet concrete and nods, satisfied. Above him the one small grey cloud grows and darkens.",
        [b(0, "Forecast: 0% chance of rain.", "0%")], [{ type: "air", at: 0, dur: 2.6 }, { type: "beat", at: 0, dur: 2.6, bpm: 100, gain: 0.4 }]),
      shot("s2", 3.2, "Heavy cartoon rain pours down on him as he stands in the same spot, soaked, deadpan, holding a comically tiny umbrella over the hard hat. Raindrops dimple the wet concrete behind him.",
        "Rain pours straight down. He stands completely still under the tiny umbrella, deadpan, water streaming off his hard hat. Raindrops splash on the concrete.",
        [b(0.1, "The 0%:", "0%:")], [{ type: "thud", at: 0 }, { type: "air", at: 0, dur: 3.2, gain: 3 }, { type: "sad", at: 0.6 }]),
    ],
    sound: "A calm bed; a thunder-thud, steady rain noise and the three-note “wah-wah”.",
    caption: "The app said zero. The sky said “hold my float.”",
    hashtags: ["concrete", "contractorlife", "construction", "contractorhumor", "bluecollar"],
    linkedin: null,
    youtubeTitle: "Forecast said 0% chance of rain (pour day)",
  },
  {
    id: "one-quick-supply-run", title: "One quick supply run", format: "job-site pain", evergreen: true,
    hook: "“Just one quick supply run.”",
    shots: [
      shot("s1", 2.6, `He stands beside ${TRUCK} parked on a jobsite, the truck bed completely empty, holding up one finger confidently.`,
        "He holds up one finger, nods confidently and pats the side of the empty truck.",
        [b(0, "“Just one quick supply run.”", "one")], [{ type: "ding", at: 0.2 }, { type: "beat", at: 0, dur: 2.6, bpm: 110, gain: 0.5 }]),
      shot("s2", 3.2, `At sunset he stands beside the same parked ${TRUCK}, its bed now piled high with lumber, buckets and boxes strapped down, wiping his brow, tired, holding up four fingers.`,
        "He wipes his brow and holds up four fingers, shaking his head slowly. The sun sets behind the loaded, parked truck.",
        [b(0.1, "Trip four.", "four.")], [{ type: "thud", at: 0.05 }, { type: "sad", at: 0.5 }]),
    ],
    sound: "A cheerful bell and bed; a thud and the “wah-wah” at sunset.",
    caption: "The list was three things. The list is never three things.",
    hashtags: ["contractorlife", "contractorhumor", "construction", "handyman", "diy"],
    linkedin: null,
    youtubeTitle: "“Just one quick supply run” (trip four)",
  },
  {
    id: "where-is-my-tape", title: "Where is my tape measure?", format: "job-site pain", evergreen: true,
    hook: "Where is my tape measure?",
    shots: [
      shot("s1", 3.2, "In a garage workshop he is bent over an open tool bag on a workbench, rummaging with both hands, tools scattered around, looking worried.",
        "He rummages frantically through the tool bag, lifting tools and setting them down, then looks left and right.",
        [b(0, "Where is my tape measure?", "tape")], [{ type: "beat", at: 0, dur: 3.2, bpm: 140, gain: 0.5 }, { type: "pop", at: 0.5, every: 0.7, until: 2.8, gain: 0.3 }]),
      shot("s2", 3.0, "Close-up at hip height: the orange tape measure is clipped right there on his tool belt. His hand hovers just above it. His face, in the upper part of the frame, looks down at it, deadpan.",
        "He slowly looks down at the tape measure clipped to his own belt, pauses, then slowly looks up at the viewer, deadpan.",
        [b(0.2, "It was on my belt.", "belt.")], [{ type: "whoosh", at: 0 }, { type: "tick", at: 0.5, every: 0.5, until: 2.6 }]),
    ],
    sound: "A busy bed for the search; cut to a swish and a slow clock for the reveal.",
    caption: "Twenty minutes. It was on my belt for all twenty.",
    hashtags: ["contractorlife", "contractorhumor", "tools", "construction", "carpentry"],
    linkedin: null,
    youtubeTitle: "Where is my tape measure? (it was on my belt)",
  },
  {
    id: "inspector-pulls-up", title: "The inspector pulls up", format: "job-site pain", evergreen: true,
    hook: "When the inspector pulls up",
    shots: [
      shot("s1", 2.4, "He sits relaxed on an upturned bucket on a tidy jobsite, sipping from a paper coffee cup, one boot stretched out. A framed wall stands behind him.",
        "He sips his coffee calmly, then suddenly freezes and turns his head sharply toward something off-screen.",
        [b(0, "When the inspector pulls up", "inspector")], [{ type: "air", at: 0, dur: 2.4 }, { type: "whoosh", at: 1.7 }]),
      shot("s2", 3.4, "He stands perfectly upright on the spotless jobsite with a push broom held like a staff, chest out, the framed wall behind him perfectly square, everything neatly stacked, a proud closed-mouth smile.",
        "He sweeps one last perfectly clean stroke with the push broom, then stands to attention with the broom upright and nods once, proud.",
        [b(0.1, "Already ready.", "ready.")], [{ type: "beat", at: 0, dur: 3.4, bpm: 118, gain: 0.6 }, { type: "ding", at: 2.4 }]),
    ],
    sound: "Quiet morning air, a swish on the head turn, then a proud little march and a bell.",
    caption: "No panic. The work was right before the truck pulled in.",
    hashtags: ["construction", "contractorlife", "buildinginspection", "generalcontractor", "contractorhumor"],
    linkedin: "The inspections that go quickly are the ones where nothing had to be tidied when the truck pulled in. Do it right while nobody is looking, and inspection day is just another Tuesday.",
    youtubeTitle: "When the inspector pulls up (already ready)",
  },
  {
    id: "lunch-1159", title: "11:59 on the jobsite", format: "job-site pain", evergreen: true,
    hook: "11:59 AM.",
    shots: [
      shot("s1", 2.4, "He holds a spirit level against a wooden post on a sunny jobsite, concentrating hard, snout close to the level.",
        "He holds the level steady against the post, concentrating. Then his head snaps up as if he has heard something.",
        [b(0, "11:59 AM.", "11:59")], [{ type: "tick", at: 0.2, every: 0.5, until: 2.2 }, { type: "air", at: 0, dur: 2.4 }]),
      shot("s2", 3.2, `He sits on the open tailgate of ${TRUCK}, parked, legs dangling, happily holding an enormous sandwich in both hands, a lunch cooler beside him.`,
        "He sits on the tailgate swinging his boots, takes a big happy bite of the enormous sandwich and chews, content.",
        [b(0.1, "12:00 PM.", "12:00")], [{ type: "ding", at: 0 }, { type: "beat", at: 0.1, dur: 3.1, bpm: 112, gain: 0.6 }]),
    ],
    sound: "A clock ticking toward noon; a bell on the cut and an easy bed for lunch.",
    caption: "Nobody on this earth moves faster than a crew at noon.",
    hashtags: ["contractorlife", "lunchbreak", "construction", "bluecollar", "contractorhumor"],
    linkedin: null,
    youtubeTitle: "11:59 AM vs 12:00 PM on the jobsite",
  },
  {
    id: "measure-twice", title: "Measure twice, cut once", format: "job-site pain", evergreen: true,
    hook: "Measure twice. Cut once.",
    shots: [
      shot("s1", 3.0, "At a pair of sawhorses outdoors he bends over a long wooden board, measuring it carefully with an orange tape measure, a carpenter's pencil in his other hand.",
        "He measures the board carefully with the tape, marks it with the pencil, then measures it a second time and nods.",
        [b(0, "Measure twice. Cut once.", "twice.")], [{ type: "beat", at: 0, dur: 3.0, bpm: 108, gain: 0.5 }, { type: "tick", at: 0.8 }, { type: "tick", at: 2.0 }]),
      shot("s2", 3.2, "He holds the cut board up against an open doorway frame. The board is clearly a hand's width too short and does not reach the other side. He looks at the gap, deadpan.",
        "He holds the board up to the opening. It is too short. He looks at the gap, then slowly turns his head to the viewer, deadpan.",
        [b(0.2, "Still short.", "short.")], [{ type: "thud", at: 0.05 }, { type: "sad", at: 0.6 }]),
    ],
    sound: "A patient bed with two pencil ticks; a thud and the “wah-wah”.",
    caption: "Measured twice. Cut once. Read the tape wrong both times.",
    hashtags: ["carpentry", "woodworking", "contractorlife", "contractorhumor", "construction"],
    linkedin: null,
    youtubeTitle: "Measure twice, cut once… still short",
  },
  {
    id: "first-cold-morning", title: "First cold morning of the season", format: "job-site pain", evergreen: false, timing: "Seasonal: the first frosty week of autumn.",
    hook: "First cold morning of the season",
    shots: [
      shot("s1", 3.2, `At dawn he scrapes thick frost off the windscreen of ${TRUCK} with a tiny plastic card, bundled in a thick scarf over his hoodie, his breath a big white cloud.`,
        "He scrapes a small patch of frost off the windscreen with the tiny card, breath puffing out in white clouds. He pauses and looks at how much frost is left.",
        [b(0, "First cold morning of the season", "cold")], [{ type: "air", at: 0, dur: 3.2, gain: 1.5 }, { type: "pop", at: 0.4, every: 0.45, until: 2.4, gain: 0.25 }]),
      shot("s2", 2.8, `He sits in the driver's seat of the parked ${TRUCK}, seen through the side window, hunched over a steaming paper coffee cup held in both hands, a small clear patch scraped in the frosted windscreen.`,
        "He sits hunched and still, holding the steaming coffee close, a tiny shiver running through him. Steam rises from the cup.",
        [b(0.1, "Five more minutes.", "Five")], [{ type: "air", at: 0, dur: 2.8 }, { type: "tick", at: 0.5, every: 1, until: 2.5, gain: 0.6 }]),
    ],
    sound: "Cold wind and scraping; then a quiet cab and a slow clock.",
    caption: "The scraper is in the other truck. It is always in the other truck.",
    hashtags: ["contractorlife", "construction", "bluecollar", "wintermorning", "contractorhumor"],
    linkedin: null,
    youtubeTitle: "First cold morning of the season (jobsite edition)",
  },
  {
    id: "phone-on-the-ladder", title: "The phone rings on the ladder", format: "job-site pain", evergreen: true,
    hook: "Phone rings. You're on the ladder.",
    shots: [
      shot("s1", 3.0, "He stands on a stepladder beside a house wall, three points of contact: both boots on a rung and one hand gripping the ladder, a paintbrush in the other hand. A phone in his chest pocket glows and shakes with small vibration lines.",
        "The phone in his pocket buzzes and glows. He glances down at it, shakes his head calmly and keeps hold of the ladder.",
        [b(0, "Phone rings. You're on the ladder.", "ladder.")], [{ type: "tick", at: 0.2, every: 0.12, until: 0.9 }, { type: "tick", at: 1.5, every: 0.12, until: 2.2 }, { type: "air", at: 0, dur: 3.0 }]),
      shot("s2", 3.0, "He stands on the ground beside the stepladder, both boots on the grass, holding the phone to the side of his head, relaxed, one hand on his hip.",
        "Standing on the ground, he lifts the phone to the side of his head and nods along, relaxed.",
        [b(0.1, "It can wait till I'm down.", "down.")], [{ type: "ding", at: 0.1 }, { type: "beat", at: 0.2, dur: 2.8, bpm: 104, gain: 0.5 }]),
    ],
    sound: "A buzzing phone over quiet air; a bell and an easy bed once his boots are on the ground.",
    caption: "Nobody's call is worth the fall. Boots on the ground first.",
    hashtags: ["laddersafety", "contractorlife", "construction", "safetyfirst", "painting"],
    linkedin: "Most calls on a jobsite arrive at the worst moment. The habit worth having is the boring one: climb down, then answer. A missed call costs a minute.",
    youtubeTitle: "Phone rings while you're on the ladder",
  },
  {
    id: "quick-question-947", title: "A quick question at 9:47 PM", format: "job-site pain", evergreen: true,
    hook: "9:47 PM: “quick question…”",
    shots: [
      shot("s1", 3.0, "At night he sits sunk into a big armchair in a cosy living room, still in his full work gear and hard hat, boots up on a footstool, a blanket over his knees. A phone on the armrest lights up, glowing, showing nothing readable.",
        "He dozes in the armchair. The phone on the armrest lights up and buzzes. His head lifts slowly.",
        [b(0, "9:47 PM: “quick question…”", "“quick")], [{ type: "air", at: 0, dur: 3.0 }, { type: "ding", at: 1.0 }]),
      shot("s2", 3.0, "In the same armchair he holds the glowing phone in both hands and types with his thumbs, a small tired smile, the blanket still on his knees.",
        "He types on the phone with both thumbs, nodding slightly, a small tired smile.",
        [b(0.1, "Me, answering anyway.", "anyway.")], [{ type: "tick", at: 0.2, every: 0.18, until: 2.6, gain: 0.5 }]),
    ],
    sound: "A sleepy room, one notification bell, then soft key taps.",
    caption: "It's never quick. I'm answering anyway. That's the job.",
    hashtags: ["contractorlife", "smallbusiness", "construction", "contractorhumor", "remodeling"],
    linkedin: "The evening “quick question” is a sign of trust, and answering it well is part of the service. It is also why the answers belong in one place tomorrow morning — not in a text thread nobody can find in June.",
    youtubeTitle: "9:47 PM: “quick question about the tile”",
  },
  {
    id: "coffee-ran-out", title: "The coffee ran out at 7:15", format: "job-site pain", evergreen: true,
    hook: "7:15 AM. The coffee is gone.",
    shots: [
      shot("s1", 3.4, "On an early-morning jobsite he holds a steel thermos upside down above a paper cup, peering up into it. One single drop hangs from the thermos.",
        "He shakes the upside-down thermos. One single drop falls into the cup. He peers into the thermos, then into the cup.",
        [b(0, "7:15 AM. The coffee is gone.", "gone.")], [{ type: "air", at: 0, dur: 3.4 }, { type: "tick", at: 1.4 }]),
      shot("s2", 2.8, "He stands holding the empty paper cup, staring into the distance over the jobsite, completely deadpan, the thermos hanging from his other hand.",
        "He stares into the distance, motionless and deadpan. A light wind moves a scrap of paper across the ground behind him.",
        [b(0.2, "Long day ahead.", "Long")], [{ type: "sad", at: 0.3 }, { type: "air", at: 0, dur: 2.8 }]),
    ],
    sound: "Morning air, one drip, then the “wah-wah”.",
    caption: "Some losses you feel all day.",
    hashtags: ["contractorlife", "coffee", "construction", "bluecollar", "contractorhumor"],
    linkedin: null,
    youtubeTitle: "7:15 AM and the coffee is already gone",
  },
  {
    id: "dumpster-day-three", title: "The dumpster on day three", format: "job-site pain", evergreen: true,
    hook: "“One dumpster will be plenty.”",
    shots: [
      shot("s1", 2.6, "He stands beside a large plain, unmarked, empty skip in a driveway, patting its side confidently, a demolition site behind him.",
        "He pats the side of the empty skip confidently and nods.",
        [b(0, "“One dumpster will be plenty.”", "plenty.”")], [{ type: "thud", at: 0.6, gain: 0.5 }, { type: "beat", at: 0, dur: 2.6, bpm: 108, gain: 0.5 }]),
      shot("s2", 3.4, "The same plain skip is now heaped far above its rim with broken drywall, old boards and cardboard. He stands on the ground beside it holding one more short board, looking up at the heap.",
        "He looks up at the towering heap, then very gently places one more board on the edge of the pile and tiptoes backward. The heap wobbles slightly and holds.",
        [b(0.1, "Day three.", "three.")], [{ type: "tick", at: 0.8, every: 0.4, until: 2.8 }, { type: "ding", at: 3.0, gain: 0.6 }]),
    ],
    sound: "A confident bed and a pat; tiptoe ticks and a relieved bell when it holds.",
    caption: "Demo always finds more house than the plans promised.",
    hashtags: ["demolition", "remodeling", "contractorlife", "construction", "contractorhumor"],
    linkedin: null,
    youtubeTitle: "“One dumpster will be plenty” (day three)",
  },

  /* ── POV ───────────────────────────────────────────────────────────────── */
  {
    id: "pov-first-on-site", title: "POV: first one on site", format: "POV", evergreen: true, timing: "The POV label is a trend format; the scene is evergreen.",
    hook: "POV: first one on site",
    shots: [
      shot("s1", 4.6, `At sunrise he stands alone on a quiet, empty building lot beside ${TRUCK}, holding a paper coffee cup, looking out at a golden sky, mist over the ground, a framed house in silhouette.`,
        "He takes a slow sip of coffee and breathes out, looking at the sunrise. Mist drifts over the ground. The light slowly brightens. Peaceful.",
        [b(0, "POV: first one on site", "first"), b(2.6, "Quietest part of the day.", "day.", "low")], [{ type: "air", at: 0, dur: 4.6 }, { type: "ding", at: 2.6, gain: 0.4 }]),
    ],
    sound: "Just dawn air and one soft bell — the quiet is the point.",
    caption: "Twenty minutes before the saws start. Nobody tell the others.",
    hashtags: ["contractorlife", "construction", "sunrise", "bluecollar", "jobsite"],
    linkedin: "The first twenty minutes on site, before the saws start, are when the day gets planned. It is the quietest meeting of the week.",
    youtubeTitle: "POV: you're the first one on site",
  },
  {
    id: "pov-bubble-dead-centre", title: "POV: the bubble is dead centre", format: "POV", evergreen: true,
    hook: "POV: the bubble is dead centre",
    shots: [
      shot("s1", 4.4, "Close-up: a yellow spirit level rests on a wooden beam, its bubble sitting exactly between the two lines. His face is right beside the level, snout low to the beam, a slow satisfied smile.",
        "The bubble in the spirit level drifts slightly and settles exactly in the centre. He watches it, then slowly smiles and nods. Slow push-in on the bubble.",
        [b(0, "POV: the bubble is dead centre", "dead"), b(2.8, "First try.", "First", "low")], [{ type: "air", at: 0, dur: 4.4 }, { type: "ding", at: 2.7 }]),
    ],
    sound: "Quiet, then one bright bell as the bubble settles.",
    caption: "No shims. No second look. Just centre.",
    hashtags: ["carpentry", "satisfying", "construction", "contractorlife", "framing"],
    linkedin: null,
    youtubeTitle: "POV: the bubble is dead centre, first try",
  },
  {
    id: "pov-zero-punch-list", title: "POV: zero punch list", format: "POV", evergreen: true,
    hook: "POV: final walkthrough. Zero punch list.",
    shots: [
      shot("s1", 2.8, "He walks through a bright, finished, empty kitchen with new cabinets and a clean floor, holding a clipboard whose page shows only a column of green tick marks and no writing.",
        "He walks slowly through the finished kitchen, looking around, running one hand along the countertop, glancing at the clipboard.",
        [b(0, "POV: final walkthrough. Zero punch list.", "Zero")], [{ type: "beat", at: 0, dur: 2.8, bpm: 104, gain: 0.5 }]),
      shot("s2", 2.8, "In the same finished kitchen he stands with one fist raised in a small, restrained fist pump, the clipboard under his arm, a proud closed-mouth grin.",
        "He does one small, restrained fist pump and nods, proud.",
        [b(0.1, "Nothing. Not one thing.", "Nothing.")], [{ type: "ding", at: 0.1 }, { type: "beat", at: 0.1, dur: 2.7, bpm: 104, gain: 0.7 }]),
    ],
    sound: "An easy walking bed; a bell on the fist pump.",
    caption: "It happens about twice a career. Let me have this.",
    hashtags: ["remodeling", "contractorlife", "construction", "kitchenremodel", "generalcontractor"],
    linkedin: "A walkthrough with an empty punch list is not luck. It is every small thing closed out the day it was noticed, instead of saved for the end.",
    youtubeTitle: "POV: final walkthrough with zero punch list",
  },
  {
    id: "pov-organised-truck", title: "POV: you finally organised the truck", format: "POV", evergreen: true,
    hook: "POV: you finally organised the truck",
    shots: [
      shot("s1", 2.8, `He stands at the open tailgate of ${TRUCK}, presenting the truck bed with both hands: every tool in its own tray, boxes lined up, hoses coiled, a soft golden glow over it all.`,
        "He presents the perfectly organised truck bed with a proud sweep of his hand. A soft golden glow shimmers over the tools.",
        [b(0, "POV: you finally organised the truck", "organised")], [{ type: "ding", at: 0.2 }, { type: "air", at: 0, dur: 2.8 }]),
      shot("s2", 3.0, `He stands at the same open tailgate of ${TRUCK}, now a jumble of tangled extension cords, loose tools, empty paper cups and offcuts, scratching the back of his hard hat.`,
        "He looks at the jumbled truck bed and slowly scratches the back of his hard hat. A paper cup rolls off the tailgate.",
        [b(0.1, "Day two.", "two.")], [{ type: "thud", at: 0.05 }, { type: "sad", at: 0.5 }]),
    ],
    sound: "A heavenly bell over the tidy bed; a thud and the “wah-wah” a day later.",
    caption: "It was beautiful. For about nine hours.",
    hashtags: ["contractorlife", "tools", "truckorganization", "construction", "contractorhumor"],
    linkedin: null,
    youtubeTitle: "POV: you finally organised the truck (day two)",
  },
  {
    id: "pov-passed-first-try", title: "POV: inspection passed, first try", format: "POV", evergreen: true,
    hook: "POV: passed inspection. First try.",
    shots: [
      shot("s1", 4.6, "Inside a newly framed house he stands beside a wall stud that has a plain bright-green tag with nothing written on it stapled to it, arms crossed, a slow proud nod, sunlight through the framing.",
        "He looks at the plain green tag on the stud, crosses his arms and nods slowly, proud. Sunbeams and dust drift through the framing. Slow push-in.",
        [b(0, "POV: passed inspection. First try.", "passed"), b(2.8, "On to the next one.", "next", "low")], [{ type: "ding", at: 0.2 }, { type: "beat", at: 0.3, dur: 4.3, bpm: 100, gain: 0.6 }]),
    ],
    sound: "A bell and a steady, proud bed.",
    caption: "Green tag. No notes. We ride at dawn.",
    hashtags: ["construction", "framing", "buildinginspection", "contractorlife", "generalcontractor"],
    linkedin: "Passing first time is mostly paperwork done early: the right permit, the right office, the inspection booked before the wall is closed. The framing is the easy part.",
    youtubeTitle: "POV: passed inspection on the first try",
  },

  /* ── Satisfying work ───────────────────────────────────────────────────── */
  {
    id: "chalk-line-snap", title: "One snap of the chalk line", format: "satisfying work", evergreen: true,
    hook: "Chalk line. One snap.",
    shots: [
      shot("s1", 4.4, "He kneels on a clean plywood subfloor inside a framed house, holding a chalk line stretched tight across the floor with one hand, pinching the string up in the middle with the other, about to snap it.",
        "He lifts the tight string and lets it snap down. A puff of blue chalk dust jumps up and a perfectly straight blue line is left across the plywood. He nods.",
        [b(0, "Chalk line. One snap.", "snap."), b(2.6, "Dead straight.", "straight.", "low")], [{ type: "air", at: 0, dur: 4.4 }, { type: "pop", at: 1.4 }, { type: "ding", at: 2.6, gain: 0.5 }]),
    ],
    sound: "Silence, one crisp snap, a bell.",
    caption: "The most satisfying sound in framing. Fight me (politely).",
    hashtags: ["carpentry", "framing", "satisfying", "construction", "contractorlife"],
    linkedin: null,
    youtubeTitle: "Chalk line, one snap, dead straight",
  },
  {
    id: "deck-boards-rhythm", title: "Deck boards, one after another", format: "satisfying work", evergreen: true,
    hook: "Deck boards. One after another.",
    shots: [
      shot("s1", 4.2, "He kneels on a half-built wooden deck in a back garden, driving a screw into a deck board with a cordless drill, a row of evenly spaced boards behind him and bare joists ahead.",
        "He drives a screw with the drill, shifts along, drives the next, shifts along, in an even rhythm. The camera slides along the deck with him.",
        [b(0, "Deck boards. One after another.", "another.")], [{ type: "pop", at: 0.3, every: 0.6, until: 4.0, gain: 0.7 }, { type: "beat", at: 0, dur: 4.2, bpm: 100, gain: 0.5 }]),
      shot("s2", 2.4, "He stands on the finished wooden deck with his arms crossed, every board evenly spaced and every screw in a straight line, evening sun.",
        "Arms crossed, he looks along the perfectly even deck boards and nods. Slow pull back.",
        [b(0.1, "Even gaps. Every one.", "Even")], [{ type: "ding", at: 0.1 }, { type: "air", at: 0, dur: 2.4 }]),
    ],
    sound: "Drill hits on the beat; a bell on the finished deck.",
    caption: "Same gap. Same line. Forty boards. No thoughts.",
    hashtags: ["deckbuilding", "carpentry", "satisfying", "construction", "contractorlife"],
    linkedin: null,
    youtubeTitle: "Deck boards, one after another (satisfying)",
  },
  {
    id: "one-pass-no-drips", title: "One pass, no drips", format: "satisfying work", evergreen: true,
    hook: "One pass. No drips.",
    shots: [
      shot("s1", 4.6, "In an empty room with dust sheets on the floor he rolls a paint roller on an extension pole up a wall, standing on the floor, leaving a clean wide stripe of fresh sage-green paint on a pale wall.",
        "He rolls the paint roller smoothly up and down the wall, leaving clean, even stripes of fresh paint that join without a mark. Calm and steady.",
        [b(0, "One pass. No drips.", "drips."), b(3.0, "Cut in. Roll out. Done.", "Done.", "low")], [{ type: "whoosh", at: 0.4, dur: 0.7, gain: 0.5 }, { type: "whoosh", at: 1.6, dur: 0.7, gain: 0.5 }, { type: "whoosh", at: 2.8, dur: 0.7, gain: 0.5 }, { type: "beat", at: 0, dur: 4.6, bpm: 96, gain: 0.4 }]),
    ],
    sound: "Soft roller swishes over a slow bed.",
    caption: "Paint that goes on like this is 90% prep. The gator did the prep.",
    hashtags: ["painting", "satisfying", "housepainter", "contractorlife", "remodeling"],
    linkedin: null,
    youtubeTitle: "One pass, no drips (gator painting)",
  },
  {
    id: "smooth-concrete", title: "Smooth", format: "satisfying work", evergreen: true,
    hook: "Smooth.",
    shots: [
      shot("s1", 4.6, "He kneels on kneeboards at the edge of a fresh grey concrete slab, sweeping a steel trowel across it in a wide arc, the surface behind the trowel glassy and reflecting the sky.",
        "He sweeps the steel trowel across the wet concrete in slow, wide arcs. Behind the trowel the surface turns glassy smooth and reflects the sky. Slow push-in.",
        [b(0, "Smooth.", "Smooth."), b(3.0, "Do not walk on it.", "not", "low")], [{ type: "whoosh", at: 0.3, dur: 0.9, gain: 0.5 }, { type: "whoosh", at: 1.7, dur: 0.9, gain: 0.5 }, { type: "whoosh", at: 3.1, dur: 0.9, gain: 0.5 }, { type: "air", at: 0, dur: 4.6 }]),
    ],
    sound: "Slow trowel swishes and open air.",
    caption: "Glass. Do not walk on it. Yes, that includes the dog.",
    hashtags: ["concrete", "satisfying", "concretelife", "construction", "contractorlife"],
    linkedin: null,
    youtubeTitle: "Smooth. (gator finishing concrete)",
  },
  {
    id: "cleanest-jobsite", title: "The cleanest jobsite on the street", format: "satisfying work", evergreen: true,
    hook: "End of day. Cleanest site on the street.",
    shots: [
      shot("s1", 3.2, "At golden hour he pushes a wide push broom across a driveway, a neat line of sawdust ahead of the broom and spotless concrete behind it, tools stacked tidily by the garage.",
        "He pushes the broom in long, even strokes. Sawdust gathers in a neat line ahead of it, leaving spotless concrete behind.",
        [b(0, "End of day. Cleanest site on the street.", "Cleanest")], [{ type: "whoosh", at: 0.2, dur: 0.6, gain: 0.5 }, { type: "whoosh", at: 1.2, dur: 0.6, gain: 0.5 }, { type: "whoosh", at: 2.2, dur: 0.6, gain: 0.5 }, { type: "beat", at: 0, dur: 3.2, bpm: 100, gain: 0.4 }]),
      shot("s2", 2.6, "He stands on the spotless driveway leaning on the push broom, tools stacked neatly, the house tidy behind him, a satisfied closed-mouth smile, warm evening light.",
        "He leans on the broom, looks over the spotless driveway and nods once, satisfied.",
        [b(0.1, "That's the reference.", "reference.")], [{ type: "ding", at: 0.1 }, { type: "air", at: 0, dur: 2.6 }]),
    ],
    sound: "Broom swishes on a slow bed; a bell at the end.",
    caption: "The neighbours notice the broom before they notice the work. Sweep.",
    hashtags: ["contractorlife", "satisfying", "construction", "remodeling", "generalcontractor"],
    linkedin: "A swept driveway at five o'clock is the cheapest marketing a contractor does. The neighbours are the next three jobs, and they are watching the kerb, not the framing.",
    youtubeTitle: "End of day: the cleanest jobsite on the street",
  },

  /* ── Product tie-ins (a light end tag — never a lecture) ───────────────── */
  {
    id: "permit-office-in-seconds", title: "Finding the permit office in seconds", format: "product tie-in", evergreen: true,
    hook: "Which office handles this permit?",
    shots: [
      shot("s1", 2.8, `He stands at the bonnet of ${TRUCK} with a large blank paper map spread across it, the map showing only plain shapes and no writing, scratching the back of his hard hat, puzzled.`,
        "He looks over the big paper map, turning it one way and then the other, and scratches the back of his hard hat, puzzled.",
        [b(0, "Which office handles this permit?", "permit?")], [{ type: "tick", at: 0.3, every: 0.5, until: 2.6 }, { type: "air", at: 0, dur: 2.8 }]),
      shot("s2", 3.0, `He leans against ${TRUCK} holding a phone in one hand, its screen a soft plain glow with nothing readable, giving a thumbs-up with the other hand, a relaxed closed-mouth grin. The paper map lies folded on the bonnet.`,
        "He looks at the glowing phone, nods, and gives a slow thumbs-up to the viewer.",
        [b(0.1, "Found it. In seconds.", "seconds.")], [{ type: "ding", at: 0.1 }, { type: "beat", at: 0.2, dur: 2.8, bpm: 112, gain: 0.6 }]),
    ],
    sound: "A puzzled clock; a bell and an easy bed when he finds it.",
    caption: "City or county? Which portal? Look the permit office up before you drive — the directory is at constructhub.us.",
    hashtags: ["buildingpermit", "contractorlife", "construction", "generalcontractor", "permits"],
    linkedin: "Half the time lost on a permit is spent finding out who issues it: the city, the county, or a portal with a different name. The ConstructHUB directory lists permit offices and portals by city and county, so the first call goes to the right counter.",
    youtubeTitle: "Which office handles this permit? Found it in seconds",
  },
  {
    id: "estimate-from-the-truck", title: "Sending the estimate from the truck", format: "product tie-in", evergreen: true,
    hook: "Estimate sent. Still in the driveway.",
    shots: [
      shot("s1", 3.0, `He sits in the driver's seat of the parked ${TRUCK}, engine off, door open, seen from outside, tapping a phone with one thumb, a steaming paper coffee cup on the dashboard. A house and its front garden are behind the truck.`,
        "Sitting in the parked truck, he taps the phone a few times with his thumb, then gives one firm final tap and nods.",
        [b(0, "Estimate sent. Still in the driveway.", "sent.")], [{ type: "tick", at: 0.3, every: 0.3, until: 1.8, gain: 0.5 }, { type: "whoosh", at: 2.2 }, { type: "ding", at: 2.45, gain: 0.6 }]),
      shot("s2", 2.8, `In the same parked ${TRUCK} he leans back in the seat and picks up the steaming paper coffee cup, relaxed, a satisfied closed-mouth smile.`,
        "He leans back, picks up the coffee, takes a calm sip and breathes out, relaxed. Steam rises from the cup.",
        [b(0.1, "Coffee's still hot.", "hot.")], [{ type: "beat", at: 0, dur: 2.8, bpm: 104, gain: 0.6 }]),
    ],
    sound: "Thumb taps, a send swish and bell; an easy bed for the coffee.",
    caption: "Walk the job, price the job, send the estimate before you back out of the driveway. Estimates live in the ConstructHUB CRM — a separate product with its own plans.",
    hashtags: ["contractorlife", "estimating", "construction", "smallbusiness", "generalcontractor"],
    linkedin: "The estimate that arrives while the contractor is still in the driveway wins more often than the better one that arrives on Thursday. Building it on the phone, from the job just walked, is the whole trick. (Estimates are part of the ConstructHUB CRM, a separate product with its own plans.)",
    youtubeTitle: "Estimate sent before leaving the driveway",
  },
];
