/**
 * The LIVE-ACTION gator (2026-10-08, the owner's experiment): a photoreal alligator in the brand's hard
 * hat, shades and hi-vis vest, in clips that look like something a person filmed on a phone by accident.
 * The formula of the owner's two reference clips (an AI squirrel "doing parkour" over an AC unit; an AI
 * selfie vlog that goes wrong while its character never stops talking):
 *   · ONE continuous take, 6–15 s; one gag you understand in half a second with the sound off;
 *   · mundane place, flat daylight, imperfect framing; loud natural sound;
 *   · NOTHING burned into the picture — the brand is what he wears, the caption and the account;
 *   · every post is labelled AI-generated by the platform flag and carries #AIContent.
 * THE LINE holds: he is always fine and pops back up; no people are hurt (there are no people); nothing
 * that reads as a real accident, a real animal attack or cruelty; he never bites or threatens; no brands,
 * no real people, nobody else's character. The joke is always on HIS overconfidence — never advice.
 */
import type { Concept, Shot } from "./concepts";

/** The model sheet: drawn once from text, then the reference of every live still. */
export const LIVE_SHEET_PROMPT = "A photograph taken on a phone in flat overcast daylight on a gravel construction lot: a real adult American alligator standing fully upright on its hind legs like a person, facing the camera in a relaxed three-quarter stance, full body in frame from hard hat to feet and tail — photorealistic, real scales, real proportions, dark olive-green hide, pale cream throat and belly, long snout, mouth closed — wearing a clean yellow construction hard hat, dark wraparound safety sunglasses and an orange hi-vis safety vest with silver reflective stripes; its tail rests on the ground behind it. Plain background: a stack of lumber and a chain-link fence, out of the way. Everything in focus, no cinematic lighting, no filter. No people. No text, letters, numbers, logos, brand names or watermarks anywhere.";

const SELFIE = "Selfie taken by the alligator himself: one scaly forearm reaches out to the edge of the frame toward the lens, holding the phone at arm's length; wide-angle front camera; his head, hard hat and shoulders fill the lower two thirds of the frame; he looks straight into the lens with his mouth slightly open, mid-sentence.";
const ONE_TAKE = "ONE continuous handheld selfie take filmed by the alligator himself, no cuts, photorealistic phone footage, natural daylight.";
const ALWAYS = "He is never hurt. His hard hat, dark sunglasses and orange vest stay on the whole time. Exactly one alligator; no people appear. No text, captions, logos or watermarks appear in the picture. Loud natural sound only: his voice and what happens around him — no music.";
const tags = ["contractorlife", "construction", "aicontent", "jobsite", "bluecollar"];

/** A selfie vlog that goes wrong while he keeps talking. `script`: what he says, as checked against the take. */
const selfie = (n: number, id: string, title: string, seconds: number, scene: string, action: string, script: string, caption: string): Concept => {
  const shot: Shot = { id: "s1", look: "live", video: "talk", seconds, use: seconds, rawMotion: true, scene: `${SELFIE} ${scene}`, motion: `${ONE_TAKE} ${action} ${ALWAYS}`, say: { text: script }, beats: [], cues: [] };
  void n;
  return { id, title, format: "job-site pain", cut: "oneshot", look: "live", style: 1, evergreen: true, sample: true, hook: caption, shots: [shot], sound: "His own voice and the disaster, as the model renders them; nothing added.", caption, hashtags: tags, linkedin: null, youtubeTitle: title };
};

const PHONE = "It looks like a frame from an ordinary phone video: flat natural daylight, slightly imperfect framing, everything in focus, no cinematic lighting, no filter. Vertical 9:16, filling the frame edge to edge. No text, letters, numbers, logos, brand names or watermarks anywhere.";
const FINE = "Nobody is hurt: it is clean, harmless slapstick. No blood, no injury. No text, captions, logos or watermarks appear in the picture. Loud natural sound only — no music.";

/** One continuous found-footage take of the live gator (or the cast): nothing burned in. */
const oneshot = (o: { id: string; style: number; title: string; caption: string; seconds: number; scene: string; action: string; script?: string; cast?: boolean; voice?: "none"; overlay?: "cctv"; meme?: string; subtitled?: boolean }): Concept => ({
  id: o.id, title: o.title, format: "job-site pain", cut: "oneshot", look: "live", style: o.style, evergreen: true, sample: true, hook: o.caption, ...(o.overlay ? { overlay: o.overlay } : {}), ...(o.meme ? { meme: o.meme } : {}),
  shots: [{ id: "s1", look: "live", video: "talk", seconds: o.seconds, use: o.seconds, rawMotion: true, ...(o.cast ? { rawStill: true, voice: "none" as const } : {}), ...(o.voice ? { voice: o.voice } : {}), scene: o.cast ? `${o.scene} ${PHONE}` : o.scene, motion: `${o.action} ${FINE}`, ...(o.script ? { say: { text: o.script } } : {}), beats: [], cues: [] }],
  sound: "The take's own sound.", caption: o.caption, hashtags: tags, linkedin: null, youtubeTitle: o.title,
});

/** STYLE 7 — a cliché, then a hard cut to OUR goat (generated once: "our-goat"). Subtitled; 0.8 s tag. */
const cutaway = (o: { id: string; style: number; title: string; caption: string; seconds: number; scene: string; action: string; script: string }): Concept => ({
  id: o.id, title: o.title, format: "job-site pain", look: "live", style: o.style, subtitles: true, endTagSec: 0.8, logo: false, evergreen: true, sample: true, hook: o.caption,
  shots: [
    { id: "s1", look: "live", video: "talk", voice: "none", seconds: o.seconds, use: o.seconds, rawMotion: true, scene: o.scene, motion: `${o.action} ${FINE}`, say: { text: o.script }, beats: [], cues: [] },
    { id: "s2", look: "live", video: "talk", videoFrom: "our-goat/s1", scene: "", motion: "", from: 0.35, use: 2.6, ownGain: 0.95, beats: [], cues: [] },
  ],
  sound: "The line; then the goat.", caption: o.caption, hashtags: tags, linkedin: null, youtubeTitle: o.title,
});
/** STYLE 2 — the selfie vlog with the cartoon mascot (drawn from the mascot's own artwork). */
const mascotSelfie = (o: { id: string; title: string; caption: string; seconds: number; scene: string; action: string; script: string }): Concept => ({
  id: o.id, title: o.title, format: "job-site pain", cut: "oneshot", style: 2, evergreen: true, sample: true, hook: o.caption,
  shots: [{ id: "s1", video: "talk", seconds: o.seconds, use: o.seconds, rawMotion: true, scene: o.scene, motion: `ONE continuous selfie take filmed by the cartoon alligator himself, no cuts — 2D cartoon animation in the same bold cel-shaded style as the image throughout. ${o.action} His sunglasses are opaque and dark with an orange tint at all times: his eyes are never visible. His hard hat stays on. Nobody is hurt. No text appears. Loud sound: his voice and what happens behind him — no music.`, say: { text: o.script }, beats: [], cues: [] }],
  sound: "The take's own sound.", caption: o.caption, hashtags: tags, linkedin: null, youtubeTitle: o.title,
});
/** STYLE 10 — the hot take: the gator, a coffee, one line (on a still that was already drawn). */
const hotTake = (o: { id: string; title: string; stillFrom: string; line: string; prompt: string }): Concept => ({
  id: o.id, title: o.title, format: "job-site pain", cut: "oneshot", look: "live", style: 10, evergreen: true, sample: true, hook: o.line,
  shots: [{ id: "s1", look: "live", video: "talk", seconds: 5, use: 5, rawMotion: true, stillFrom: o.stillFrom, scene: "", motion: `ONE continuous handheld phone take, photorealistic. The alligator holds his coffee, looks straight into the lens and says, completely deadpan and unhurried: "${o.prompt}" Then he takes a slow sip. He is the only character. No text appears. Natural sound only — no music.`, say: { text: o.line }, beats: [], cues: [] }],
  sound: "His voice.", caption: o.line, hashtags: tags, linkedin: o.line, youtubeTitle: o.title,
});

/**
 * ACCIDENT v2 (the owner, 2026-10-08: "The accident videos were not great since they didn't look like an
 * accident" — and: "the one where the alligator falls off the roof is funny"). What was wrong with v1: he
 * walks in already performing, the fall is slow and floaty, the camera is centred on the spot and waiting,
 * nothing else in the scene reacts. The recipe now:
 *   · he is BUSY and unaware — carrying, climbing, talking to someone off-frame; no wind-up, no look at the lens;
 *   · the camera is filming SOMETHING ELSE and the accident happens at the edge or in the background; then it
 *     whips round late, shakes, and the person filming is heard;
 *   · weight and speed: real time, a hard stop, debris that keeps moving, a second thing going over a beat later;
 *   · the scene reacts: a dog, a "…you good?", and his thumbs-up — so it stays comedy.
 * The limits are unchanged: an animal takes the hit, never a person (the people filming are voices only);
 * no blood, no injury; he is shown fine.
 */
const FOUND = "Found-footage realism: ordinary compressed phone video, slightly soft, the exposure shifts when the camera swings, a little wind noise on the microphone, imperfect framing. Everything happens at real speed with real weight — fast acceleration, a hard stop, dust and debris that keep moving afterwards. No slow motion.";
const SAFE = "The alligator is not hurt: no blood, no injury is shown, and he is clearly fine at the end. No human being appears in the picture at any time — the person filming is only heard. His hard hat, dark sunglasses and orange vest stay on. No text, captions, logos or watermarks appear in the picture. No music.";
const accident = (o: { id: string; title: string; caption: string; seconds: number; scene: string; action: string; script?: string; voice?: "none" }): Concept => ({
  id: o.id, title: o.title, format: "job-site pain", cut: "oneshot", look: "live", style: 16, evergreen: true, sample: true, hook: o.caption,
  shots: [{ id: "s1", look: "live", video: "talk", seconds: o.seconds, use: o.seconds, rawMotion: true, ...(o.voice ? { voice: o.voice } : {}), scene: `${o.scene} ${PHONE}`, motion: `${o.action} ${FOUND} ${SAFE}`, ...(o.script ? { say: { text: o.script } } : {}), beats: [], cues: [] }],
  sound: "The take's own sound.", caption: o.caption, hashtags: tags, linkedin: null, youtubeTitle: o.title,
});
/** A five-second fail of the animal cast, for the "Gator Reacts" episodes: found footage, sudden, they walk away. */
const quickFail = (o: { id: string; title: string; caption: string; scene: string; action: string }): Concept => ({
  id: o.id, title: o.title, format: "job-site pain", cut: "oneshot", look: "live", style: 17, evergreen: true, sample: true, hook: o.caption,
  shots: [{ id: "s1", look: "live", video: "talk", voice: "none", seconds: 5, use: 5, rawMotion: true, rawStill: true, scene: `${o.scene} ${PHONE}`, motion: `ONE continuous handheld phone take, photorealistic, filmed by a coworker who is never seen. ${o.action} ${FOUND} The animal is not hurt: no blood, no injury; it gets straight back up, unharmed. No human being appears. No text, captions, logos or watermarks appear in the picture. Loud natural sound, no music.`, beats: [], cues: [] }],
  sound: "The take's own sound.", caption: o.caption, hashtags: tags, linkedin: null, youtubeTitle: o.title,
});
/**
 * THE REACTION PACK and the HOST LINES of "Gator Reacts": the live gator in one framing (the still of the
 * coffee-and-ladder shot, so they cut together and with the coffee shots that already exist), a few seconds each.
 */
const HOST_STILL = "moment-ladders/s2";
const HOST_HOLD = "ONE continuous steady phone take, photorealistic; the camera does not move and the framing does not change. The alligator stands exactly where he is, holding his paper coffee cup in one claw.";
const HOST_END = "He is the only character; nobody else appears. His hard hat, dark opaque sunglasses and orange vest stay on; his eyes are never visible. No text appears. No music.";
const reaction = (name: string, title: string, action: string, sound: string): Concept => ({
  id: `react-${name}`, title, format: "job-site pain", cut: "oneshot", look: "live", style: 17, evergreen: true, sample: true, hook: title,
  shots: [{ id: "s1", look: "live", video: "talk", voice: "none", seconds: 3, use: 3, rawMotion: true, stillFrom: HOST_STILL, scene: "", motion: `${HOST_HOLD} He is watching something off to the side of the camera, just past the lens. ${action} He does not speak any words. ${HOST_END} Sound: ${sound}`, beats: [], cues: [] }],
  sound: "The take's own sound.", caption: title, hashtags: tags, linkedin: null, youtubeTitle: title,
});
const VIEWER_STILL = "_reactions/REFERENCE-doorbell-clipboard.png";
const VIEWER_HOLD = "ONE continuous steady phone take, photorealistic; the camera does not move and the framing does not change. The alligator stands upright exactly where he is in front of the doorway, close to the lens, facing it, holding his clipboard in one claw. He is watching a screen just below the lens.";
const VIEWER_END = "He is the only character; nobody else appears; nothing happens to him and nothing else in the scene changes. His yellow hard hat, dark opaque sunglasses and orange vest stay on; his eyes are never visible. Never a smile, never a grin, never laughing. No text appears. No music.";
const viewer = (name: string, title: string, action: string, sound: string, seconds = 3): Concept => ({
  id: `rv-${name}`, title, format: "job-site pain", cut: "oneshot", look: "live", style: 17, evergreen: true, sample: true, hook: title,
  shots: [{ id: "s1", look: "live", video: "talk", voice: "none", seconds, use: seconds, rawMotion: true, stillFile: VIEWER_STILL, scene: "", motion: `${VIEWER_HOLD} ${action} He does not speak any words. ${VIEWER_END} Sound: ${sound}`, beats: [], cues: [] }],
  sound: "The take's own sound.", caption: title, hashtags: tags, linkedin: null, youtubeTitle: title,
});
const hostLine = (name: string, line: string, seconds = 3): Concept => ({
  id: `host-${name}`, title: line, format: "job-site pain", cut: "oneshot", look: "live", style: 17, evergreen: true, sample: true, hook: line,
  shots: [{ id: "s1", look: "live", video: "talk", seconds, use: seconds, rawMotion: true, stillFrom: HOST_STILL, scene: "", motion: `${HOST_HOLD} He looks straight into the lens and says, completely deadpan and unhurried: "${line}" ${HOST_END}`, say: { text: line }, beats: [], cues: [] }],
  sound: "His voice.", caption: line, hashtags: tags, linkedin: null, youtubeTitle: line.slice(0, 60),
});

/**
 * STYLE 13 — "viral moment + gator button": our own scene on the engine of the stalling-before-the-inevitable
 * meme (a cast member talks with total confidence right up to the drop), small subtitles because the line
 * is the joke, then the gator's dry button and a 0.8 s tag. The cast are animals: nobody real is put in peril.
 */
const moment = (o: { id: string; title: string; caption: string; seconds: number; castStill: string; castAction: string; castScript: string; buttonScene: string; buttonAction: string; buttonLine: string; buttonSeconds?: number }): Concept => ({
  id: o.id, title: o.title, format: "job-site pain", look: "live", style: 13, subtitles: true, endTagSec: 0.8, logo: false, evergreen: true, sample: true, hook: o.caption,
  shots: [
    { id: "s1", look: "live", video: "talk", voice: "none", seconds: o.seconds, use: o.seconds, rawMotion: true, rawStill: true, scene: `${o.castStill} ${PHONE}`, motion: `${o.castAction} ${FINE}`, say: { text: o.castScript }, beats: [], cues: [] },
    { id: "s2", look: "live", video: "talk", seconds: o.buttonSeconds ?? 5, use: o.buttonSeconds ?? 5, rawMotion: true, scene: o.buttonScene, motion: `${o.buttonAction} He is the only character in the shot. No text appears. Natural sound only — no music.`, say: { text: o.buttonLine }, beats: [], cues: [] },
  ],
  sound: "The takes' own sound; a hit on the cut to the gator.", caption: o.caption, hashtags: tags, linkedin: null, youtubeTitle: o.title,
});

export const LIVE_CONCEPTS: Concept[] = [
  selfie(1, "selfie-deck", "Day one, new deck", 10,
    "He stands on a brand-new wooden backyard deck raised about a metre off the ground; behind him the deck boards, a railing and the back wall of a suburban house with a sliding glass door.",
    "He talks fast and cocky straight into the lens: \"Day one. New deck. Solid. I'm tellin' you, this thing ain't goin' nowhere—\" Mid-word the whole deck suddenly drops out from under him with a loud crack and crash of timber; the camera jolts, spins and shakes, a blur of sky, boards and dust; then he rises back into frame from below, covered in sawdust, hard hat crooked, still holding the phone, completely unbothered, and says, deadpan: \"Like I said. Day two.\"",
    "Day one. New deck. Solid. I'm telling you, this thing ain't going nowhere. Like I said. Day two.",
    "Day one on the new deck. He said it was solid."),
  selfie(2, "selfie-roof", "Twenty years", 10,
    "He stands on a low-pitched shingle roof of a single-storey house under a pale sky; behind him the roof slopes away to the gutter, with treetops and a neighbour's roof beyond.",
    "He talks fast and cocky straight into the lens: \"Guy says tie off. I been doin' this twenty years—\" Mid-word his feet go out from under him and he slides backward down the shingles and out of frame; the camera tumbles — a blur of sky, gutter, leaves — and lands in a big green hedge; then his head pops up out of the hedge into frame, leaves on his hard hat, still holding the phone, unhurt and deadpan, and he says: \"Twenty years. Never said good years.\"",
    "Guy says tie off. I been doing this twenty years. Twenty years. Never said good years.",
    "He's been doing this twenty years. (Tie off.)"),
  selfie(3, "selfie-leak", "It's a small leak", 9,
    "He stands in an ordinary small bathroom with white tiles; behind him a white tiled wall with a chrome tap and a faint damp stain on it.",
    "He talks fast and dry straight into the lens: \"Homeowner says it's a small leak—\" Mid-word the tiled wall behind him bursts open and a huge jet of water blasts across the room, hitting him in the back and soaking everything; the camera shakes and is splashed; he does not flinch, water pouring off his hard hat, and after a beat he says, completely deadpan: \"Small.\"",
    "Homeowner says it's a small leak. Small.",
    "The homeowner said it was a small leak."),

  /* ── Style 13: viral moment + gator button ───────────────────────────────── */
  moment({ id: "moment-ladders", title: "Lemme tell you somethin' about ladders", caption: "He had one more thing to say about ladders.", seconds: 10,
    castStill: "A photograph: on the flat roof edge of a two-storey building, a real rooster standing upright like a person, wearing a tiny yellow hard hat and a full-body safety harness whose rope runs taut up to a steel anchor frame behind him, both wings raised mid-gesture, beak open, talking to two real raccoons who stand upright on either side of him in matching orange hi-vis vests and yellow hard hats; one raccoon rests a paw on a large red lever on a winch stand. Rooftops and trees behind. Filmed by a coworker's phone from a few steps away. No people.",
    castAction: "ONE continuous handheld phone take, no cuts, photorealistic. The rooster in the harness stalls, talking fast and nervous, wings flapping: \"Wait, wait, wait — lemme tell you somethin'. Lemme tell you somethin' about ladders—\" The two raccoons look at each other, nod, and one pulls the red lever: the rooster drops smoothly backward off the roof edge on his rope and out of frame, safely held by the harness, yelling as he goes: \"—safety fiiirst!\" The raccoons lean over the edge to look, and one raises a thumbs-up. The rooster has the fast, nervous voice of a young man. Sound: his voice, the winch whirring, wind.",
    castScript: "Wait, wait, wait, let me tell you something. Let me tell you something about ladders. Safety first!",
    buttonScene: "He stands on the ground at the foot of a two-storey building beside an extension ladder, holding a paper coffee cup, looking up toward the roof; seen from a few steps away in three-quarter view.",
    buttonAction: "ONE continuous handheld phone take, photorealistic. The alligator watches something above, takes a slow sip of coffee, then turns his head to the lens and says, completely deadpan: \"Lemme tell YOU somethin'. Tie off.\"",
    buttonLine: "Let me tell you something. Tie off." }),
  moment({ id: "moment-video", title: "I watched a video", caption: "He watched a video. It's not load-bearing, he said.", seconds: 10,
    castStill: "A photograph: inside a half-renovated living room with one wall stripped to its bare timber studs, a real opossum standing upright like a person, wearing a bathrobe, grips one wall stud with both front paws and looks back over his shoulder with total confidence; beside him a real beaver standing upright in a yellow hard hat and an orange hi-vis vest holds up both front paws as if to say stop. Dust sheets on the floor, a work light. Filmed on a phone from the doorway. No people.",
    castAction: "ONE continuous handheld phone take, no cuts, photorealistic. The opossum in the bathrobe talks with total confidence while tugging at the stud: \"Lemme tell you somethin'. I watched a video. This one? Not load-bearing—\" He yanks the stud out: the whole stud wall folds over and falls flat with a huge crash and a cloud of dust, landing all around the two animals. As the dust thins, BOTH of them are still standing exactly where they were, completely untouched, framed by the gap where the doorway opening was — the opossum still in his bathrobe, still holding the loose stud in his paws, blinking in surprise; the beaver beside him slowly lowers his paws and sighs. The opossum stays clearly visible, standing and unhurt, until the end of the shot. The opossum has the smug voice of a middle-aged man. Sound: his voice, timber cracking, a crash, dust settling.",
    castScript: "Let me tell you something. I watched a video. This one? Not load-bearing.",
    buttonScene: "He stands in the doorway of a half-renovated room full of settling dust, holding a paper coffee cup; seen from a few steps away in three-quarter view.",
    buttonAction: "ONE continuous handheld phone take, photorealistic. Dust drifts past. The alligator takes a slow sip of coffee, looks at the lens and says, completely deadpan: \"Twenty years. Never heard the end of that sentence.\"",
    buttonLine: "Twenty years. Never heard the end of that sentence." }),

  /* ── Style 14: the fall (the instant-replay edit is made from this one shot — replay.ts) ── */
  oneshot({ id: "fall-bucket", style: 14, title: "He kicked the bucket", caption: "Somebody filled the bucket with concrete.", seconds: 10,
    scene: `Low, ground-level, static phone shot on a gravel jobsite path: close in the foreground stands a white 5-gallon plastic bucket filled to the brim with set grey concrete. Far in the background, small in the frame, he walks toward the camera along the path between stacks of lumber.`,
    action: `ONE static, low, ground-level phone shot, no cuts, photorealistic. For the first three seconds nothing moves but the alligator walking closer from the background, relaxed and confident. He reaches the bucket, winds up and kicks it hard like a football: the bucket does not move at all. His kicking leg stops dead, his other foot flies up, and he flips onto his back and lands flat in the gravel with a heavy thud and a puff of dust. He lies there a beat, then raises one arm in a thumbs-up. Sound: footsteps on gravel, a dull clunk, a thud.` }),
  oneshot({ id: "fall-wetfloor", style: 14, title: "Fresh coat", caption: "The floor had just been coated.", seconds: 10, cast: true,
    scene: `A photograph: static wide shot inside an empty room of a house under renovation — a freshly coated, glossy wet wooden floor shining like glass, a plain yellow plastic cone standing in the doorway in the foreground. In the far doorway at the back stands a real rooster, upright like a person, wearing a tiny yellow hard hat and an orange hi-vis vest, chest puffed out. No people.`,
    action: `ONE static wide phone shot, no cuts, photorealistic. The rooster in the hard hat struts confidently straight past the yellow cone onto the glossy wet floor. On his second step both feet shoot out from under him; he lands flat on his back with a slap and slides the whole length of the room on the wet floor, spinning slowly, and bumps gently to a stop against the far wall. A beat. He raises one wing in a thumbs-up. Sound: confident footsteps, a squeak, a slap, a long slide.` }),

  /* ── Style 15: tiny gator, giant opponent ────────────────────────────────── */
  oneshot({ id: "slap-arena", style: 15, title: "One slap", caption: "They let the little guy have a turn.", seconds: 10, cast: true,
    scene: `A photograph taken on a phone from ringside at an indoor slap-contest under bright arena lights: a pair of hands in grey work gloves gently holds up a small juvenile alligator, about the size of a cat, wearing a tiny yellow hard hat and a tiny orange hi-vis vest, its mouth closed; it faces an enormous, bald, bearded man — an invented person, not anyone real — who stands on the other side of a small table with his chin out and his hands behind his back, in plain black shorts with nothing written on them. A blurred crowd in the dark behind. The table, floor and banners are plain and blank.`,
    action: `ONE continuous handheld ringside phone take, no cuts, photorealistic. The gloved hands hold the little alligator steady. With its mouth shut the whole time, it winds one short front leg back and slaps the huge man across the cheek with a small open paw — a puff of white chalk dust. A beat: the huge man blinks, sways, and topples over backward like a felled tree, landing flat on the mat. The crowd erupts. The little alligator slowly turns its head and looks into the lens, deadpan. In the background the man sits up, dazed and smiling, and raises a thumbs-up. The alligator never bites, lunges or opens its jaws. Sound: crowd murmur, a small slap, a heavy thud, a roar.` }),
  oneshot({ id: "slap-jobsite", style: 15, title: "Union break's over", caption: "Lunch break. The big guy said go ahead.", seconds: 10, cast: true,
    scene: `A photograph taken on a coworker's phone during lunch break on a house-framing jobsite: a pair of hands in grey work gloves gently holds up a small juvenile alligator, about the size of a cat, wearing a tiny yellow hard hat and a tiny orange hi-vis vest, mouth closed; it faces an enormous, cartoonishly broad construction worker — an invented person, not anyone real — in a plain hard hat and plain t-shirt, grinning with his chin stuck out and his hands on his knees. Behind him a big soft pile of pink insulation batts and a stack of empty buckets. Flat daylight. No logos or writing on anything.`,
    action: `ONE continuous handheld phone take, no cuts, photorealistic. The gloved hands hold the little alligator up to the huge grinning worker. With its mouth shut the whole time, the little alligator winds one short front leg back and slaps him across the cheek with a small open paw — a puff of drywall dust. A beat: the big man's grin freezes, he sways, and he topples backward like a felled tree into the big soft pile of pink insulation, which swallows him with a soft whump. Offscreen coworkers burst out laughing. The man's arm comes up out of the insulation with a thumbs-up, and he is laughing too. The little alligator turns its head and looks into the lens, deadpan. The alligator never bites, lunges or opens its jaws. Sound: site ambience, a small slap, a soft whump, laughter.` }),

  /* ── The goat: OUR goat, generated once, cut to wherever a cliché deserves it (style 7) ── */
  oneshot({ id: "our-goat", style: 7, title: "The goat", caption: "The goat has seen the invoice.", seconds: 4, cast: true,
    scene: "A photograph: close-up of a real white-and-tan goat with a short beard standing in a muddy jobsite yard, wearing a small yellow hard hat held on by a chin strap, looking straight into the lens with its mouth closed. Behind it a wheelbarrow and a stack of cinder blocks.",
    action: "ONE continuous handheld phone take, photorealistic. The goat stares into the lens for half a second, then stretches its neck, opens its mouth wide and SCREAMS — one long, loud, hoarse yell that sounds almost like a person shouting — eyes wide, for two full seconds; then it stops abruptly and stares into the lens again, completely calm. Sound: the scream, loud and close." }),
  cutaway({ id: "goat-cousin", style: 7, title: "My cousin can do it cheaper", caption: "“My cousin can do it cheaper.”", seconds: 6,
    scene: "Doorbell-camera view — wide fisheye lens, high angle from beside a front door — of a suburban front porch in daylight: he stands on the doormat holding a clipboard, facing the door.",
    action: "Static doorbell-camera footage, photorealistic. The alligator stands at the door holding a clipboard. From the doorway, off-screen, a cheerful middle-aged woman's voice says: \"That's your price? My cousin can do it cheaper.\" The alligator does not move for a full second. Then, very slowly, he turns his head and looks straight into the doorbell camera, completely deadpan, and holds the look.",
    script: "That's your price? My cousin can do it cheaper." }),
  cutaway({ id: "goat-inch-short", style: 7, title: "Exactly where you said, boss", caption: "He cut it exactly where he was told.", seconds: 7,
    scene: "Inside a framed doorway opening on a jobsite: a real rooster standing upright like a person, in a tiny yellow hard hat and orange vest, proudly holds a cut wooden board up across the opening — the board is clearly a hand's width too short and does not reach the other side. He stands beside the rooster, looking at the gap.",
    action: "ONE continuous handheld phone take, photorealistic. The rooster holds the too-short board up proudly and says in a young man's eager voice: \"Cut it exactly where you said, boss!\" The alligator looks at the gap between the board and the frame, then at the rooster, then very slowly turns his head and looks straight into the lens, deadpan, and holds the look.",
    script: "Cut it exactly where you said, boss!" }),

  /* ── Style 2: the selfie vlog with the cartoon mascot ────────────────────── */
  mascotSelfie({ id: "mascot-shed", title: "Strapped it myself", caption: "He strapped the shed down himself.", seconds: 9,
    scene: "Selfie from the phone's point of view: one of his arms reaches out to the edge of the frame holding the phone, his head, his one hard hat and his shoulders fill the lower half of the frame, he looks into the lens mid-sentence; he wears exactly one hard hat and there is no second hat anywhere. Behind him, on a quiet street, drawn right down to the bottom edge of the picture, a small wooden garden shed sits on a flatbed trailer hitched to a generic unmarked orange pickup truck, held by one thin strap.",
    action: "He talks fast and cocky straight into the lens: \"This shed? Strapped it myself. It ain't goin' nowhere—\" Behind him the strap snaps and the shed slides off the back of the trailer and lands on the road with a huge crash and a cloud of dust. He does not turn around. A beat. He says, deadpan: \"I'll strap it again.\"",
    script: "This shed? Strapped it myself. It ain't going nowhere. I'll strap it again." }),
  mascotSelfie({ id: "mascot-pour", title: "Nobody touches it", caption: "Fresh pour. Nobody touches it.", seconds: 9,
    scene: "Selfie from the phone's point of view: one of his arms reaches out to the edge of the frame holding the phone, his head, hard hat and shoulders fill the lower half of the frame, he looks into the lens mid-sentence. Behind him a freshly poured, perfectly smooth concrete driveway slab in wooden forms, and at the top of the sloping drive an empty wheelbarrow.",
    action: "He talks fast and proud straight into the lens: \"Fresh pour. Perfect finish. Nobody touches it—\" Behind him the empty wheelbarrow starts rolling by itself, trundles right across the wet concrete leaving a deep wheel track from one side to the other, and tips over at the far edge with a clatter. He does not turn around. A beat. He says, deadpan: \"Fuhgeddaboudit.\"",
    script: "Fresh pour. Perfect finish. Nobody touches it. Forget about it." }),

  /* ── Style 3: the impossible skill ───────────────────────────────────────── */
  oneshot({ id: "skill-blower", style: 3, title: "Leaf blower", caption: "He found a new setting on the leaf blower.", seconds: 8,
    scene: "In a suburban back garden covered in autumn leaves he stands holding a large petrol leaf blower with both hands, its nozzle pointed straight down at the ground; seen from a few steps away, as if filmed by a neighbour over the fence.",
    action: "ONE continuous handheld phone take, photorealistic. He squeezes the trigger: the blower roars and he rises slowly off the ground, hovering about half a metre up, legs dangling, tail swaying, perfectly calm, drifting a little from side to side while leaves swirl beneath him. After a few seconds he eases off and settles gently back on the grass, and gives one small nod. Sound: a loud leaf blower rising and falling." }),
  oneshot({ id: "skill-tail", style: 3, title: "Tail finish", caption: "No trowel. He says he doesn't need one.", seconds: 8,
    scene: "He kneels on kneeboards at the edge of a freshly poured grey concrete slab on a house site, his long tail lying flat on the wet concrete behind him; seen from a few steps away by a coworker's phone.",
    action: "ONE continuous handheld phone take, photorealistic. He sweeps his tail across the wet concrete in one long, slow, smooth arc; behind the tail the rough surface turns into a flawless, glassy, mirror-smooth finish reflecting the sky. He sweeps once more the other way, perfect again, then looks over his shoulder at the lens. Sound: a soft wet scraping, site ambience." }),

  /* ── Style 4: the fail he walks away from ────────────────────────────────── */
  oneshot({ id: "fail-wheelbarrow", style: 4, title: "Wheelbarrow", caption: "He said the wheelbarrow was faster.", seconds: 8,
    scene: "On a house site he stands upright inside a steel wheelbarrow, in a surfer's stance with his arms out, at the top of a long wooden plank ramp that runs down from a mound of earth; at the bottom of the ramp is a big soft pile of yellow sand. Seen from the side by a coworker's phone.",
    action: "ONE continuous handheld phone take, photorealistic. The wheelbarrow rolls down the plank ramp, picking up speed, and he surfs it with his arms out, confident. At the bottom the wheel digs into the sand, the wheelbarrow stops dead and tips, and he is thrown forward head-first into the big soft sand pile with a soft thump, his legs and tail sticking out. A beat. One arm comes up out of the sand with a thumbs-up. Sound: a rattling wheel, a thump, a coworker laughing off-screen." }),
  oneshot({ id: "fail-dominoes", style: 4, title: "Dominoes", caption: "He spent all morning stacking those.", seconds: 8,
    scene: "On a concrete slab a long, perfectly neat row of grey cinder blocks stands on end, one behind another like dominoes, stretching away into the distance. He stands beside the nearest block with his back to the row, facing the lens proudly, chest out.",
    action: "ONE continuous handheld phone take, photorealistic. He stands proudly in front of his row of blocks. He shifts his weight: his tail swings and taps the first block. The whole row topples like dominoes, one after another, clattering away into the distance behind him. He hears it. He does not turn around. He slowly closes his mouth and looks into the lens, deadpan, while the last blocks fall. Sound: a long run of clacking concrete." }),

  /* ── Style 5: CCTV ───────────────────────────────────────────────────────── */
  oneshot({ id: "cctv-ladder", style: 5, title: "CAM 03", caption: "The yard camera caught this.", seconds: 8, overlay: "cctv",
    scene: "High-angle security-camera view, wide lens, looking down from the corner of a building at the side wall of a house in daylight: an aluminium extension ladder leans against the wall, and he stands on it about two metres up, carrying a bundle of roof shingles on one shoulder.",
    action: "Static security-camera footage, photorealistic, slightly washed-out colour. He climbs one more rung, calm. The foot of the ladder slides out: the ladder skids down the wall, and he rides it all the way down like a surfboard, knees bent, still holding the bundle of shingles, and lands on his feet on the ground as the ladder clatters flat beside him. He stands still for a moment, then slowly looks up, straight into the security camera. Sound: a scrape, a clatter, quiet." }),
  oneshot({ id: "cctv-shingles", style: 5, title: "CAM 03 — the delivery", caption: "The delivery came off the roof early.", seconds: 8, overlay: "cctv",
    scene: "High-angle security-camera view, wide lens, of a driveway in daylight: a generic unmarked orange pickup truck is parked directly below the edge of a low roof, where a pallet stacked with bundles of roof shingles sits right at the edge. He stands beside the truck holding a paper coffee cup.",
    action: "Static security-camera footage, photorealistic, slightly washed-out colour. The stack of shingle bundles at the roof edge slowly tips and slides off, and lands with a huge crash in the bed of his own pickup truck, which sags hard on its springs. He does not flinch. He takes one slow sip of coffee. Then he slowly looks up, straight into the security camera. Sound: a creak, a huge crash, quiet." }),

  /* ── Style 8: the coworker's phone ───────────────────────────────────────── */
  oneshot({ id: "pov-nailgun", style: 8, title: "New guy's first day", caption: "New guy's first day.", meme: "New guy's first day", seconds: 8, voice: "none", script: "Bro. Bro!",
    scene: "Phone footage from a few steps away on a house site, as if filmed by a coworker who is not in the picture: he kneels at one end of a long plywood subfloor panel, holding a framing nail gun in his own clawed hands, its tip against a blue chalk line that runs the full length of the panel. Nobody else is in the frame.",
    action: "ONE continuous handheld phone take filmed by a coworker, photorealistic. He pulls the trigger and runs the nail gun along the whole chalk line at absurd speed — a rapid machine-gun burst of pops — leaving a perfectly straight, perfectly evenly spaced row of nail heads from one end to the other in about two seconds. He stands up, blows across the tip of the nail gun, and walks out of frame. Off-screen, the man filming says in disbelief: \"Bro… BRO.\"" }),
  oneshot({ id: "pov-one-trip", style: 8, title: "One trip", caption: "He said he'd get it all in one trip.", meme: "One trip.", seconds: 8, voice: "none", script: "No way. No way!",
    scene: "Phone footage by a coworker on a house site: he walks toward the lens carrying an absurd load with total calm — a tall stack of plywood sheets balanced flat on his hard hat, a five-gallon bucket hanging from each forearm, a long bundle of timber under one arm, and a coil of extension lead looped over his tail.",
    action: "ONE continuous handheld phone take filmed by a coworker, photorealistic. He walks steadily past the camera carrying the whole impossible load, perfectly balanced, not even looking at it, and gives the lens a tiny nod as he passes. Nothing falls. Off-screen, the man filming says: \"No way. No WAY.\"" }),

  /* ── Style 9: satisfying ─────────────────────────────────────────────────── */
  oneshot({ id: "satis-chalk", style: 9, title: "Chalk lines", caption: "Three snaps. Three straight lines.", seconds: 8,
    scene: "He kneels on a clean plywood subfloor inside a framed house, holding a chalk line stretched tight across the floor with one hand and pinching the string up in the middle with the other; seen from a low angle a few steps away.",
    action: "ONE continuous steady phone take, photorealistic. He lifts the tight string and lets it snap: a puff of blue chalk dust and a perfectly straight blue line appears on the plywood. He moves the string a hand's width over and snaps again, then a third time, in an even rhythm — three perfectly parallel blue lines. Sound: three crisp snaps, quiet room." }),
  oneshot({ id: "satis-caulk", style: 9, title: "One bead", caption: "One bead. One pass.", seconds: 8,
    scene: "Close view of a new white window frame set in a wall; he holds a caulk gun with its nozzle at the top corner of the joint between the frame and the wall, his snout near the work, concentrating.",
    action: "ONE continuous steady close phone take, photorealistic. He draws the caulk gun slowly and smoothly down the whole length of the joint in a single unbroken motion, leaving a perfect, even, white bead of sealant. Then he runs one claw down the bead in a single pass, leaving it flawlessly smooth. Sound: a soft squeeze and a quiet room." }),

  /* ── Style 10: the hot take ──────────────────────────────────────────────── */
  hotTake({ id: "take-measure", title: "Measure once", stillFrom: "moment-ladders/s2", line: "Measure once. Cut twice. That's the trade.", prompt: "Measure once. Cut twice. That's the trade." }),
  hotTake({ id: "take-caulk", title: "Do your best", stillFrom: "moment-video/s2", line: "Do your best. Caulk the rest.", prompt: "Do your best. Caulk the rest." }),

  /* ── Style 12: the cast ──────────────────────────────────────────────────── */
  oneshot({ id: "cast-stretcher", style: 12, title: "The board stretcher", caption: "He sent the new guy for a board stretcher.", seconds: 9, voice: "none", subtitled: true, script: "Got it, boss! The board stretcher! Who sold you that?",
    scene: "On a house site he stands at a pair of sawhorses holding a paper coffee cup. In front of him a real rooster standing upright like a person, in a tiny yellow hard hat and orange vest, proudly presents a ridiculous home-made wooden contraption with ropes and a big hand crank, twice his own size.",
    action: "ONE continuous handheld phone take, photorealistic. The rooster proudly drags the wooden contraption up to the alligator and says in a young man's eager voice: \"Got it, boss! The board stretcher!\" The alligator looks at the contraption, then at the rooster, takes a slow sip of coffee, and says in a gravelly, dry, deadpan New Jersey voice: \"Who sold you that?\" The rooster beams." }),
  oneshot({ id: "cast-inspector", style: 12, title: "The inspector", caption: "The inspector looked in the panel.", seconds: 9, subtitled: true, script: "He does that. Means we passed.",
    scene: "In a garage on a jobsite, a real opossum standing upright like a person, wearing a tiny white hard hat and an orange vest and holding a small clipboard, peers into an open grey electrical panel on the wall, its door swung open; nothing is written on anything. He stands beside the opossum holding a paper coffee cup, watching.",
    action: "ONE continuous handheld phone take, photorealistic. The opossum inspector leans in and looks into the open electrical panel. It freezes, goes stiff, and topples straight over backward onto the floor, lying flat on its back with its legs in the air, playing dead. The alligator looks down at it, takes a slow sip of coffee, turns to the lens and says, completely deadpan: \"He does that. Means we passed.\" Behind him the opossum opens one eye." }),

  /* ── Selfie-vlog falls in the mould of "Twenty years" (the owner: "the one where the alligator falls off the roof is funny") ── */
  selfie(4, "selfie-scaffold", "I got balance", 10,
    "He stands on the plank deck of a two-level steel pipe scaffold against the side of a house, with his back to the open, unguarded edge; rooftops and trees behind him. On the ground below the scaffold is a big heap of yellow sand.",
    "He talks fast and cocky straight into the lens: \"Guy says put up the guardrail. I got balance. I got balance—\" Mid-word he steps back off the open edge of the scaffold and drops: the phone goes with him, the picture whips past pipes, sky and wall, and he lands with a heavy thump in the heap of sand in a burst of sand. A beat. The phone, still in his claw, comes back up on his sandy face against the sky, hard hat crooked, and he says, deadpan: \"I got a guardrail guy now.\"",
    "Guy says put up the guardrail. I got balance. I got balance. I got a guardrail guy now.", "He said he didn't need the guardrail."),
  selfie(5, "selfie-ladder", "It's a step", 10,
    "There is exactly ONE alligator in the picture: the one taking the selfie. He is filming himself from the very top of a tall stepladder, so the camera looks slightly down past his shoulders: the roof gutter of a house is right beside his head, the top cap and rails of the aluminium stepladder are visible under his chest, and the lawn and a thick green hedge along the house wall are far below him. Nobody and nothing else is on the ladder or on the roof.",
    "He talks fast and cocky straight into the lens: \"They say don't stand on the top step. It's a step. It's right there—\" Mid-word the ladder wobbles hard and kicks out sideways from under him: the phone goes with him, the picture spins past the gutter, the sky and the falling ladder, and he crashes down into the thick hedge with a loud rustle as the ladder clatters onto the lawn. A beat. His head pops up out of the hedge, leaves on his hard hat, and he says into the lens, deadpan: \"Okay. It's a shelf.\"",
    "They say don't stand on the top step. It's a step. It's right there. Okay. It's a shelf.", "He stood on the top step."),
  selfie(6, "selfie-attic", "Stay on the joists", 10,
    "He crouches in a dim house attic, balancing on the bare wooden ceiling joists with pink insulation between them, a work light behind him and the sloping roof rafters overhead.",
    "He talks fast and cocky straight into the lens while walking backwards along the joists: \"Attic's easy. You just stay on the joists. Stay on the—\" Mid-word his foot misses a joist and he drops straight through the ceiling: the phone goes with him through a burst of drywall and pink insulation, the picture whips past a bright living room, and he lands with a thump on a big soft sofa in a cloud of dust, insulation floating down around him, a ragged hole in the ceiling above. A beat. He looks into the lens, dusty, and says, deadpan: \"Found the living room.\"",
    "Attic's easy. You just stay on the joists. Stay on the. Found the living room.", "He said the attic was easy."),

  /* ── Accident v2: the camera was filming something else ───────────────────── */
  accident({ id: "acc-deck-ladder", title: "Check out this deck", caption: "He was filming the new deck.", seconds: 10, voice: "none", script: "Check out this deck, boys. Oh! Oh! You good?",
    scene: "Phone video of a brand-new wooden backyard deck in daylight, filmed from the lawn at an angle so the fresh boards and the railing fill most of the frame. Far in the background, small and off-centre at the right edge, he is high up an aluminium extension ladder leaning against the house wall, his back to the camera, busy carrying a bundle of roof shingles on one shoulder.",
    action: "ONE continuous handheld phone take, photorealistic. The person filming, never seen, pans slowly along the new deck boards and says proudly: \"Check out this deck, boys—\" In the background, small and at the edge of the frame, the alligator is climbing the extension ladder with the shingles, paying no attention to the camera. Suddenly the foot of the ladder kicks out on the patio: the ladder scrapes down the wall very fast and he drops with it, hitting the ground hard out of sight behind the deck railing with a loud metallic crash; shingles scatter and dust rises. The filmer gasps \"Oh— OH!\" and the camera whips round late toward the noise, shaking and overshooting. A second later a paint bucket rolls off the patio and clatters over. A dog starts barking somewhere. The filmer calls: \"…You good?\" From behind the deck railing one scaly arm rises with a thumbs-up." }),
  accident({ id: "acc-scaffold-doorbell", title: "Front door camera", caption: "The doorbell camera got all of it.", seconds: 10, voice: "none",
    scene: "Doorbell-camera view: a very wide fisheye lens, high beside a front door, looking out over a front porch, the steps and the front yard in daylight. Most of the picture is the empty porch, the steps, the lawn and the street. He is SMALL and far from the camera — no more than a quarter of the height of the frame — at the far left edge of the picture and partly cut off by it, out on the lawn: standing on a wooden scaffold plank laid between two tall wooden trestles, side-on to the camera, reaching up to paint the eave of the porch roof with a brush, a paint bucket beside his feet on the plank. He does not look at the camera.",
    action: "Static doorbell-camera footage, photorealistic, wide fisheye. At the left edge of the frame the alligator paints the trim, busy, turned away, never looking at the camera. Without any warning the plank under him snaps in the middle with a sharp crack: he drops straight down instantly with the two halves of the plank and the paint bucket, landing hard on the lawn mostly out of frame; white paint splashes up across the porch steps; a brush spins across the porch floor. A beat later one of the trestles tips over slowly and crashes down. A dog barks inside the house. Paint keeps dripping off the step. Then, from the bottom-left corner of the frame, one scaly arm rises with a thumbs-up, and holds." }),
  accident({ id: "acc-wheelbarrow-drive", title: "The new walkway", caption: "She was filming the new walkway.", seconds: 10, voice: "none", script: "So here's the new walkway. Oh no. Oh no!",
    scene: "Phone video of a freshly laid stone front walkway and new front steps of a suburban house in daylight, filmed looking down at the stones at an angle. In the upper background, out of the centre, a steep concrete driveway rises beside the lawn; at the top of it, small in the frame, he is pushing a steel wheelbarrow heaped with wet grey concrete, side-on to the camera, busy.",
    action: "ONE continuous handheld phone take, photorealistic. The person filming, never seen, walks slowly along the new stone walkway looking down at it and says in a pleased woman's voice: \"So here's the new walkway—\" In the background the alligator is wheeling the heavy wheelbarrow of wet concrete across the top of the steep driveway, not looking at the camera. The wheelbarrow gets away from him: it lurches downhill, pulling out of his claws, and races down the driveway by itself, fast, bouncing; he runs after it flat out. It hits the kerb at the bottom with a bang and flips, throwing a wide wave of wet concrete across the grass, and he trips over the handles at full speed and belly-flops into the wet concrete with a heavy slap. The filmer says \"Oh no. Oh NO.\" and the camera swings up late and shakes. The wheel keeps spinning. He lifts his head, covered in grey concrete, hard hat still on, and raises one thumb." }),
  selfie(7, "acc-ceiling-selfie", "Smooth as glass", 10,
    "He stands in a half-renovated kitchen under a freshly plastered, freshly painted white ceiling; behind him an aluminium stepladder, a work light and a bucket of joint compound on a dust sheet.",
    "He talks fast and proud straight into the lens: \"New ceiling. Mudded it myself. Smooth as glass. That ain't goin' nowhere—\" Mid-word, without warning, a big section of the ceiling behind him lets go and crashes down in one heavy slab — drywall, dust and pink insulation exploding across the kitchen, the stepladder knocked flying, the work light swinging. He flinches hard, the phone jerks and shakes, dust rolls over him. Bits keep falling. He does not turn around. A beat. Covered in white dust, he says into the lens, deadpan: \"Smooth as glass.\"",
    "New ceiling. Mudded it myself. Smooth as glass. That ain't going nowhere. Smooth as glass.", "He mudded the ceiling himself."),

  /* ── Five-second fails of the cast, for "Gator Reacts" ───────────────────── */
  quickFail({ id: "fx-raccoon-plank", title: "The plank", caption: "The plank was fine yesterday.",
    scene: "A real raccoon standing upright like a person, in a tiny yellow hard hat and orange hi-vis vest, walks along a long wooden plank laid between two sawhorses over a muddy trench on a jobsite, carrying a long piece of lumber on its shoulder, seen from the side from a few steps away, off-centre in the frame.",
    action: "The raccoon walks briskly along the plank, busy, not looking at the camera. Halfway across, the plank snaps in the middle with a loud crack and the raccoon drops straight down into the muddy trench with a splat, the lumber clattering after it; mud splashes up. The camera jerks. The raccoon's head pops up over the edge of the trench, muddy, hard hat still on." }),
  quickFail({ id: "fx-rooster-washer", title: "The pressure washer", caption: "First time on the pressure washer.",
    scene: "A real rooster standing upright like a person, in a tiny yellow hard hat and orange hi-vis vest, holds the long lance of a pressure washer with both wings on a wet concrete driveway beside a house, a hose trailing behind him to the machine; seen from the side, slightly off-centre.",
    action: "The rooster squeezes the trigger. The lance kicks back violently and a hard jet of water blasts out; the recoil spins the rooster round and drags him skidding backwards across the wet driveway at speed, spraying water in a wild arc over the garage door and the camera, until he sits down hard in a puddle and lets go. The lance clatters. Water drips off the lens. The rooster shakes himself, unharmed." }),
  quickFail({ id: "fx-beaver-cut", title: "The wrong side of the cut", caption: "He was standing on the off-cut.",
    scene: "A real beaver standing upright like a person, in a tiny yellow hard hat and orange hi-vis vest, stands on the overhanging end of a long plank that sticks out past the edge of a low wooden deck frame on a jobsite, holding a handsaw to the plank between himself and the frame; a big pile of sawdust and wood shavings lies on the ground below him. Seen from the side.",
    action: "The beaver saws quickly through the plank he is standing on, concentrating, not looking at the camera. The cut goes through: the end of the plank he stands on drops instantly and he falls straight down with it into the big pile of sawdust with a thump, sawdust bursting into the air. The saw lands beside him. The camera shakes with a laugh. The beaver sits up in the sawdust, unharmed, and looks at the cut end above him." }),
  quickFail({ id: "fx-possum-paint", title: "The paint tray", caption: "He left the tray on top of the ladder.",
    scene: "A real opossum standing upright like a person, in a tiny white hard hat and orange hi-vis vest, stands at the foot of a wooden stepladder in an empty room with drop cloths on the floor; on the very top of the stepladder sits a paint tray full of white paint. The opossum has both paws on the ladder, about to move it. Seen from across the room, off-centre.",
    action: "The opossum grabs the stepladder and drags it briskly sideways across the room, busy, not looking up or at the camera. The paint tray slides off the top and lands upside down squarely on the opossum's hard hat with a slap, white paint pouring down over its head and shoulders and splattering the drop cloth. The opossum freezes, standing, dripping. The camera jerks with a stifled laugh. The tray slowly slides off and clatters on the floor." }),
  quickFail({ id: "fx-goat-drywall", title: "Sideways", caption: "It fits if you turn it. He did not turn it.",
    scene: "A real white-and-tan goat with a small yellow hard hat on its head walks toward an open interior doorway in a house under construction, carrying a full sheet of drywall balanced flat across its back, the sheet far wider than the doorway; seen from behind and to the side, down a hallway.",
    action: "The goat trots briskly straight at the doorway without slowing. The wide drywall sheet slams into both sides of the door frame with a loud bang and snaps clean in half, the two halves dropping to the floor in a puff of white dust, while the goat walks straight on through the doorway without stopping or looking back. The camera shakes. Dust hangs in the air." }),
  quickFail({ id: "fx-raccoon-buckets", title: "The stack", caption: "They stacked them one higher.",
    scene: "Two real raccoons standing upright like people, in tiny yellow hard hats and orange hi-vis vests, on a concrete garage floor on a jobsite: one stands on tiptoe placing one more white five-gallon bucket on top of a very tall, leaning tower of stacked white buckets, the other steadies the bottom. Seen from a few steps away, the tower partly cut off by the top of the frame.",
    action: "The raccoon on tiptoe lets go of the top bucket. The whole leaning tower sways and comes down fast in a loud hollow avalanche of plastic buckets that buries both raccoons and bounces across the floor toward the camera, one bucket hitting the lens with a thud. The camera jolts back. The buckets settle. Two raccoon heads pop up out of the pile, each wearing a bucket-shaped dent of dust, unharmed." }),

  /* ── "Gator Reacts": the reaction pack (the owner: "the reactions have to be annoyed or shocked" — "or no reaction is also a reaction") ── */
  // SHOCKED — for the impact. Each peaks within the first second.
  reaction("shocked-01-jaw-drop", "Jaw drop", "Within the first half second he sees a sudden disaster: his jaw drops wide open in shock and his head jerks sharply back, shoulders jumping; he holds the stunned, open-mouthed pose — shocked, not smiling.", "one sharp gasp."),
  reaction("shocked-02-spit-take", "Spit-take", "He is taking a sip of coffee when he sees a sudden disaster: at once he sprays the coffee out of his mouth in a wide spit-take, lurching forward, coffee mist hanging in the air, then stares, mouth open in shock.", "a sip, a loud spluttering spray, a cough."),
  reaction("shocked-03-recoil", "OHH!", "Within the first half second he sees a sudden hard impact: he flinches and recoils with his whole body, jerking back half a step, his free claw flying up in front of his chest, mouth wide open in alarm, and lets out one loud \"OHHH!\" — alarmed, not amused.", "one loud alarmed \"OHHH!\" in a gravelly man's voice."),
  reaction("shocked-04-double-take", "Double-take", "He glances away, bored — then snaps his head back toward what he is watching in a fast, sharp double-take and freezes, leaning forward, jaw hanging open in disbelief.", "a sharp \"huh?!\" grunt."),
  reaction("shocked-05-hard-hat", "Grabs his hard hat", "Within the first half second he sees a sudden disaster: he jolts so hard that his yellow hard hat pops up off his head, and he slaps his free claw down on top of it to hold it on, mouth open in shock, staring.", "a startled grunt and a slap on plastic."),
  reaction("shocked-06-drops-coffee", "Drops his coffee", "Within the first half second he sees a sudden disaster: he freezes, staring, mouth falling open, and the paper coffee cup slips out of his claw and drops to the ground, splashing — he does not look at it at all, still staring.", "a small gasp, then a cup hitting the ground with a splash."),
  reaction("shocked-07-frozen-sip", "Frozen mid-sip", "He lifts the coffee cup to drink — and freezes solid with the cup stopped at his mouth, completely motionless, staring at what he is watching, stunned.", "sudden silence."),
  reaction("shocked-08-lean-in", "Leans in", "He slowly leans far in toward the lens and toward what he is watching, head pushed forward, mouth hanging open in total disbelief, and holds it.", "a slow, quiet \"what…\" in a gravelly man's voice."),
  // ANNOYED — for the aftermath and the verdict.
  reaction("annoyed-09-head-shake", "Head shake", "Annoyed, jaw clamped shut, he slowly shakes his head from side to side three times, then looks down at the ground.", "a low disapproving grunt."),
  reaction("annoyed-10-facepalm", "Facepalm", "Annoyed, he lifts his free claw and plants it flat over his snout and sunglasses in a facepalm; his shoulders drop and his head sinks, and he holds it there.", "a long tired sigh."),
  reaction("annoyed-11-exhale", "Long exhale", "Annoyed, mouth shut, he tilts his head slowly all the way back to look up at the sky and lets out one long, slow breath through his nose, shoulders sinking.", "one long exhale through the nose."),
  reaction("annoyed-12-tapping", "Waiting", "Annoyed, mouth shut, he plants his free claw on his hip and taps one foot on the ground impatiently, his tail flicking sharply from side to side behind him, staring at what he is watching.", "a foot tapping on gravel."),
  reaction("annoyed-13-pinch", "Pinches his snout", "Annoyed, he pinches the top of his snout just under his sunglasses with two claws of his free hand, head bowed, like a man with a headache, and holds it.", "a quiet groan."),
  reaction("annoyed-14-cmon", "C'mon", "Annoyed, he points his free claw sharply at what he is watching, then throws the claw up in the air in exasperation and lets it drop, muttering \"C'mon.\"", "a muttered \"C'mon.\" in a gravelly New Jersey man's voice."),
  reaction("annoyed-15-watch", "Checks his watch", "Annoyed, mouth shut, he slowly raises his free wrist, looks at it as if checking a watch, lowers it, and shakes his head once.", "a short flat grunt."),
  reaction("annoyed-16-slow-turn", "The look", "Mouth shut, face completely flat, he turns his head very slowly from what he is watching to stare straight into the lens, and holds the flat stare, motionless, one beat too long.", "silence."),
  // NO REACTION — for the biggest, loudest fails (the contrast is the joke). 18 and 19 are cut from shots that exist.
  reaction("deadpan-17-still", "Nothing", "He does not react at all: completely still, mouth shut, staring flatly straight into the lens while a loud crash is heard off-camera; only the tip of his tail flicks once.", "a loud crash and clatter somewhere off-camera, then silence."),
  reaction("deadpan-20-glance", "A glance", "Mouth shut, face flat, he glances briefly off to the side at a loud mess, then looks back into the lens — and does nothing at all; no expression, no movement.", "a loud crash off-camera, then silence."),
  reaction("deadpan-21-clipboard", "Still writing", "He does not react at all: he looks down at his coffee cup, calmly swirls it and takes one unhurried sip, never once looking up, while a loud crash is heard off-camera.", "a loud crash and clatter somewhere off-camera; a calm sip."),
  reaction("deadpan-22-nod", "Called it", "Mouth shut, face flat, he looks at what he is watching and gives one single slow nod, as if he had predicted exactly this, then is still.", "a loud crash off-camera, then a quiet \"mm-hm.\""),

  /* ── THE VIEWER PACK (owner, 2026-10-08): a reaction is ONLY the gator as a viewer — upright, facing the lens, in the one
     setting of the owner-approved doorbell/clipboard shot (`_reactions/REFERENCE-doorbell-clipboard.png`, the first frame of
     reaction-deadpan-55-doorbell-stare), nothing happening TO him. Animated straight from that still, so they intercut.
     Shopping list and costs: docs/gator/REACTIONS-SHOPPING-LIST.md. NOT generated yet (no credit). ───────────────── */
  viewer("shocked-60-jaw-drop", "Jaw drop", "Within the first half second he sees something go badly wrong: his head jerks BACK, his jaw drops open in alarm (an O of shock — no teeth-baring, no smile) and he freezes like that, staring.", "a sharp intake of breath."),
  viewer("shocked-61-spit-take", "Spit-take", "He raises a paper coffee cup from below the frame in his free claw and sips — then sees it and sprays the coffee out in a burst, recoiling, and stares, coffee dripping from his snout.", "a sip, then a spluttering spray."),
  viewer("shocked-62-flinch", "Flinch", "He flinches hard at a sudden crash: his whole body jolts, shoulders up, the clipboard jerks up against his chest, and he stays tensed, staring, mouth open in shock (never a smile).", "a loud bang off-camera and a short gasp \"oh!\" with no other words."),
  viewer("shocked-63-double-take", "Double take", "He glances at it, looks away calmly, then whips his head back to stare at it again, frozen, snout pushed forward.", "silence, then a short startled grunt."),
  viewer("shocked-64-hard-hat", "Grabs his hard hat", "He jolts in shock and slaps his free claw down on top of his yellow hard hat with both hands as if to hold his head together, mouth falling open, staring.", "a slap on plastic and a gasp."),
  viewer("shocked-65-frozen-sip", "Frozen mid-sip", "He lifts a paper coffee cup from below the frame to his mouth — and freezes solid with the cup at his mouth, completely motionless, staring.", "sudden silence."),
  viewer("shocked-66-lean-in", "Leans in", "He slowly leans far in toward the lens, snout pushed forward, mouth hanging slightly open in total disbelief, and holds it — not smiling.", "silence."),
  viewer("shocked-67-drops-clipboard", "Drops the clipboard", "Within the first half second he goes rigid with shock and the clipboard slips out of his claw and falls out of frame; he does not look down, still staring, mouth open in shock.", "a clipboard clattering on a porch floor."),
  viewer("annoyed-70-facepalm", "Facepalm", "Annoyed, he lifts his free claw and plants it flat over his snout and sunglasses; his shoulders drop and his head sinks, and he holds it there.", "a long tired sigh."),
  viewer("annoyed-71-exhale", "Long exhale", "Annoyed, mouth shut, he tilts his head slowly back to look up at the sky and lets out one long slow breath through his nose, shoulders sinking.", "one long exhale through the nose.", 4),
  viewer("annoyed-72-arms-crossed", "Arms crossed, tapping", "Annoyed, mouth shut, he folds his arms across his chest with the clipboard held against it and taps one claw on his arm, staring flatly.", "slow claw taps on plastic."),
  viewer("annoyed-73-pinch", "Pinches his snout", "Annoyed, he pinches the bridge of his snout just under his sunglasses with two claws, head bowed, like a man with a headache, and holds it.", "a quiet groan."),
  viewer("annoyed-74-claw-up", "Throws a claw up", "Annoyed, mouth shut, he throws his free claw up in the air in exasperation and lets it drop against his side.", "a clap of a claw against the vest."),
  viewer("annoyed-75-write-up", "Writes him up", "Mouth shut, face flat, he looks down at the clipboard and writes one short line on it with a pen in his free claw, firmly, then looks back up at the lens.", "a pen scratching on paper."),
  viewer("annoyed-76-clipboard-face", "Can't watch", "Annoyed, he slowly raises the clipboard in front of his face to block the view, and holds it there.", "a quiet groan."),
  viewer("deadpan-80-flat-stare", "Flat stare", "He does not react at all: completely still, mouth shut, staring flatly into the lens while a loud crash is heard; only the tip of his tail flicks once.", "a loud crash off-camera, then silence."),
  viewer("deadpan-81-slow-nod", "Called it", "Mouth shut, face flat, he gives one single slow nod, as if he had predicted exactly this, then is still.", "a loud crash off-camera, then silence."),
  viewer("deadpan-82-sandwich", "Keeps eating", "He raises a sandwich from below the frame in his free claw and keeps chewing a bite slowly, completely unbothered, staring flatly into the lens while a loud crash is heard.", "a loud crash off-camera; slow chewing.", 4),

  /* ── "Gator Reacts": the host lines ──────────────────────────────────────── */
  hostLine("open", "Alright. Site walk. Let's see who's getting written up today.", 5),
  hostLine("write-up", "That's a write-up."),
  hostLine("signed-off", "Who signed off on that?"),
  hostLine("twenty-years", "Twenty years. Never seen it done that wrong.", 4),
  hostLine("operator", "Ladder's fine. Operator's defective.", 4),
  hostLine("check", "That's coming out of somebody's check.", 4),
  hostLine("meeting", "And that's why we have the safety meeting.", 4),
  hostLine("new-guy", "Send that to the new guy."),
  hostLine("gravity", "Gravity. Still undefeated."),
  hostLine("seen-worse", "I've seen worse. Not today. But I've seen worse.", 5),
  hostLine("lunch", "And it's not even lunch."),
  hostLine("sign-off", "ConstructHUB. Run the whole job. And tie off.", 5),
];
