/**
 * "Gator Reacts" — the episode edit: fail clips with the gator cropped in, reacting at the impact, and
 * full-screen host lines between them.
 *
 * RUN
 *   npx tsx --env-file=.env.gator scripts/gator/reacts.ts docs/gator/reacts/<id>.json [--out file.mp4]
 *   npx tsx --env-file=.env.gator scripts/gator/reacts.ts docs/gator/reacts/<id>.json --owner-accepted-risk   (third-party clips; see below)
 * Writes analysis/gator-shorts/_reacts/reacts-<id>.mp4 (+ -review.jpg contact sheet, + .json sidecar) unless --out.
 *
 * THE EPISODE (docs/gator/reacts/<id>.json) — every path is relative to analysis/gator-shorts/:
 *   {
 *     "id": "ep01",
 *     "music": "sneaking-around",                              // a CC0 bed from scripts/gator/music.ts
 *     "open": "host-open",                                     // a host line: an id (its pure.mp4 / clip.mp4 / only raw take)
 *     "verdict": { "after": 2, "line": { "id": "host-write-up", "in": 0.2, "out": 2.9, "caption": "That's a write-up." } },
 *     "signOff": "host-sign-off",                              // optional
 *     "ownerAcceptedRisk": { "by": "…", "date": "2026-10-08", "quote": "…" },   // only for third-party clips
 *     "clips": [
 *       { "file": "fx-raccoon-plank/videos/s1-still1-take1.mp4",
 *         "impact": 2.6,                                       // seconds in the SOURCE file
 *         "in": 0.4, "out": 4.4,                               // optional: the range used (else impact − 2.0 … impact + 1.6;
 *                                                              //   the old relative "pre"/"post" fields still work)
 *         "crop": { "x": 656, "y": 0, "w": 608, "h": 1080 },   // optional, source pixels: cropped to this box, then a ~9:16
 *                                                              //   box fills 1080×1920, anything wider is fitted over a blur
 *         "panel": "bl",                                       // where the gator sits: bl (default), br, tl, tr
 *         "reaction": "react-shocked-01-jaw-drop",             // an id, or a file, e.g. "_deliver/reaction-shocked-01-jaw-drop.mp4"
 *         "peak": 1.9,                                         // optional: seconds into the reaction it peaks (else PEAK_AT / 0.7)
 *         "rights": { "kind": "own-ai", "record": "generated by us, Higgsfield …" } }
 *     ]
 *   }
 * A host line is either a plain id or { "id", "in", "out", "caption" } (trimmed to in…out; the caption replaces
 * the line's social.json script). The reaction's PEAK lands on the clip's IMPACT; no reaction is used twice.
 *
 * THE RIGHTS RULE — in the tool, not in a habit: every clip carries a rights record:
 *   own-ai       generated by us (the animal cast; AI-labelled)
 *   owner        filmed by the owner or his crews, with their say-so
 *   licensed     bought or licensed for commercial social use — `licensor` and `licence` (the reference) required
 *   cc-by        published under Creative Commons Attribution — `url` and `attribution` required (and credited)
 *   third-party  somebody else's video, NOT licensed — `source` (the https YouTube address) and `channel` required.
 *                Refused unless BOTH the run has --owner-accepted-risk AND the episode carries
 *                "ownerAcceptedRisk": { "by", "date" (YYYY-MM-DD), "quote" } — the owner's own words accepting the
 *                copyright / takedown / account-strike risk. Never a default. Such a run prints a warning, and
 *                the sidecar records every clip's source and channel plus a credits list "clips: <channel> (YouTube)".
 * A clip with no record, an unknown kind, or a record that admits it is unlicensed under another kind is refused.
 * See docs/gator/CLIP-LICENSING.md for how to get footage properly.
 *
 * WATERMARKS — by decision, this tool has NO watermark-removal step and never gets one: it does not remove, blur,
 * crop out or cover a creator's watermark or handle. The only lever is `panel`, which moves the gator AWAY from a
 * watermark; a `crop` must not be chosen to cut one off. A record that says it was de-watermarked is refused.
 *
 * THE EDIT: vertical 1080×1920; each clip at real speed; the gator panel (head-and-shoulders, 460×560) sits in
 * its corner for the whole clip, clear of the bottom 250 px the platforms draw over; full-screen host lines with
 * a caption; a 0.8 s logo-only end tag (never the cartoon mascot: this is a live-gator video); a CC0 music bed
 * low under the clips' own sound; −14 LUFS.
 */
import fs from "fs";
import path from "path";
import { ROOT, parseArgs, run } from "../tutorials/lib";
import { renderStill } from "../tutorials/brand";
import { LOUDNESS, measureLoudness } from "../tutorials/mux";
import { endTagHtml } from "./brand";
import { FPS, H, W, assFile, layoutBeat } from "./layout";
import { OUT } from "./make";
import { track } from "./music";

export type Rights =
  | { kind: "own-ai"; record: string }
  | { kind: "owner"; record: string }
  | { kind: "licensed"; record: string; licensor: string; licence: string }
  | { kind: "cc-by"; record: string; url: string; attribution: string }
  | { kind: "third-party"; record: string; source: string; channel: string };
export type Crop = { x: number; y: number; w: number; h: number };
export type Corner = "bl" | "br" | "tl" | "tr";
export type ReactClip = {
  file: string; /** Seconds in the source file. */ impact: number; reaction: string;
  /** The source range used (absolute seconds); without them, `pre` / `post` seconds around the impact (defaults 2.0 / 1.6). */
  in?: number; out?: number; pre?: number; post?: number;
  crop?: Crop; panel?: Corner; /** Seconds into the reaction at which it peaks (overrides PEAK_AT). */ peak?: number; rights?: Rights;
};
export type HostLine = string | { id: string; in?: number; out?: number; caption?: string };
export type RiskRecord = { by: string; date: string; quote: string };
export type Episode = { id: string; open?: HostLine; clips: ReactClip[]; verdict?: { after: number; line: HostLine }; signOff?: HostLine; music?: string; ownerAcceptedRisk?: RiskRecord };
/** The run's consent to third-party clips: the CLI flag and the episode's record — both are needed. */
export type Consent = { flag?: boolean; record?: unknown };
export const PRE = 2.0, POST = 1.6, TAG_SEC = 0.8;
/** The gator panel (inside a white border). Its corners keep it clear of the bottom 250 px and the top tabs. */
export const PANEL = { w: 460, h: 560, border: 6 };
const PW = PANEL.w + 2 * PANEL.border, PH = PANEL.h + 2 * PANEL.border;
export const PANEL_AT: Record<Corner, { x: number; y: number }> = { bl: { x: 36, y: H - 250 - PH - 8 }, br: { x: W - 36 - PW, y: H - 250 - PH - 8 }, tl: { x: 36, y: 230 }, tr: { x: W - 36 - PW, y: 230 } };
/** The head-and-shoulders crop of a reaction shot (hat to vest), as fractions of its 9:16 frame — the coffee-by-the-ladder framing (checked by eye 2026-10-08). */
export const REACTION_CROP = { cx: 0.5, cy: 0.31, w: 0.6 };
/** When a reaction peaks, seconds from its start (default 0.7). The takes open with ~1.5 s of calm: the listed ones were measured by eye. */
export const PEAK_AT: Record<string, number> = { "react-shocked-01-jaw-drop": 1.9, "react-annoyed-09-head-shake": 2.0, "react-deadpan-17-still": 1.5, "react-shocked-02-spit-take": 1.2, "react-shocked-04-double-take": 1.3, "react-shocked-07-frozen-sip": 1.2, "react-shocked-08-lean-in": 1.5, "react-annoyed-10-facepalm": 1.4, "react-annoyed-11-exhale": 1.5, "react-annoyed-16-slow-turn": 1.8 };
/** The peak of a reaction given as an id or as a file under it (`<id>/videos/…`). */
export const peakOf = (reaction: string) => PEAK_AT[reaction] ?? PEAK_AT[reaction.split("/")[0]] ?? 0.7;
export const hostOf = (h: HostLine) => (typeof h === "string" ? { id: h } : h);

const str = (o: Record<string, unknown> | undefined, k: string) => typeof o?.[k] === "string" && (o[k] as string).trim().length >= 3;
/** Whether the episode's ownerAcceptedRisk record is complete: who, when (YYYY-MM-DD), and his words. */
export const riskRecordOk = (r: unknown) => { const o = r as Record<string, unknown> | undefined; return !!o && typeof o === "object" && str(o, "by") && str(o, "quote") && /^\d{4}-\d{2}-\d{2}$/.test(String(o.date ?? "")); };

/** Why a clip may not be used — or null. Third-party clips need the consent (flag AND record); nothing else lifts a refusal. */
export function rightsRefusal(c: { file: string; rights?: unknown }, consent: Consent = {}): string | null {
  const r = c.rights as Record<string, unknown> | undefined;
  if (!r || typeof r !== "object") return `${c.file}: no rights record — a clip is never used without one`;
  if (!str(r, "record")) return `${c.file}: the rights record says nothing`;
  if (/de-?watermark|watermark (removed|blurred|cropped)|logo removed/i.test(String(r.record))) return `${c.file}: footage with a creator’s watermark removed is not used (this tool keeps watermarks)`;
  if (r.kind === "third-party") {
    if (!consent.flag) return `${c.file}: somebody else's video without a licence is not used — unless the owner accepts the risk: run with --owner-accepted-risk AND put "ownerAcceptedRisk": { by, date, quote } in the episode`;
    if (!riskRecordOk(consent.record)) return `${c.file}: --owner-accepted-risk was given but the episode has no complete "ownerAcceptedRisk": { by, date (YYYY-MM-DD), quote } — both are needed`;
    if (!/^https:\/\/(www\.|m\.)?(youtube\.com|youtu\.be)\//.test(String(r.source ?? ""))) return `${c.file}: a third-party clip needs its source — the https YouTube address it came from`;
    return str(r, "channel") ? null : `${c.file}: a third-party clip needs the channel it came from (credited)`;
  }
  if (/third.?party|unlicen[cs]ed|scraped|found online/i.test(`${r.kind} ${r.record}`)) return `${c.file}: somebody else's video without a licence is not used under kind “${String(r.kind)}” — label it third-party (license it, ask its creator, or use our own — docs/gator/CLIP-LICENSING.md)`;
  if (r.kind === "own-ai" || r.kind === "owner") return null;
  if (r.kind === "licensed") return str(r, "licensor") && str(r, "licence") ? null : `${c.file}: a licensed clip needs its licensor and the licence reference`;
  if (r.kind === "cc-by") return str(r, "attribution") && /^https:\/\//.test(String(r.url ?? "")) ? null : `${c.file}: a CC-BY clip needs its address and the attribution to print`;
  return `${c.file}: “${String(r.kind)}” is not a kind of rights this tool knows (own-ai, owner, licensed, cc-by, third-party)`;
}
/** The credits to print with the post: CC-BY attributions, and "clips: <channel> (YouTube)" per third-party channel. */
export function creditsOf(ep: Episode): string[] {
  const out = ep.clips.flatMap((c) => (c.rights?.kind === "cc-by" ? [c.rights.attribution] : c.rights?.kind === "third-party" ? [`clips: ${c.rights.channel} (YouTube)`] : []));
  return [...new Set(out)];
}
export type Segment =
  | { kind: "host"; line: string; start: number; sec: number; from: number; caption?: string }
  | { kind: "clip"; clip: ReactClip; start: number; sec: number; from: number; /** Seconds into the segment at which the reaction starts playing (negative: the reaction is already under way). */ reactionAt: number; impactAt: number; peak: number }
  | { kind: "tag"; start: number; sec: number };
/**
 * The timeline. `durations`: seconds of every file used (clips by `file`, host lines by id, reactions are not needed).
 * No reaction is used twice in an episode. Pure (tested).
 */
export function plan(ep: Episode, durations: Readonly<Record<string, number>>, consent: Consent = {}): { segments: Segment[]; totalSec: number } {
  if (!ep.clips.length) throw new Error(`${ep.id}: an episode needs clips`);
  for (const c of ep.clips) { const no = rightsRefusal(c, { flag: consent.flag, record: consent.record ?? ep.ownerAcceptedRisk }); if (no) throw new Error(no); }
  const used = ep.clips.map((c) => c.reaction), twice = used.find((r, i) => used.indexOf(r) !== i);
  if (twice) throw new Error(`${ep.id}: the reaction ${twice} is used twice — vary them`);
  const segments: Segment[] = []; let t = 0;
  const host = (line: HostLine) => {
    const h = hostOf(line), d = durations[h.id];
    if (!(d > 0)) throw new Error(`${ep.id}: no host line ${h.id}`);
    const from = Math.max(0, h.in ?? 0), to = Math.min(d, h.out ?? d), sec = Math.round((to - from) * FPS) / FPS;
    if (!(sec > 0)) throw new Error(`${ep.id}: host line ${h.id} — in/out (${h.in}…${h.out}) leave nothing of its ${d} s`);
    segments.push({ kind: "host", line: h.id, start: t, sec, from, ...(h.caption !== undefined ? { caption: h.caption } : {}) }); t += sec;
  };
  if (ep.open) host(ep.open);
  ep.clips.forEach((clip, i) => {
    const d = durations[clip.file];
    if (!(d > 0) || !(clip.impact >= 0 && clip.impact <= d)) throw new Error(`${ep.id}: ${clip.file} — the impact (${clip.impact}) is not inside the clip (${d} s)`);
    const from = Math.max(0, clip.in ?? clip.impact - (clip.pre ?? PRE)), to = Math.min(d, clip.out ?? clip.impact + (clip.post ?? POST));
    if (!(clip.impact >= from && clip.impact <= to)) throw new Error(`${ep.id}: ${clip.file} — the impact (${clip.impact}) is not inside in/out (${from}…${to})`);
    const sec = Math.round((to - from) * FPS) / FPS, peak = clip.peak ?? peakOf(clip.reaction);
    if (clip.crop && !(clip.crop.w > 0 && clip.crop.h > 0 && clip.crop.x >= 0 && clip.crop.y >= 0)) throw new Error(`${ep.id}: ${clip.file} — a crop needs x, y ≥ 0 and w, h > 0`);
    segments.push({ kind: "clip", clip, start: t, sec, from, impactAt: clip.impact - from, reactionAt: clip.impact - from - peak, peak });
    t += sec;
    if (ep.verdict && ep.verdict.after === i + 1) host(ep.verdict.line);
  });
  if (ep.signOff) host(ep.signOff);
  segments.push({ kind: "tag", start: t, sec: TAG_SEC });
  return { segments, totalSec: t + TAG_SEC };
}

const FF = ["-hide_banner", "-loglevel", "error", "-y", "-threads", "4"];
const CODEC = ["-c:v", "libx264", "-profile:v", "high", "-preset", "medium", "-crf", "19", "-maxrate", "10M", "-bufsize", "20M", "-pix_fmt", "yuv420p", "-r", String(FPS), "-g", String(FPS * 2), "-c:a", "aac", "-b:a", "160k", "-ar", "48000", "-ac", "2"];
const probe = async (file: string) => { const j = JSON.parse((await run("ffprobe", ["-v", "error", "-show_streams", "-show_format", "-of", "json", file])).stdout); const v = j.streams.find((s: any) => s.codec_type === "video"); return { sec: Number(j.format.duration), w: Number(v.width), h: Number(v.height), audio: j.streams.some((s: any) => s.codec_type === "audio") }; };
/** The shot of a reaction or host line by id: its finished pure.mp4 / clip.mp4, else its only raw take. */
export const shotOf = (id: string) => {
  const dir = path.join(OUT, id), f = ["pure.mp4", "clip.mp4"].map((x) => path.join(dir, x)).find((x) => fs.existsSync(x));
  if (f) return f;
  const raw = fs.existsSync(path.join(dir, "videos")) ? fs.readdirSync(path.join(dir, "videos")).filter((x) => x.endsWith(".mp4")) : [];
  if (raw.length === 1) return path.join(dir, "videos", raw[0]);
  throw new Error(`${id}: not made (${dir}${raw.length ? `: ${raw.length} raw takes — name the file` : ""})`);
};
/** An id (see shotOf) or a file path relative to analysis/gator-shorts. */
export const sourceOf = (ref: string) => {
  if (!/\.(mp4|mov|webm|mkv)$/i.test(ref)) return shotOf(ref);
  const f = path.resolve(OUT, ref);
  if (!f.startsWith(path.resolve(OUT) + path.sep)) throw new Error(`${ref}: outside analysis/gator-shorts`);
  if (!fs.existsSync(f)) throw new Error(`${ref}: no such file under analysis/gator-shorts`);
  return f;
};
const A = "aresample=48000,aformat=sample_fmts=fltp:channel_layouts=stereo";
const FILL = `fps=${FPS},scale=${W}:${H}:force_original_aspect_ratio=increase,crop=${W}:${H},setsar=1`;
const even = (n: number) => Math.max(2, Math.round(n / 2) * 2);

async function main() {
  const args = parseArgs(process.argv.slice(2), ["owner-accepted-risk"]);
  const epFile = args._[0];
  if (!epFile) throw new Error("usage: reacts.ts <episode.json> [--out file.mp4] [--owner-accepted-risk]");
  const ep = JSON.parse(fs.readFileSync(epFile, "utf8")) as Episode;
  const consent: Consent = { flag: args.flags["owner-accepted-risk"] === true, record: ep.ownerAcceptedRisk };
  for (const c of ep.clips) { const no = rightsRefusal(c, consent); if (no) throw new Error(no); }
  const thirdParty = ep.clips.filter((c) => c.rights?.kind === "third-party");
  if (thirdParty.length) console.warn(`  ⚠ THIRD-PARTY FOOTAGE (unlicensed): ${thirdParty.length} clip(s) from ${[...new Set(thirdParty.map((c) => (c.rights as { channel: string }).channel))].join(", ")} — used on the owner's accepted risk (${ep.ownerAcceptedRisk!.by}, ${ep.ownerAcceptedRisk!.date}). Copyright claims, takedowns and account strikes are possible. Watermarks are kept.`);
  const out = typeof args.flags.out === "string" ? path.resolve(args.flags.out) : path.join(OUT, "_reacts", `reacts-${ep.id}.mp4`);
  const work = path.join(OUT, "_reacts", `.work-${ep.id}`); fs.mkdirSync(work, { recursive: true });
  const w = (f: string) => path.join(work, f);
  const durations: Record<string, number> = {}, info: Record<string, Awaited<ReturnType<typeof probe>>> = {};
  for (const c of ep.clips) {
    info[c.file] ??= await probe(sourceOf(c.file)); durations[c.file] = info[c.file].sec;
    const k = c.crop, ci = info[c.file];
    if (k && (k.x + k.w > ci.w || k.y + k.h > ci.h)) throw new Error(`${c.file}: the crop ${k.w}x${k.h}+${k.x}+${k.y} is outside the ${ci.w}x${ci.h} picture`);
  }
  const hosts = [ep.open, ep.verdict?.line, ep.signOff].filter((x): x is HostLine => !!x).map(hostOf);
  for (const h of hosts) { info[h.id] = await probe(sourceOf(h.id)); durations[h.id] = info[h.id].sec; }
  const { segments, totalSec } = plan(ep, durations, consent);
  fs.copyFileSync(path.join(ROOT, "scripts/tutorials/assets/Anton-Regular.ttf"), w("Anton-Regular.ttf"));
  const parts: string[] = [];
  for (const [i, s] of segments.entries()) {
    const part = w(`part${String(i).padStart(2, "0")}.mp4`); parts.push(part);
    if (s.kind === "tag") {
      // Logo only — endTagHtml(false) has no mascot: the cartoon gator never closes a live-gator video.
      await renderStill(endTagHtml(false), w("end.png"), W, { size: { width: W, height: H } });
      await run("ffmpeg", [...FF, "-loop", "1", "-t", String(s.sec), "-i", w("end.png"), "-f", "lavfi", "-t", String(s.sec), "-i", "anullsrc=r=48000:cl=stereo", "-vf", `${FILL},format=yuv420p`, ...CODEC, "-t", String(s.sec), part], { nice: true });
    } else if (s.kind === "host") {
      const social = path.join(OUT, s.line, "social.json");
      const text = s.caption ?? (fs.existsSync(social) ? JSON.parse(fs.readFileSync(social, "utf8")).speech?.script ?? "" : "");
      fs.writeFileSync(w(`host${i}.ass`), assFile(text ? [layoutBeat({ at: 0.05, until: s.sec, text, pos: "low", small: true })] : []));
      await run("ffmpeg", [...FF, "-ss", s.from.toFixed(3), "-t", s.sec.toFixed(3), "-i", sourceOf(s.line), "-vf", `${FILL},ass=host${i}.ass:fontsdir=.,format=yuv420p`, "-af", A, ...CODEC, "-t", s.sec.toFixed(3), part], { nice: true, cwd: work });
    } else {
      const src = sourceOf(s.clip.file), rf = sourceOf(s.clip.reaction), ri = await probe(rf), ci = info[s.clip.file];
      const cw = even(ri.w * REACTION_CROP.w), ch = Math.min(ri.h, even(cw * PANEL.h / PANEL.w)), cx = Math.max(0, Math.min(ri.w - cw, Math.round(ri.w * REACTION_CROP.cx - cw / 2))), cy = Math.max(0, Math.min(ri.h - ch, Math.round(ri.h * REACTION_CROP.cy - ch / 2)));
      // The clip's own crop box (source pixels) comes first; a ~9:16 box then fills the frame, anything wider is
      // fitted whole over a blurred copy of itself. NB: no step here removes, blurs or covers a watermark — by decision.
      const k = s.clip.crop, pre = k ? `crop=${even(k.w)}:${even(k.h)}:${Math.round(k.x)}:${Math.round(k.y)},` : "";
      const pw = k ? k.w : ci.w, ph = k ? k.h : ci.h, wide = pw / ph > 0.6;
      const bg = wide ? `[0:v]${pre}fps=${FPS},split[a][b];[a]scale=${W}:${H}:force_original_aspect_ratio=increase,crop=${W}:${H},boxblur=30:4,eq=brightness=-0.12[bl];[b]scale=${W}:-2[fg];[bl][fg]overlay=0:(H-h)/2,setsar=1[bg]` : `[0:v]${pre}${FILL}[bg]`;
      const lead = Math.max(0, s.reactionAt), skip = Math.max(0, -s.reactionAt), at = PANEL_AT[s.clip.panel ?? "bl"];
      if (!at) throw new Error(`${s.clip.file}: panel “${s.clip.panel}” is not bl, br, tl or tr`);
      const pip = `[1:v]fps=${FPS},trim=start=${skip.toFixed(3)},setpts=PTS-STARTPTS,crop=${cw}:${ch}:${cx}:${cy},scale=${PANEL.w}:${PANEL.h},setsar=1,tpad=start_mode=clone:start_duration=${lead.toFixed(3)}:stop_mode=clone:stop_duration=30,pad=${PW}:${PH}:${PANEL.border}:${PANEL.border}:white[pip]`;
      const audio = [ci.audio ? `[0:a]${A},volume=1[ca]` : `anullsrc=r=48000:cl=stereo,atrim=duration=${s.sec.toFixed(3)}[ca]`, ri.audio ? `[1:a]${A},atrim=start=${skip.toFixed(3)},asetpts=PTS-STARTPTS,adelay=${Math.round(lead * 1000)}:all=1,volume=0.9[ra];[ca][ra]amix=inputs=2:duration=first:normalize=0[a]` : `[ca]anull[a]`].join(";");
      await run("ffmpeg", [...FF, "-ss", s.from.toFixed(3), "-t", s.sec.toFixed(3), "-i", src, "-i", rf, "-filter_complex", `${bg};${pip};[bg][pip]overlay=${at.x}:${at.y}:shortest=0,format=yuv420p[v];${audio}`, "-map", "[v]", "-map", "[a]", ...CODEC, "-t", s.sec.toFixed(3), part], { nice: true });
    }
  }
  // Join, lay the music bed low under everything but the host lines, tame the impact peaks (as replay.ts does —
  // without it the true-peak ceiling holds the whole at ~−16) and bring the whole to −14 LUFS.
  const music = await track(ep.music ?? "sneaking-around");
  const duck = segments.filter((s) => s.kind === "host").map((s) => `between(t,${s.start.toFixed(2)},${(s.start + s.sec).toFixed(2)})`).join("+") || "0";
  const graph = `${parts.map((_p, i) => `[${i}:v][${i}:a]`).join("")}concat=n=${parts.length}:v=1:a=1[v][body];[${parts.length}:a]${A},atrim=start=2:duration=${totalSec.toFixed(3)},asetpts=PTS-STARTPTS,volume='if(${duck},0.05,0.16)':eval=frame,afade=t=out:st=${(totalSec - 0.8).toFixed(2)}:d=0.8[m];[body][m]amix=inputs=2:duration=first:normalize=0,acompressor=threshold=-24dB:ratio=4:attack=3:release=140:makeup=6,alimiter=limit=0.84:level=false,loudnorm=I=${LOUDNESS.I}:TP=-1.5:LRA=${LOUDNESS.LRA},alimiter=limit=0.84:level=false,${A}[a]`;
  fs.mkdirSync(path.dirname(out), { recursive: true });
  await run("ffmpeg", [...FF, ...parts.flatMap((p) => ["-i", p]), "-i", music, "-filter_complex", graph, "-map", "[v]", "-map", "[a]", ...CODEC, "-t", totalSec.toFixed(3), "-movflags", "+faststart", out], { nice: true });
  const loud = await measureLoudness(out);
  await run("ffmpeg", [...FF, "-i", out, "-vf", `fps=1.5,scale=180:320,tile=${Math.min(12, Math.ceil(totalSec * 1.5 / 3))}x3`, "-frames:v", "1", "-q:v", "3", out.replace(/\.mp4$/, "-review.jpg")], { nice: true });
  const sources = ep.clips.map((c) => ({ clip: c.file, kind: c.rights?.kind, ...(c.rights?.kind === "third-party" ? { source: c.rights.source, channel: c.rights.channel } : c.rights?.kind === "cc-by" ? { source: c.rights.url } : {}) }));
  fs.writeFileSync(out.replace(/\.mp4$/, ".json"), JSON.stringify({
    id: ep.id, seconds: Math.round(totalSec * 100) / 100, lufs: loud.lufs, truePeakDb: loud.truePeakDb,
    segments: segments.map((s) => (s.kind === "clip" ? { clip: s.clip.file, from: s.from, start: s.start, sec: s.sec, reaction: s.clip.reaction, peak: s.peak, impactAt: s.start + s.impactAt, panel: s.clip.panel ?? "bl", rights: s.clip.rights } : s.kind === "host" ? { host: s.line, from: s.from, start: s.start, sec: s.sec } : { tag: true, start: s.start, sec: s.sec })),
    sources, credits: creditsOf(ep), ...(thirdParty.length ? { thirdParty: true, ownerAcceptedRisk: ep.ownerAcceptedRisk } : {}),
  }, null, 2) + "\n");
  console.log(`  ${path.relative(ROOT, out)}  ${totalSec.toFixed(2)} s  ${loud.lufs} LUFS, true peak ${loud.truePeakDb} dBTP  — LOOK at ${path.basename(out.replace(/\.mp4$/, "-review.jpg"))}`);
}
if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(import.meta.filename)) main().then(() => process.exit(0), (e) => { console.error(`\n✗ ${e instanceof Error ? e.message : e}`); process.exit(1); });
