/**
 * "Gator Reacts" — the episode edit: fail clips with the gator cropped in, reacting at the impact, and
 * full-screen host lines between them.
 *
 * RUN
 *   npx tsx --env-file=.env.gator scripts/gator/reacts.ts docs/gator/reacts/<id>.json [--out file.mp4]
 *   npx tsx --env-file=.env.gator scripts/gator/reacts.ts docs/gator/reacts/<id>.json --owner-accepted-risk   (third-party clips; see below)
 * Writes analysis/gator-shorts/_reacts/reacts-<id>.mp4 (+ -review.jpg contact sheet, + .json sidecar) unless --out.
 *
 * THE EPISODE (docs/gator/reacts/<id>.json) — every path is relative to analysis/gator-shorts/:
 *   {
 *     "id": "ep01",
 *     "music": "sneaking-around",                              // a CC0 bed from scripts/gator/music.ts
 *     "open": "host-open",                                     // a host line: an id (its pure.mp4 / clip.mp4 / only raw take)
 *     "verdict": { "after": 2, "line": { "id": "host-write-up", "in": 0.2, "out": 2.9, "caption": "That's a write-up." } },
 *     "signOff": "host-sign-off",                              // optional
 *     "ownerAcceptedRisk": { "by": "…", "date": "2026-10-08", "quote": "…" },   // only for third-party clips
 *     "clips": [
 *       { "file": "fx-raccoon-plank/videos/s1-still1-take1.mp4",
 *         "impact": 2.6,                                       // seconds in the SOURCE file
 *         "in": 0.4, "out": 4.4,                               // optional: the range used (else impact − 2.0 … impact + 1.6;
 *                                                              //   the old relative "pre"/"post" fields still work)
 *         "crop": { "x": 656, "y": 0, "w": 608, "h": 1080 },   // optional, source pixels: cropped to this box, then a ~9:16
 *                                                              //   box fills 1080×1920, anything wider is fitted over a blur
 *         "panel": "bl",                                       // where the gator sits: bl (default), br, tl, tr
 *         "reaction": "react-shocked-01-jaw-drop",             // an id, or a file, e.g. "_deliver/reaction-shocked-01-jaw-drop.mp4"
 *         "peak": 1.9,                                         // optional: seconds into the reaction it peaks (else PEAK_AT / 0.7)
 *         "rights": { "kind": "own-ai", "record": "generated by us, Higgsfield …" } }
 *     ]
 *   }
 * A host line is either a plain id or { "id", "in", "out", "caption" } (trimmed to in…out; the caption replaces
 * the line's social.json script). The reaction's PEAK lands on the clip's IMPACT; no reaction is used twice.
 *
 * THE RIGHTS RULE — in the tool, not in a habit: every clip carries a rights record:
 *   own-ai       generated by us (the animal cast; AI-labelled)
 *   owner        filmed by the owner or his crews, with their say-so
 *   licensed     bought or licensed for commercial social use — `licensor` and `licence` (the reference) required
 *   cc-by        published under Creative Commons Attribution — `url` and `attribution` required (and credited)
 *   third-party  somebody else's video, NOT licensed — `source` (the https YouTube address) and `channel` required.
 *                Refused unless BOTH the run has --owner-accepted-risk AND the episode carries
 *                "ownerAcceptedRisk": { "by", "date" (YYYY-MM-DD), "quote" } — the owner's own words accepting the
 *                copyright / takedown / account-strike risk. Never a default. Such a run prints a warning, and
 *                the sidecar records every clip's source and channel plus a credits list "clips: <channel> (YouTube)".
 * A clip with no record, an unknown kind, or a record that admits it is unlicensed under another kind is refused.
 * See docs/gator/CLIP-LICENSING.md for how to get footage properly.
 *
 * WATERMARKS — by decision, this tool has NO watermark-removal step and never gets one: it does not remove, blur,
 * crop out or cover a creator's watermark or handle. The only lever is `panel`, which moves the gator AWAY from a
 * watermark; a `crop` must not be chosen to cut one off. A record that says it was de-watermarked is refused.
 *
 * THE EDIT: vertical 1080×1920; each clip at real speed; the gator panel (head-and-shoulders, 460×560) sits in
 * its corner for the whole clip, clear of the bottom 250 px the platforms draw over; full-screen host lines with
 * a caption; a 0.8 s logo-only end tag (never the cartoon mascot: this is a live-gator video); a CC0 music bed
 * low under the clips' own sound; −14 LUFS.
 *
 * ── FORMAT 2: "cutaway" (the owner, 2026-10-08: "the gator should be in between scenes, not overlay") ──────────
 *   npx tsx --env-file=.env.gator scripts/gator/reacts.ts docs/gator/reacts/<id>.json [--owner-accepted-risk] [--out f.mp4]
 * An episode with "format": "cutaway" is cut fail → hard cut → full-screen silent gator beat → next fail. No PiP, no
 * captions, no host lines. Same rights rules and output files as above (+ per fail its crop window in source pixels).
 *   {
 *     "id": "c01", "format": "cutaway", "music": "sneaking-around",
 *     "musicLevel": 0.12,                                       // optional: the bed's level (of full scale), ducked under gator beats
 *     "accent": "whoosh",                                       // optional: a quiet synthesised cue (sound.ts synth: whoosh, thud, tick,
 *                                                               //   hit, pop, ding) at each cut to a gator; default none
 *     "ownerAcceptedRisk": { … },                               // only for third-party fails (and the run needs the flag)
 *     "sequence": [
 *       { "fail": { "file": "fx-raccoon-plank/videos/s1-still1-take1.mp4", "in": 0.6, "out": 3.4, "impact": 2.7,
 *                   "crop": { "x": 408, "y": 0, "w": 1104, "h": 1080 },   // optional: the clip's own picture (source px)
 *                   "frame": { "x0": 0.3, "x1": 0.6, "y": 0.5 },          // optional: where the 9:16 window sits in the slack
 *                                                                          //   (0 left/top … 1 right/bottom); x0 → x1 pans over the clip
 *                   "rights": { "kind": "own-ai", "record": "…" } } },
 *       { "gator": "_deliver/reaction-deadpan-20-glance.mp4", "sec": 1.6, "lead": 0.25, "audio": "keep", "peak": 2.0 },
 *       …
 *     ]
 *   }
 * The rules (planCutaway, tested): starts with a fail (the hook is in the first second, never the gator first), ends with a
 * gator; never two gators in a row; no reaction file twice; a gator beat lasts 1.2–2.5 s; the whole runs 30–45 s INCLUDING
 * the 0.8 s logo-only end tag, else it is refused with the numbers ("testOnlyAllowAnyLength": true lifts only that rule,
 * for test renders — never on a posted episode). A gator beat plays the reaction from (peak − lead) for `sec` s, so its
 * peak lands right after the cut; when the file runs out first its last frame is held ("frozenSec" in the sidecar).
 * peak / lead / audio default from analysis/gator-shorts/_reactions/pack.json (else every _reactions/pack-*.json
 * merged), keyed by the reaction's file name; without an entry the episode must give "peak" (lead 0, audio mute).
 * A fail plays in…out at real speed with its own sound, cropped to `crop`, then FILLS 9:16 (scaled to cover — no bars,
 * no blur, no letterbox). NB: by decision there is NO watermark-removal step here either; a crop/frame must not be
 * chosen to cut a watermark off.
 */
import fs from "fs";
import path from "path";
import { ROOT, encodeWav, parseArgs, run } from "../tutorials/lib";
import { renderStill } from "../tutorials/brand";
import { LOUDNESS, measureLoudness } from "../tutorials/mux";
import { endTagHtml } from "./brand";
import { FPS, H, W, assFile, layoutBeat } from "./layout";
import { OUT } from "./make";
import { track } from "./music";
import { synth, toPcm, RATE, type Cue } from "./sound";

export type Rights =
  | { kind: "own-ai"; record: string }
  | { kind: "owner"; record: string }
  | { kind: "licensed"; record: string; licensor: string; licence: string }
  | { kind: "cc-by"; record: string; url: string; attribution: string }
  | { kind: "third-party"; record: string; source: string; channel: string };
export type Crop = { x: number; y: number; w: number; h: number };
export type Corner = "bl" | "br" | "tl" | "tr";
export type ReactClip = {
  file: string; /** Seconds in the source file. */ impact: number; reaction: string;
  /** The source range used (absolute seconds); without them, `pre` / `post` seconds around the impact (defaults 2.0 / 1.6). */
  in?: number; out?: number; pre?: number; post?: number;
  crop?: Crop; panel?: Corner; /** Seconds into the reaction at which it peaks (overrides PEAK_AT). */ peak?: number; rights?: Rights;
};
export type HostLine = string | { id: string; in?: number; out?: number; caption?: string };
export type RiskRecord = { by: string; date: string; quote: string };
export type Episode = { id: string; open?: HostLine; clips: ReactClip[]; verdict?: { after: number; line: HostLine }; signOff?: HostLine; music?: string; ownerAcceptedRisk?: RiskRecord };
/** The run's consent to third-party clips: the CLI flag and the episode's record — both are needed. */
export type Consent = { flag?: boolean; record?: unknown };
export const PRE = 2.0, POST = 1.6, TAG_SEC = 0.8;
/** The gator panel (inside a white border). Its corners keep it clear of the bottom 250 px and the top tabs. */
export const PANEL = { w: 460, h: 560, border: 6 };
const PW = PANEL.w + 2 * PANEL.border, PH = PANEL.h + 2 * PANEL.border;
export const PANEL_AT: Record<Corner, { x: number; y: number }> = { bl: { x: 36, y: H - 250 - PH - 8 }, br: { x: W - 36 - PW, y: H - 250 - PH - 8 }, tl: { x: 36, y: 230 }, tr: { x: W - 36 - PW, y: 230 } };
/** The head-and-shoulders crop of a reaction shot (hat to vest), as fractions of its 9:16 frame — the coffee-by-the-ladder framing (checked by eye 2026-10-08). */
export const REACTION_CROP = { cx: 0.5, cy: 0.31, w: 0.6 };
/** When a reaction peaks, seconds from its start (default 0.7). The takes open with ~1.5 s of calm: the listed ones were measured by eye. */
export const PEAK_AT: Record<string, number> = { "react-shocked-01-jaw-drop": 1.9, "react-annoyed-09-head-shake": 2.0, "react-deadpan-17-still": 1.5, "react-shocked-02-spit-take": 1.2, "react-shocked-04-double-take": 1.3, "react-shocked-07-frozen-sip": 1.2, "react-shocked-08-lean-in": 1.5, "react-annoyed-10-facepalm": 1.4, "react-annoyed-11-exhale": 1.5, "react-annoyed-16-slow-turn": 1.8 };
/** The peak of a reaction given as an id or as a file under it (`<id>/videos/…`). */
export const peakOf = (reaction: string) => PEAK_AT[reaction] ?? PEAK_AT[reaction.split("/")[0]] ?? 0.7;
export const hostOf = (h: HostLine) => (typeof h === "string" ? { id: h } : h);

const str = (o: Record<string, unknown> | undefined, k: string) => typeof o?.[k] === "string" && (o[k] as string).trim().length >= 3;
/** Whether the episode's ownerAcceptedRisk record is complete: who, when (YYYY-MM-DD), and his words. */
export const riskRecordOk = (r: unknown) => { const o = r as Record<string, unknown> | undefined; return !!o && typeof o === "object" && str(o, "by") && str(o, "quote") && /^\d{4}-\d{2}-\d{2}$/.test(String(o.date ?? "")); };

/** Why a clip may not be used — or null. Third-party clips need the consent (flag AND record); nothing else lifts a refusal. */
export function rightsRefusal(c: { file: string; rights?: unknown }, consent: Consent = {}): string | null {
  const r = c.rights as Record<string, unknown> | undefined;
  if (!r || typeof r !== "object") return `${c.file}: no rights record — a clip is never used without one`;
  if (!str(r, "record")) return `${c.file}: the rights record says nothing`;
  if (/de-?watermark|watermark (removed|blurred|cropped)|logo removed/i.test(String(r.record))) return `${c.file}: footage with a creator’s watermark removed is not used (this tool keeps watermarks)`;
  if (r.kind === "third-party") {
    if (!consent.flag) return `${c.file}: somebody else's video without a licence is not used — unless the owner accepts the risk: run with --owner-accepted-risk AND put "ownerAcceptedRisk": { by, date, quote } in the episode`;
    if (!riskRecordOk(consent.record)) return `${c.file}: --owner-accepted-risk was given but the episode has no complete "ownerAcceptedRisk": { by, date (YYYY-MM-DD), quote } — both are needed`;
    if (!/^https:\/\/(www\.|m\.)?(youtube\.com|youtu\.be)\//.test(String(r.source ?? ""))) return `${c.file}: a third-party clip needs its source — the https YouTube address it came from`;
    return str(r, "channel") ? null : `${c.file}: a third-party clip needs the channel it came from (credited)`;
  }
  if (/third.?party|unlicen[cs]ed|scraped|found online/i.test(`${r.kind} ${r.record}`)) return `${c.file}: somebody else's video without a licence is not used under kind “${String(r.kind)}” — label it third-party (license it, ask its creator, or use our own — docs/gator/CLIP-LICENSING.md)`;
  if (r.kind === "own-ai" || r.kind === "owner") return null;
  if (r.kind === "licensed") return str(r, "licensor") && str(r, "licence") ? null : `${c.file}: a licensed clip needs its licensor and the licence reference`;
  if (r.kind === "cc-by") return str(r, "attribution") && /^https:\/\//.test(String(r.url ?? "")) ? null : `${c.file}: a CC-BY clip needs its address and the attribution to print`;
  return `${c.file}: “${String(r.kind)}” is not a kind of rights this tool knows (own-ai, owner, licensed, cc-by, third-party)`;
}
/** The credits to print with the post: CC-BY attributions, and "clips: <channel> (YouTube)" per third-party channel. */
export function creditsOf(ep: Episode): string[] {
  const out = ep.clips.flatMap((c) => (c.rights?.kind === "cc-by" ? [c.rights.attribution] : c.rights?.kind === "third-party" ? [`clips: ${c.rights.channel} (YouTube)`] : []));
  return [...new Set(out)];
}
export type Segment =
  | { kind: "host"; line: string; start: number; sec: number; from: number; caption?: string }
  | { kind: "clip"; clip: ReactClip; start: number; sec: number; from: number; /** Seconds into the segment at which the reaction starts playing (negative: the reaction is already under way). */ reactionAt: number; impactAt: number; peak: number }
  | { kind: "tag"; start: number; sec: number };
/**
 * The timeline. `durations`: seconds of every file used (clips by `file`, host lines by id, reactions are not needed).
 * No reaction is used twice in an episode. Pure (tested).
 */
export function plan(ep: Episode, durations: Readonly<Record<string, number>>, consent: Consent = {}): { segments: Segment[]; totalSec: number } {
  if (!ep.clips.length) throw new Error(`${ep.id}: an episode needs clips`);
  for (const c of ep.clips) { const no = rightsRefusal(c, { flag: consent.flag, record: consent.record ?? ep.ownerAcceptedRisk }); if (no) throw new Error(no); }
  const used = ep.clips.map((c) => c.reaction), twice = used.find((r, i) => used.indexOf(r) !== i);
  if (twice) throw new Error(`${ep.id}: the reaction ${twice} is used twice — vary them`);
  const segments: Segment[] = []; let t = 0;
  const host = (line: HostLine) => {
    const h = hostOf(line), d = durations[h.id];
    if (!(d > 0)) throw new Error(`${ep.id}: no host line ${h.id}`);
    const from = Math.max(0, h.in ?? 0), to = Math.min(d, h.out ?? d), sec = Math.round((to - from) * FPS) / FPS;
    if (!(sec > 0)) throw new Error(`${ep.id}: host line ${h.id} — in/out (${h.in}…${h.out}) leave nothing of its ${d} s`);
    segments.push({ kind: "host", line: h.id, start: t, sec, from, ...(h.caption !== undefined ? { caption: h.caption } : {}) }); t += sec;
  };
  if (ep.open) host(ep.open);
  ep.clips.forEach((clip, i) => {
    const d = durations[clip.file];
    if (!(d > 0) || !(clip.impact >= 0 && clip.impact <= d)) throw new Error(`${ep.id}: ${clip.file} — the impact (${clip.impact}) is not inside the clip (${d} s)`);
    const from = Math.max(0, clip.in ?? clip.impact - (clip.pre ?? PRE)), to = Math.min(d, clip.out ?? clip.impact + (clip.post ?? POST));
    if (!(clip.impact >= from && clip.impact <= to)) throw new Error(`${ep.id}: ${clip.file} — the impact (${clip.impact}) is not inside in/out (${from}…${to})`);
    const sec = Math.round((to - from) * FPS) / FPS, peak = clip.peak ?? peakOf(clip.reaction);
    if (clip.crop && !(clip.crop.w > 0 && clip.crop.h > 0 && clip.crop.x >= 0 && clip.crop.y >= 0)) throw new Error(`${ep.id}: ${clip.file} — a crop needs x, y ≥ 0 and w, h > 0`);
    segments.push({ kind: "clip", clip, start: t, sec, from, impactAt: clip.impact - from, reactionAt: clip.impact - from - peak, peak });
    t += sec;
    if (ep.verdict && ep.verdict.after === i + 1) host(ep.verdict.line);
  });
  if (ep.signOff) host(ep.signOff);
  segments.push({ kind: "tag", start: t, sec: TAG_SEC });
  return { segments, totalSec: t + TAG_SEC };
}

/* ── FORMAT 2: cutaway ─────────────────────────────────────────────────────────────────────────────────────── */
export type Frame = { x0?: number; x1?: number; y?: number };
export type Fail = { file: string; in: number; out: number; impact: number; crop?: Crop; frame?: Frame; rights?: Rights };
export type GatorBeat = { gator: string; sec?: number; lead?: number; peak?: number; audio?: "keep" | "mute" };
export type Step = { fail: Fail } | GatorBeat;
export type CutawayEpisode = {
  id: string; format: "cutaway"; music?: string; musicLevel?: number; accent?: string; ownerAcceptedRisk?: RiskRecord;
  sequence: Step[]; /** Test renders only: lifts the 30–45 s rule (nothing else). Never on a posted episode. */ testOnlyAllowAnyLength?: boolean;
};
/** One entry of the reaction pack (analysis/gator-shorts/_reactions/pack.json), keyed by the reaction's file name. */
export type PackEntry = { family?: string; peak?: number; lead?: number; hold?: number; audio?: "keep" | "mute"; verdict?: string };
export const GATOR_SEC = { min: 1.2, max: 2.5, default: 1.6 }, CUTAWAY_SEC = { min: 30, max: 45 }, MUSIC_LEVEL = 0.12;
/** The cues an accent may be: our own synthesised sounds only (sound.ts) — short ones. */
export const ACCENTS = ["whoosh", "thud", "tick", "hit", "pop", "ding"] as const;
export type CutSegment =
  | { kind: "fail"; fail: Fail; start: number; sec: number; from: number; impactAt: number }
  | { kind: "gator"; file: string; start: number; sec: number; from: number; peak: number; lead: number; audio: "keep" | "mute"; /** Seconds of the beat that hold the reaction's last frame (it ran out). */ frozenSec: number }
  | { kind: "tag"; start: number; sec: number };
const q = (x: number) => Math.round(x * FPS) / FPS;
const isGator = (s: Step): s is GatorBeat => typeof (s as GatorBeat).gator === "string";
export const isCutaway = (ep: unknown): ep is CutawayEpisode => (ep as { format?: string })?.format === "cutaway";

/**
 * The cutaway timeline. `durations`: seconds of every file used (fails and reaction files). `pack`: reaction defaults by file
 * name. Pure (tested). Throws on any broken rule, with the numbers; `warnings` carries what a test-only option lifted.
 */
export function planCutaway(ep: CutawayEpisode, durations: Readonly<Record<string, number>>, pack: Readonly<Record<string, PackEntry>> = {}, consent: Consent = {}): { segments: CutSegment[]; totalSec: number; warnings: string[] } {
  const seq = ep.sequence ?? [], warnings: string[] = [];
  if (!seq.length) throw new Error(`${ep.id}: a cutaway episode needs a sequence`);
  if (isGator(seq[0])) throw new Error(`${ep.id}: the sequence starts with the gator — it must open on a fail (the hook is in the first second)`);
  if (!isGator(seq[seq.length - 1])) throw new Error(`${ep.id}: the sequence must end with a gator beat (the last punchline before the end tag)`);
  if (ep.accent !== undefined && !(ACCENTS as readonly string[]).includes(ep.accent)) throw new Error(`${ep.id}: accent “${ep.accent}” — only our own synthesised cues: ${ACCENTS.join(", ")}`);
  if (ep.musicLevel !== undefined && !(ep.musicLevel >= 0 && ep.musicLevel <= 0.5)) throw new Error(`${ep.id}: musicLevel ${ep.musicLevel} — 0…0.5 of full scale (default ${MUSIC_LEVEL}; the bed stays low)`);
  const seen = new Set<string>(), segments: CutSegment[] = []; let t = 0;
  seq.forEach((step, i) => {
    if (isGator(step)) {
      if (i > 0 && isGator(seq[i - 1])) throw new Error(`${ep.id}: step ${i + 1} — two gators in a row (${(seq[i - 1] as GatorBeat).gator}, ${step.gator}); a fail goes between them`);
      if (seen.has(step.gator)) throw new Error(`${ep.id}: the reaction ${step.gator} is used twice — vary them`);
      seen.add(step.gator);
      const d = durations[step.gator], p = pack[path.basename(step.gator)] ?? {};
      if (!(d > 0)) throw new Error(`${ep.id}: no reaction file ${step.gator}`);
      const peak = step.peak ?? p.peak, lead = step.lead ?? p.lead ?? 0, audio = step.audio ?? p.audio ?? "mute", sec = q(step.sec ?? GATOR_SEC.default);
      if (peak === undefined) throw new Error(`${ep.id}: ${step.gator} — no "peak" (not in the reaction pack): give it in the episode`);
      if (!(peak > 0 && peak < d)) throw new Error(`${ep.id}: ${step.gator} — peak ${peak} is not inside the file (${d} s)`);
      if (!(lead >= 0 && lead <= 0.5)) throw new Error(`${ep.id}: ${step.gator} — lead ${lead} must be 0…0.5 s (the peak comes right after the cut)`);
      if (audio !== "keep" && audio !== "mute") throw new Error(`${ep.id}: ${step.gator} — audio “${audio}” is keep or mute`);
      if (!(sec >= GATOR_SEC.min - 1e-6 && sec <= GATOR_SEC.max + 1e-6)) throw new Error(`${ep.id}: ${step.gator} — a gator beat is ${GATOR_SEC.min}–${GATOR_SEC.max} s, not ${step.sec}`);
      const from = Math.max(0, peak - lead), frozenSec = Math.max(0, q(sec - (d - from)));
      segments.push({ kind: "gator", file: step.gator, start: t, sec, from, peak, lead: peak - from, audio, frozenSec }); t += sec;
      return;
    }
    const f = (step as { fail?: Fail }).fail;
    if (!f || typeof f.file !== "string") throw new Error(`${ep.id}: step ${i + 1} is neither { "fail": {…} } nor { "gator": "…" }`);
    const no = rightsRefusal(f, { flag: consent.flag, record: consent.record ?? ep.ownerAcceptedRisk }); if (no) throw new Error(no);
    const d = durations[f.file];
    if (!(d > 0)) throw new Error(`${ep.id}: no fail file ${f.file}`);
    if (!(f.in >= 0 && f.out <= d + 1e-6 && f.out > f.in)) throw new Error(`${ep.id}: ${f.file} — in/out (${f.in}…${f.out}) must lie inside its ${d} s, in before out`);
    if (!(f.impact >= f.in && f.impact <= f.out)) throw new Error(`${ep.id}: ${f.file} — the impact (${f.impact}) is not inside in/out (${f.in}…${f.out})`);
    if (f.crop && !(f.crop.w > 0 && f.crop.h > 0 && f.crop.x >= 0 && f.crop.y >= 0)) throw new Error(`${ep.id}: ${f.file} — a crop needs x, y ≥ 0 and w, h > 0`);
    for (const [k, v] of Object.entries(f.frame ?? {})) if (!(typeof v === "number" && v >= 0 && v <= 1)) throw new Error(`${ep.id}: ${f.file} — frame.${k} ${v} must be 0…1`);
    const sec = q(f.out - f.in);
    segments.push({ kind: "fail", fail: f, start: t, sec, from: f.in, impactAt: f.impact - f.in }); t += sec;
  });
  segments.push({ kind: "tag", start: t, sec: TAG_SEC });
  const totalSec = t + TAG_SEC;
  if (totalSec < CUTAWAY_SEC.min - 1e-6 || totalSec > CUTAWAY_SEC.max + 1e-6) {
    const sum = (k: string) => segments.filter((s) => s.kind === k).reduce((a, s) => a + s.sec, 0).toFixed(2);
    const why = `${ep.id}: runs ${totalSec.toFixed(2)} s (fails ${sum("fail")} + gators ${sum("gator")} + end tag ${TAG_SEC}) — a cutaway episode is ${CUTAWAY_SEC.min}–${CUTAWAY_SEC.max} s`;
    if (ep.testOnlyAllowAnyLength !== true) throw new Error(why);
    warnings.push(`${why} (lifted by testOnlyAllowAnyLength — a test render, not for posting)`);
  }
  return { segments, totalSec, warnings };
}
/**
 * How a fail fills 9:16: the picture (after its crop) is scaled to cover 1080×1920, and the 9:16 window sits at
 * frame.x0 (→ x1, panning) of the horizontal slack, or frame.y of the vertical one. Returns the scale and, in SOURCE
 * pixels, the window at the clip's start and end. Pure (tested).
 */
export function fillWindow(pic: { w: number; h: number }, crop?: Crop, frame: Frame = {}) {
  const k = crop ?? { x: 0, y: 0, w: pic.w, h: pic.h };
  const scale = Math.max(W / k.w, H / k.h), sw = Math.max(W, Math.ceil(k.w * scale / 2) * 2), sh = Math.max(H, Math.ceil(k.h * scale / 2) * 2);
  const x0 = frame.x0 ?? 0.5, x1 = frame.x1 ?? x0, y = frame.y ?? 0.5, slackX = sw - W, slackY = sh - H;
  const win = (fx: number) => ({ x: Math.round(k.x + (slackX * fx) / scale), y: Math.round(k.y + (slackY * y) / scale), w: Math.round(W / scale), h: Math.round(H / scale) });
  return { crop: k, scale, sw, sh, slackX, slackY, x0, x1, y, start: win(x0), end: win(x1) };
}

const FF = ["-hide_banner", "-loglevel", "error", "-y", "-threads", "4"];
const CODEC = ["-c:v", "libx264", "-profile:v", "high", "-preset", "medium", "-crf", "19", "-maxrate", "10M", "-bufsize", "20M", "-pix_fmt", "yuv420p", "-r", String(FPS), "-g", String(FPS * 2), "-c:a", "aac", "-b:a", "160k", "-ar", "48000", "-ac", "2"];
const probe = async (file: string) => { const j = JSON.parse((await run("ffprobe", ["-v", "error", "-show_streams", "-show_format", "-of", "json", file])).stdout); const v = j.streams.find((s: any) => s.codec_type === "video"); return { sec: Number(j.format.duration), w: Number(v.width), h: Number(v.height), audio: j.streams.some((s: any) => s.codec_type === "audio") }; };
/** The shot of a reaction or host line by id: its finished pure.mp4 / clip.mp4, else its only raw take. */
export const shotOf = (id: string) => {
  const dir = path.join(OUT, id), f = ["pure.mp4", "clip.mp4"].map((x) => path.join(dir, x)).find((x) => fs.existsSync(x));
  if (f) return f;
  const raw = fs.existsSync(path.join(dir, "videos")) ? fs.readdirSync(path.join(dir, "videos")).filter((x) => x.endsWith(".mp4")) : [];
  if (raw.length === 1) return path.join(dir, "videos", raw[0]);
  throw new Error(`${id}: not made (${dir}${raw.length ? `: ${raw.length} raw takes — name the file` : ""})`);
};
/** An id (see shotOf) or a file path relative to analysis/gator-shorts. */
export const sourceOf = (ref: string) => {
  if (!/\.(mp4|mov|webm|mkv)$/i.test(ref)) return shotOf(ref);
  const f = path.resolve(OUT, ref);
  if (!f.startsWith(path.resolve(OUT) + path.sep)) throw new Error(`${ref}: outside analysis/gator-shorts`);
  if (!fs.existsSync(f)) throw new Error(`${ref}: no such file under analysis/gator-shorts`);
  return f;
};
const A = "aresample=48000,aformat=sample_fmts=fltp:channel_layouts=stereo";
const FILL = `fps=${FPS},scale=${W}:${H}:force_original_aspect_ratio=increase,crop=${W}:${H},setsar=1`;
const even = (n: number) => Math.max(2, Math.round(n / 2) * 2);

async function main() {
  const args = parseArgs(process.argv.slice(2), ["owner-accepted-risk"]);
  const epFile = args._[0];
  if (!epFile) throw new Error("usage: reacts.ts <episode.json> [--out file.mp4] [--owner-accepted-risk]");
  const raw = JSON.parse(fs.readFileSync(epFile, "utf8")) as unknown;
  if (isCutaway(raw)) return cutaway(raw, args);
  const ep = raw as Episode;
  const consent: Consent = { flag: args.flags["owner-accepted-risk"] === true, record: ep.ownerAcceptedRisk };
  for (const c of ep.clips) { const no = rightsRefusal(c, consent); if (no) throw new Error(no); }
  const thirdParty = ep.clips.filter((c) => c.rights?.kind === "third-party");
  if (thirdParty.length) console.warn(`  ⚠ THIRD-PARTY FOOTAGE (unlicensed): ${thirdParty.length} clip(s) from ${[...new Set(thirdParty.map((c) => (c.rights as { channel: string }).channel))].join(", ")} — used on the owner's accepted risk (${ep.ownerAcceptedRisk!.by}, ${ep.ownerAcceptedRisk!.date}). Copyright claims, takedowns and account strikes are possible. Watermarks are kept.`);
  const out = typeof args.flags.out === "string" ? path.resolve(args.flags.out) : path.join(OUT, "_reacts", `reacts-${ep.id}.mp4`);
  const work = path.join(OUT, "_reacts", `.work-${ep.id}`); fs.mkdirSync(work, { recursive: true });
  const w = (f: string) => path.join(work, f);
  const durations: Record<string, number> = {}, info: Record<string, Awaited<ReturnType<typeof probe>>> = {};
  for (const c of ep.clips) {
    info[c.file] ??= await probe(sourceOf(c.file)); durations[c.file] = info[c.file].sec;
    const k = c.crop, ci = info[c.file];
    if (k && (k.x + k.w > ci.w || k.y + k.h > ci.h)) throw new Error(`${c.file}: the crop ${k.w}x${k.h}+${k.x}+${k.y} is outside the ${ci.w}x${ci.h} picture`);
  }
  const hosts = [ep.open, ep.verdict?.line, ep.signOff].filter((x): x is HostLine => !!x).map(hostOf);
  for (const h of hosts) { info[h.id] = await probe(sourceOf(h.id)); durations[h.id] = info[h.id].sec; }
  const { segments, totalSec } = plan(ep, durations, consent);
  fs.copyFileSync(path.join(ROOT, "scripts/tutorials/assets/Anton-Regular.ttf"), w("Anton-Regular.ttf"));
  const parts: string[] = [];
  for (const [i, s] of segments.entries()) {
    const part = w(`part${String(i).padStart(2, "0")}.mp4`); parts.push(part);
    if (s.kind === "tag") {
      // Logo only — endTagHtml(false) has no mascot: the cartoon gator never closes a live-gator video.
      await renderStill(endTagHtml(false), w("end.png"), W, { size: { width: W, height: H } });
      await run("ffmpeg", [...FF, "-loop", "1", "-t", String(s.sec), "-i", w("end.png"), "-f", "lavfi", "-t", String(s.sec), "-i", "anullsrc=r=48000:cl=stereo", "-vf", `${FILL},format=yuv420p`, ...CODEC, "-t", String(s.sec), part], { nice: true });
    } else if (s.kind === "host") {
      const social = path.join(OUT, s.line, "social.json");
      const text = s.caption ?? (fs.existsSync(social) ? JSON.parse(fs.readFileSync(social, "utf8")).speech?.script ?? "" : "");
      fs.writeFileSync(w(`host${i}.ass`), assFile(text ? [layoutBeat({ at: 0.05, until: s.sec, text, pos: "low", small: true })] : []));
      await run("ffmpeg", [...FF, "-ss", s.from.toFixed(3), "-t", s.sec.toFixed(3), "-i", sourceOf(s.line), "-vf", `${FILL},ass=host${i}.ass:fontsdir=.,format=yuv420p`, "-af", A, ...CODEC, "-t", s.sec.toFixed(3), part], { nice: true, cwd: work });
    } else {
      const src = sourceOf(s.clip.file), rf = sourceOf(s.clip.reaction), ri = await probe(rf), ci = info[s.clip.file];
      const cw = even(ri.w * REACTION_CROP.w), ch = Math.min(ri.h, even(cw * PANEL.h / PANEL.w)), cx = Math.max(0, Math.min(ri.w - cw, Math.round(ri.w * REACTION_CROP.cx - cw / 2))), cy = Math.max(0, Math.min(ri.h - ch, Math.round(ri.h * REACTION_CROP.cy - ch / 2)));
      // The clip's own crop box (source pixels) comes first; a ~9:16 box then fills the frame, anything wider is
      // fitted whole over a blurred copy of itself. NB: no step here removes, blurs or covers a watermark — by decision.
      const k = s.clip.crop, pre = k ? `crop=${even(k.w)}:${even(k.h)}:${Math.round(k.x)}:${Math.round(k.y)},` : "";
      const pw = k ? k.w : ci.w, ph = k ? k.h : ci.h, wide = pw / ph > 0.6;
      const bg = wide ? `[0:v]${pre}fps=${FPS},split[a][b];[a]scale=${W}:${H}:force_original_aspect_ratio=increase,crop=${W}:${H},boxblur=30:4,eq=brightness=-0.12[bl];[b]scale=${W}:-2[fg];[bl][fg]overlay=0:(H-h)/2,setsar=1[bg]` : `[0:v]${pre}${FILL}[bg]`;
      const lead = Math.max(0, s.reactionAt), skip = Math.max(0, -s.reactionAt), at = PANEL_AT[s.clip.panel ?? "bl"];
      if (!at) throw new Error(`${s.clip.file}: panel “${s.clip.panel}” is not bl, br, tl or tr`);
      const pip = `[1:v]fps=${FPS},trim=start=${skip.toFixed(3)},setpts=PTS-STARTPTS,crop=${cw}:${ch}:${cx}:${cy},scale=${PANEL.w}:${PANEL.h},setsar=1,tpad=start_mode=clone:start_duration=${lead.toFixed(3)}:stop_mode=clone:stop_duration=30,pad=${PW}:${PH}:${PANEL.border}:${PANEL.border}:white[pip]`;
      const audio = [ci.audio ? `[0:a]${A},volume=1[ca]` : `anullsrc=r=48000:cl=stereo,atrim=duration=${s.sec.toFixed(3)}[ca]`, ri.audio ? `[1:a]${A},atrim=start=${skip.toFixed(3)},asetpts=PTS-STARTPTS,adelay=${Math.round(lead * 1000)}:all=1,volume=0.9[ra];[ca][ra]amix=inputs=2:duration=first:normalize=0[a]` : `[ca]anull[a]`].join(";");
      await run("ffmpeg", [...FF, "-ss", s.from.toFixed(3), "-t", s.sec.toFixed(3), "-i", src, "-i", rf, "-filter_complex", `${bg};${pip};[bg][pip]overlay=${at.x}:${at.y}:shortest=0,format=yuv420p[v];${audio}`, "-map", "[v]", "-map", "[a]", ...CODEC, "-t", s.sec.toFixed(3), part], { nice: true });
    }
  }
  // Join, lay the music bed low under everything but the host lines, tame the impact peaks (as replay.ts does —
  // without it the true-peak ceiling holds the whole at ~−16) and bring the whole to −14 LUFS.
  const music = await track(ep.music ?? "sneaking-around");
  const duck = segments.filter((s) => s.kind === "host").map((s) => `between(t,${s.start.toFixed(2)},${(s.start + s.sec).toFixed(2)})`).join("+") || "0";
  const graph = `${parts.map((_p, i) => `[${i}:v][${i}:a]`).join("")}concat=n=${parts.length}:v=1:a=1[v][body];[${parts.length}:a]${A},atrim=start=2:duration=${totalSec.toFixed(3)},asetpts=PTS-STARTPTS,volume='if(${duck},0.05,0.16)':eval=frame,afade=t=out:st=${(totalSec - 0.8).toFixed(2)}:d=0.8[m];[body][m]amix=inputs=2:duration=first:normalize=0,acompressor=threshold=-24dB:ratio=4:attack=3:release=140:makeup=6,alimiter=limit=0.84:level=false,loudnorm=I=${LOUDNESS.I}:TP=-1.5:LRA=${LOUDNESS.LRA},alimiter=limit=0.84:level=false,${A}[a]`;
  fs.mkdirSync(path.dirname(out), { recursive: true });
  await run("ffmpeg", [...FF, ...parts.flatMap((p) => ["-i", p]), "-i", music, "-filter_complex", graph, "-map", "[v]", "-map", "[a]", ...CODEC, "-t", totalSec.toFixed(3), "-movflags", "+faststart", out], { nice: true });
  const loud = await measureLoudness(out);
  await run("ffmpeg", [...FF, "-i", out, "-vf", `fps=1.5,scale=180:320,tile=${Math.min(12, Math.ceil(totalSec * 1.5 / 3))}x3`, "-frames:v", "1", "-q:v", "3", out.replace(/\.mp4$/, "-review.jpg")], { nice: true });
  const sources = ep.clips.map((c) => ({ clip: c.file, kind: c.rights?.kind, ...(c.rights?.kind === "third-party" ? { source: c.rights.source, channel: c.rights.channel } : c.rights?.kind === "cc-by" ? { source: c.rights.url } : {}) }));
  fs.writeFileSync(out.replace(/\.mp4$/, ".json"), JSON.stringify({
    id: ep.id, seconds: Math.round(totalSec * 100) / 100, lufs: loud.lufs, truePeakDb: loud.truePeakDb,
    segments: segments.map((s) => (s.kind === "clip" ? { clip: s.clip.file, from: s.from, start: s.start, sec: s.sec, reaction: s.clip.reaction, peak: s.peak, impactAt: s.start + s.impactAt, panel: s.clip.panel ?? "bl", rights: s.clip.rights } : s.kind === "host" ? { host: s.line, from: s.from, start: s.start, sec: s.sec } : { tag: true, start: s.start, sec: s.sec })),
    sources, credits: creditsOf(ep), ...(thirdParty.length ? { thirdParty: true, ownerAcceptedRisk: ep.ownerAcceptedRisk } : {}),
  }, null, 2) + "\n");
  console.log(`  ${path.relative(ROOT, out)}  ${totalSec.toFixed(2)} s  ${loud.lufs} LUFS, true peak ${loud.truePeakDb} dBTP  — LOOK at ${path.basename(out.replace(/\.mp4$/, "-review.jpg"))}`);
}
/** The reaction pack: pack.json if the coordinator has merged it, else every _reactions/pack-*.json merged (later names win). */
export function loadPack(dir = path.join(OUT, "_reactions")): Record<string, PackEntry> {
  const read = (f: string) => JSON.parse(fs.readFileSync(path.join(dir, f), "utf8")) as Record<string, PackEntry>;
  if (fs.existsSync(path.join(dir, "pack.json"))) return read("pack.json");
  if (!fs.existsSync(dir)) return {};
  return Object.assign({}, ...fs.readdirSync(dir).filter((f) => /^pack-.+\.json$/.test(f)).sort().map(read));
}

async function cutaway(ep: CutawayEpisode, args: ReturnType<typeof parseArgs>) {
  const consent: Consent = { flag: args.flags["owner-accepted-risk"] === true, record: ep.ownerAcceptedRisk };
  const fails = (ep.sequence ?? []).flatMap((s) => ("fail" in s && s.fail ? [s.fail] : []));
  for (const f of fails) { const no = rightsRefusal(f, consent); if (no) throw new Error(no); }
  const thirdParty = fails.filter((f) => f.rights?.kind === "third-party");
  if (thirdParty.length) console.warn(`  ⚠ THIRD-PARTY FOOTAGE (unlicensed): ${thirdParty.length} clip(s) from ${[...new Set(thirdParty.map((f) => (f.rights as { channel: string }).channel))].join(", ")} — used on the owner's accepted risk (${ep.ownerAcceptedRisk!.by}, ${ep.ownerAcceptedRisk!.date}). Copyright claims, takedowns and account strikes are possible. Watermarks are kept.`);
  const out = typeof args.flags.out === "string" ? path.resolve(args.flags.out) : path.join(OUT, "_reacts", `reacts-${ep.id}.mp4`);
  const work = path.join(OUT, "_reacts", `.work-${ep.id}`); fs.mkdirSync(work, { recursive: true });
  const w = (f: string) => path.join(work, f);
  const durations: Record<string, number> = {}, info: Record<string, Awaited<ReturnType<typeof probe>>> = {};
  for (const s of ep.sequence ?? []) {
    const file = "fail" in s && s.fail ? s.fail.file : (s as GatorBeat).gator;
    if (typeof file !== "string") continue;
    info[file] ??= await probe(sourceOf(file)); durations[file] = info[file].sec;
  }
  for (const f of fails) { const k = f.crop, ci = info[f.file]; if (k && (k.x + k.w > ci.w || k.y + k.h > ci.h)) throw new Error(`${f.file}: the crop ${k.w}x${k.h}+${k.x}+${k.y} is outside the ${ci.w}x${ci.h} picture`); }
  const { segments, totalSec, warnings } = planCutaway(ep, durations, loadPack(), consent);
  for (const x of warnings) console.warn(`  ⚠ ${x}`);
  const parts: string[] = [], windows: Record<number, ReturnType<typeof fillWindow>> = {};
  for (const [i, s] of segments.entries()) {
    const part = w(`cut${String(i).padStart(2, "0")}.mp4`); parts.push(part);
    if (s.kind === "tag") {
      // Logo only — endTagHtml(false) has no mascot: the cartoon gator never closes a live-gator video.
      await renderStill(endTagHtml(false), w("end.png"), W, { size: { width: W, height: H } });
      await run("ffmpeg", [...FF, "-loop", "1", "-t", String(s.sec), "-i", w("end.png"), "-f", "lavfi", "-t", String(s.sec), "-i", "anullsrc=r=48000:cl=stereo", "-vf", `${FILL},format=yuv420p`, ...CODEC, "-t", String(s.sec), part], { nice: true });
    } else if (s.kind === "fail") {
      // Cropped to the clip's own picture, scaled to COVER 9:16 and windowed (panning x0 → x1) — no bars, no blur.
      // NB: no step here removes, blurs or covers a watermark — by decision.
      const ci = info[s.fail.file], fw = fillWindow(ci, s.fail.crop, s.fail.frame); windows[i] = fw;
      const k = fw.crop, pre = s.fail.crop ? `crop=${Math.round(k.w)}:${Math.round(k.h)}:${Math.round(k.x)}:${Math.round(k.y)},` : "";
      const p = `min(1,t/${s.sec.toFixed(3)})`, x = `${fw.slackX}*(${fw.x0}+(${fw.x1 - fw.x0})*${p})`, y = `${Math.round(fw.slackY * fw.y)}`;
      const vf = `[0:v]${pre}fps=${FPS},scale=${fw.sw}:${fw.sh},crop=${W}:${H}:x='${x}':y=${y},setsar=1,format=yuv420p[v]`;
      const af = ci.audio ? `[0:a]${A},apad[a]` : `anullsrc=r=48000:cl=stereo[a]`;
      await run("ffmpeg", [...FF, "-ss", s.from.toFixed(3), "-t", s.sec.toFixed(3), "-i", sourceOf(s.fail.file), "-filter_complex", `${vf};${af}`, "-map", "[v]", "-map", "[a]", ...CODEC, "-t", s.sec.toFixed(3), part], { nice: true });
    } else {
      // The reaction from (peak − lead), full screen; when the file runs out its last frame is held (frozenSec).
      const ri = info[s.file], hold = s.frozenSec + 0.2;
      const vf = `[0:v]${FILL},tpad=stop_mode=clone:stop_duration=${hold.toFixed(3)},format=yuv420p[v]`;
      const af = s.audio === "keep" && ri.audio ? `[0:a]${A},apad[a]` : `anullsrc=r=48000:cl=stereo[a]`;
      await run("ffmpeg", [...FF, "-ss", s.from.toFixed(3), "-i", sourceOf(s.file), "-filter_complex", `${vf};${af}`, "-map", "[v]", "-map", "[a]", ...CODEC, "-t", s.sec.toFixed(3), part], { nice: true });
    }
  }
  // Music bed low under everything (a little lower under the gator beats), fading out; an optional quiet synthesised
  // accent at each cut to a gator; then the same compressor / limiter / loudnorm chain as the PiP format → −14 LUFS.
  const music = await track(ep.music ?? "sneaking-around"), level = ep.musicLevel ?? MUSIC_LEVEL;
  const gators = segments.filter((s) => s.kind === "gator");
  const duck = gators.map((s) => `between(t,${s.start.toFixed(2)},${(s.start + s.sec).toFixed(2)})`).join("+") || "0";
  const inputs = [...parts.flatMap((p) => ["-i", p]), "-i", music];
  let accent = "", mixIn = "[body][m]", mixN = 2;
  if (ep.accent) {
    const cues = gators.map((s) => ({ type: ep.accent, at: s.start, gain: 0.5 }) as Cue);
    fs.writeFileSync(w("accent.wav"), encodeWav({ sampleRate: RATE, samples: toPcm(synth(cues, totalSec)) }));
    inputs.push("-i", w("accent.wav"));
    accent = `;[${parts.length + 1}:a]${A},volume=0.18[x]`; mixIn += "[x]"; mixN = 3;
  }
  // Each part's audio is cut to its exact length first: the decoded AAC runs a few ms long, and concat would push every
  // later cut a frame or two late (measured: +2 frames by the 4th cut).
  const exact = segments.map((s, i) => `[${i}:a]apad,atrim=end=${s.sec.toFixed(4)},asetpts=PTS-STARTPTS[a${i}]`).join(";");
  const graph = `${exact};${parts.map((_p, i) => `[${i}:v][a${i}]`).join("")}concat=n=${parts.length}:v=1:a=1[v][body];[${parts.length}:a]${A},atrim=start=2:duration=${totalSec.toFixed(3)},asetpts=PTS-STARTPTS,volume='if(${duck},${(level * 0.7).toFixed(3)},${level.toFixed(3)})':eval=frame,afade=t=out:st=${Math.max(0, totalSec - 1.2).toFixed(2)}:d=1.2[m]${accent};${mixIn}amix=inputs=${mixN}:duration=first:normalize=0,acompressor=threshold=-24dB:ratio=4:attack=3:release=140:makeup=6,alimiter=limit=0.84:level=false,loudnorm=I=${LOUDNESS.I}:TP=-1.5:LRA=${LOUDNESS.LRA},alimiter=limit=0.84:level=false,${A}[a]`;
  fs.mkdirSync(path.dirname(out), { recursive: true });
  await run("ffmpeg", [...FF, ...inputs, "-filter_complex", graph, "-map", "[v]", "-map", "[a]", ...CODEC, "-t", totalSec.toFixed(3), "-movflags", "+faststart", out], { nice: true });
  const loud = await measureLoudness(out);
  await run("ffmpeg", [...FF, "-i", out, "-vf", `fps=2,scale=180:320,tile=${Math.min(12, Math.ceil(totalSec * 2 / 4))}x4`, "-frames:v", "1", "-q:v", "3", out.replace(/\.mp4$/, "-review.jpg")], { nice: true });
  const r2 = (n: number) => Math.round(n * 1000) / 1000;
  fs.writeFileSync(out.replace(/\.mp4$/, ".json"), JSON.stringify({
    id: ep.id, format: "cutaway", seconds: r2(totalSec), lufs: loud.lufs, truePeakDb: loud.truePeakDb, music: ep.music ?? "sneaking-around", musicLevel: level, accent: ep.accent ?? null,
    ...(warnings.length ? { testOnly: true, warnings } : {}),
    segments: segments.map((s, i) => s.kind === "fail"
      ? { fail: s.fail.file, in: s.fail.in, out: s.fail.out, start: r2(s.start), sec: r2(s.sec), impactAt: r2(s.start + s.impactAt), rights: s.fail.rights,
          fill: { picture: windows[i].crop, scale: r2(windows[i].scale), windowAtStart: windows[i].start, windowAtEnd: windows[i].end } }
      : s.kind === "gator" ? { gator: s.file, start: r2(s.start), sec: r2(s.sec), from: r2(s.from), peak: s.peak, lead: r2(s.lead), audio: s.audio, frozenSec: r2(s.frozenSec) }
      : { tag: true, start: r2(s.start), sec: s.sec }),
    sources: fails.map((f) => ({ clip: f.file, kind: f.rights?.kind, ...(f.rights?.kind === "third-party" ? { source: f.rights.source, channel: f.rights.channel } : f.rights?.kind === "cc-by" ? { source: f.rights.url } : {}) })),
    credits: creditsOf({ id: ep.id, clips: fails.map((f) => ({ ...f, reaction: "" })) }), ...(thirdParty.length ? { thirdParty: true, ownerAcceptedRisk: ep.ownerAcceptedRisk } : {}),
  }, null, 2) + "\n");
  console.log(`  ${path.relative(ROOT, out)}  ${totalSec.toFixed(2)} s  ${loud.lufs} LUFS, true peak ${loud.truePeakDb} dBTP  — LOOK at ${path.basename(out.replace(/\.mp4$/, "-review.jpg"))}`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(import.meta.filename)) main().then(() => process.exit(0), (e) => { console.error(`\n✗ ${e instanceof Error ? e.message : e}`); process.exit(1); });
