/**
 * "Gator Reacts" — the episode edit: fail clips with the gator cropped in, reacting at the impact, and
 * full-screen host lines between them.
 *
 *   npx tsx scripts/gator/reacts.ts <episode.json> [--out file.mp4]
 *
 * An episode (docs/gator/reacts/<id>.json):
 *   { "id": "ep01", "open": "host-open", "music": "sneaking-around",
 *     "clips": [ { "file": "fx-raccoon-plank/pure.mp4", "impact": 2.1, "reaction": "react-shocked-01-jaw-drop",
 *                  "rights": { "kind": "own-ai", "record": "generated by us, Higgsfield request …" } }, … ],
 *     "verdict": { "after": 3, "line": "host-write-up" }, "signOff": "host-sign-off" }
 *
 * THE RIGHTS RULE — in the tool, not in a habit: every clip carries a rights record, and only footage we may
 * use is accepted:
 *   own-ai     generated by us (the animal cast; AI-labelled)
 *   owner      filmed by the owner or his crews, with their say-so
 *   licensed   bought or licensed for commercial social use — `licensor` and `licence` (the reference) required
 *   cc-by      published under Creative Commons Attribution — `url` and `attribution` required (and credited)
 * A clip with no record, or one that is somebody else's video without a licence ("third-party, unlicensed"),
 * is refused. There is no flag that lifts this and no step that removes, crops out or covers another
 * creator's watermark: see docs/gator/CLIP-LICENSING.md for how to get real footage properly.
 *
 * THE EDIT: vertical 1080×1920 (a wide source is fitted with a blurred fill); each clip runs at real speed from
 * a little before its impact to a little after; the gator panel sits bottom-left the whole time and its
 * reaction is placed so that the reaction's PEAK lands on the clip's IMPACT; the host lines are full-screen
 * with a caption; a 0.8 s end tag; a CC0 music bed low under the clips' own sound; −14 LUFS.
 */
import fs from "fs";
import path from "path";
import { ROOT, parseArgs, run } from "../tutorials/lib";
import { renderStill } from "../tutorials/brand";
import { LOUDNESS, measureLoudness } from "../tutorials/mux";
import { endTagHtml } from "./brand";
import { FPS, H, W, assFile, layoutBeat } from "./layout";
import { OUT } from "./make";
import { track } from "./music";

export type Rights =
  | { kind: "own-ai"; record: string }
  | { kind: "owner"; record: string }
  | { kind: "licensed"; record: string; licensor: string; licence: string }
  | { kind: "cc-by"; record: string; url: string; attribution: string };
export type ReactClip = { file: string; impact: number; reaction: string; /** Seconds shown before / after the impact (defaults 2.0 / 1.6). */ pre?: number; post?: number; rights?: Rights };
export type Episode = { id: string; open?: string; clips: ReactClip[]; verdict?: { after: number; line: string }; signOff?: string; music?: string };
export const PRE = 2.0, POST = 1.6, TAG_SEC = 0.8;
/** Where the gator panel sits: bottom-left, above what the platforms draw over the bottom of a vertical video. */
export const PANEL = { x: 36, y: 1056, w: 400, h: 500, border: 6 };
/** The head-and-shoulders crop of a reaction shot, as fractions of its frame (the coffee-by-the-ladder framing). */
export const REACTION_CROP = { cx: 0.5, cy: 0.27, w: 0.56 };
/** When a reaction peaks, seconds from its start (default 0.7; the slow ones are listed). */
export const PEAK_AT: Record<string, number> = { "react-shocked-02-spit-take": 1.2, "react-shocked-04-double-take": 1.3, "react-shocked-07-frozen-sip": 1.2, "react-shocked-08-lean-in": 1.5, "react-annoyed-10-facepalm": 1.4, "react-annoyed-11-exhale": 1.5, "react-annoyed-16-slow-turn": 1.8 };
export const peakOf = (reaction: string) => PEAK_AT[reaction] ?? 0.7;

/** Why a clip may not be used — or null. Nothing lifts a refusal. */
export function rightsRefusal(c: { file: string; rights?: unknown }): string | null {
  const r = c.rights as Record<string, unknown> | undefined;
  const has = (k: string) => typeof r?.[k] === "string" && (r[k] as string).trim().length >= 3;
  if (!r || typeof r !== "object") return `${c.file}: no rights record — a clip is never used without one`;
  if (/third.?party|unlicen[cs]ed|scraped|found online/i.test(`${r.kind} ${r.record ?? ""}`)) return `${c.file}: somebody else's video without a licence is not used (license it, ask its creator, or use our own — docs/gator/CLIP-LICENSING.md)`;
  if (!has("record")) return `${c.file}: the rights record says nothing`;
  if (r.kind === "own-ai" || r.kind === "owner") return null;
  if (r.kind === "licensed") return has("licensor") && has("licence") ? null : `${c.file}: a licensed clip needs its licensor and the licence reference`;
  if (r.kind === "cc-by") return has("attribution") && /^https:\/\//.test(String(r.url ?? "")) ? null : `${c.file}: a CC-BY clip needs its address and the attribution to print`;
  return `${c.file}: “${String(r.kind)}” is not a kind of rights this tool knows (own-ai, owner, licensed, cc-by)`;
}
export type Segment =
  | { kind: "host"; line: string; start: number; sec: number }
  | { kind: "clip"; clip: ReactClip; start: number; sec: number; from: number; /** Seconds into the segment at which the reaction starts playing (negative: the reaction is already under way). */ reactionAt: number; impactAt: number }
  | { kind: "tag"; start: number; sec: number };
/**
 * The timeline. `durations`: seconds of every file used (clips by `file`, host lines and reactions by id).
 * No reaction is used twice in an episode. Pure (tested).
 */
export function plan(ep: Episode, durations: Readonly<Record<string, number>>): { segments: Segment[]; totalSec: number } {
  if (!ep.clips.length) throw new Error(`${ep.id}: an episode needs clips`);
  for (const c of ep.clips) { const no = rightsRefusal(c); if (no) throw new Error(no); }
  const used = ep.clips.map((c) => c.reaction), twice = used.find((r, i) => used.indexOf(r) !== i);
  if (twice) throw new Error(`${ep.id}: the reaction ${twice} is used twice — vary them`);
  const segments: Segment[] = []; let t = 0;
  const host = (line: string) => { const sec = durations[line]; if (!(sec > 0)) throw new Error(`${ep.id}: no host line ${line}`); segments.push({ kind: "host", line, start: t, sec }); t += sec; };
  if (ep.open) host(ep.open);
  ep.clips.forEach((clip, i) => {
    const d = durations[clip.file];
    if (!(d > 0) || !(clip.impact >= 0 && clip.impact <= d)) throw new Error(`${ep.id}: ${clip.file} — the impact (${clip.impact}) is not inside the clip (${d} s)`);
    const from = Math.max(0, clip.impact - (clip.pre ?? PRE)), to = Math.min(d, clip.impact + (clip.post ?? POST)), sec = Math.round((to - from) * FPS) / FPS;
    segments.push({ kind: "clip", clip, start: t, sec, from, impactAt: clip.impact - from, reactionAt: clip.impact - from - peakOf(clip.reaction) });
    t += sec;
    if (ep.verdict && ep.verdict.after === i + 1) host(ep.verdict.line);
  });
  if (ep.signOff) host(ep.signOff);
  segments.push({ kind: "tag", start: t, sec: TAG_SEC });
  return { segments, totalSec: t + TAG_SEC };
}

const FF = ["-hide_banner", "-loglevel", "error", "-y", "-threads", "4"];
const CODEC = ["-c:v", "libx264", "-profile:v", "high", "-preset", "medium", "-crf", "19", "-maxrate", "10M", "-bufsize", "20M", "-pix_fmt", "yuv420p", "-r", String(FPS), "-g", String(FPS * 2), "-c:a", "aac", "-b:a", "160k", "-ar", "48000", "-ac", "2"];
const probe = async (file: string) => { const j = JSON.parse((await run("ffprobe", ["-v", "error", "-show_streams", "-show_format", "-of", "json", file])).stdout); const v = j.streams.find((s: any) => s.codec_type === "video"); return { sec: Number(j.format.duration), w: Number(v.width), h: Number(v.height), audio: j.streams.some((s: any) => s.codec_type === "audio") }; };
/** The raw shot of a reaction or host line: the take the review kept. */
export const shotOf = (id: string) => { const dir = path.join(OUT, id), f = ["pure.mp4", "clip.mp4"].map((x) => path.join(dir, x)).find((x) => fs.existsSync(x)); if (!f) throw new Error(`${id}: not made (${dir})`); return f; };
const A = "aresample=48000,aformat=sample_fmts=fltp:channel_layouts=stereo";
const FILL = `fps=${FPS},scale=${W}:${H}:force_original_aspect_ratio=increase,crop=${W}:${H},setsar=1`;

async function main() {
  const args = parseArgs(process.argv.slice(2), []);
  const epFile = args._[0];
  if (!epFile) throw new Error("usage: reacts.ts <episode.json> [--out file.mp4]");
  const ep = JSON.parse(fs.readFileSync(epFile, "utf8")) as Episode;
  for (const c of ep.clips) { const no = rightsRefusal(c); if (no) throw new Error(no); }
  const out = typeof args.flags.out === "string" ? path.resolve(args.flags.out) : path.join(OUT, "_reacts", `reacts-${ep.id}.mp4`);
  const work = path.join(OUT, "_reacts", `.work-${ep.id}`); fs.mkdirSync(work, { recursive: true });
  const w = (f: string) => path.join(work, f);
  const durations: Record<string, number> = {}, info: Record<string, Awaited<ReturnType<typeof probe>>> = {};
  for (const c of ep.clips) { info[c.file] = await probe(path.join(OUT, c.file)); durations[c.file] = info[c.file].sec; }
  for (const id of [ep.open, ep.verdict?.line, ep.signOff].filter((x): x is string => !!x)) { info[id] = await probe(shotOf(id)); durations[id] = info[id].sec; }
  const { segments, totalSec } = plan(ep, durations);
  fs.copyFileSync(path.join(ROOT, "scripts/tutorials/assets/Anton-Regular.ttf"), w("Anton-Regular.ttf"));
  const parts: string[] = [];
  for (const [i, s] of segments.entries()) {
    const part = w(`part${String(i).padStart(2, "0")}.mp4`); parts.push(part);
    if (s.kind === "tag") {
      await renderStill(endTagHtml(false), w("end.png"), W, { size: { width: W, height: H } });
      await run("ffmpeg", [...FF, "-loop", "1", "-t", String(s.sec), "-i", w("end.png"), "-f", "lavfi", "-t", String(s.sec), "-i", "anullsrc=r=48000:cl=stereo", "-vf", `${FILL},format=yuv420p`, ...CODEC, "-t", String(s.sec), part], { nice: true });
    } else if (s.kind === "host") {
      const text = JSON.parse(fs.readFileSync(path.join(OUT, s.line, "social.json"), "utf8")).speech?.script ?? "";
      fs.writeFileSync(w(`host${i}.ass`), assFile(text ? [layoutBeat({ at: 0.05, until: s.sec, text, pos: "low", small: true })] : []));
      await run("ffmpeg", [...FF, "-i", shotOf(s.line), "-vf", `${FILL},ass=host${i}.ass:fontsdir=.,format=yuv420p`, "-af", A, ...CODEC, "-t", s.sec.toFixed(3), part], { nice: true, cwd: work });
    } else {
      const src = path.join(OUT, s.clip.file), rf = shotOf(s.clip.reaction), ri = await probe(rf), ci = info[s.clip.file];
      const cw = Math.round(ri.w * REACTION_CROP.w / 2) * 2, ch = Math.round(cw * PANEL.h / PANEL.w / 2) * 2, cx = Math.max(0, Math.round(ri.w * REACTION_CROP.cx - cw / 2)), cy = Math.max(0, Math.min(ri.h - ch, Math.round(ri.h * REACTION_CROP.cy - ch / 2)));
      const wide = ci.w / ci.h > 0.6;   // not a vertical clip: fit it whole over a blurred copy of itself
      const bg = wide ? `[0:v]fps=${FPS},split[a][b];[a]scale=${W}:${H}:force_original_aspect_ratio=increase,crop=${W}:${H},boxblur=30:4,eq=brightness=-0.12[bl];[b]scale=${W}:-2[fg];[bl][fg]overlay=0:(H-h)/2,setsar=1[bg]` : `[0:v]${FILL}[bg]`;
      const lead = Math.max(0, s.reactionAt), skip = Math.max(0, -s.reactionAt);
      const pip = `[1:v]fps=${FPS},trim=start=${skip.toFixed(3)},setpts=PTS-STARTPTS,crop=${cw}:${ch}:${cx}:${cy},scale=${PANEL.w}:${PANEL.h},tpad=start_mode=clone:start_duration=${lead.toFixed(3)}:stop_mode=clone:stop_duration=30,pad=${PANEL.w + 2 * PANEL.border}:${PANEL.h + 2 * PANEL.border}:${PANEL.border}:${PANEL.border}:white[pip]`;
      const audio = [ci.audio ? `[0:a]${A},volume=1[ca]` : `anullsrc=r=48000:cl=stereo,atrim=duration=${s.sec.toFixed(3)}[ca]`, ri.audio ? `[1:a]${A},atrim=start=${skip.toFixed(3)},asetpts=PTS-STARTPTS,adelay=${Math.round(lead * 1000)}:all=1,volume=0.9[ra];[ca][ra]amix=inputs=2:duration=first:normalize=0[a]` : `[ca]anull[a]`].join(";");
      await run("ffmpeg", [...FF, "-ss", s.from.toFixed(3), "-t", s.sec.toFixed(3), "-i", src, "-i", rf, "-filter_complex", `${bg};${pip};[bg][pip]overlay=${PANEL.x}:${PANEL.y}:shortest=0,format=yuv420p[v];${audio}`, "-map", "[v]", "-map", "[a]", ...CODEC, "-t", s.sec.toFixed(3), part], { nice: true });
    }
  }
  // Join, lay the music bed low under everything but the host lines, and bring the whole to −14 LUFS.
  const music = await track(ep.music ?? "sneaking-around");
  const duck = segments.filter((s) => s.kind === "host").map((s) => `between(t,${s.start.toFixed(2)},${(s.start + s.sec).toFixed(2)})`).join("+") || "0";
  const graph = `${parts.map((_p, i) => `[${i}:v][${i}:a]`).join("")}concat=n=${parts.length}:v=1:a=1[v][body];[${parts.length}:a]${A},atrim=start=2:duration=${totalSec.toFixed(3)},asetpts=PTS-STARTPTS,volume='if(${duck},0.05,0.16)':eval=frame,afade=t=out:st=${(totalSec - 0.8).toFixed(2)}:d=0.8[m];[body][m]amix=inputs=2:duration=first:normalize=0,loudnorm=I=${LOUDNESS.I}:TP=-1.5:LRA=11,alimiter=limit=0.84:level=false,${A}[a]`;
  fs.mkdirSync(path.dirname(out), { recursive: true });
  await run("ffmpeg", [...FF, ...parts.flatMap((p) => ["-i", p]), "-i", music, "-filter_complex", graph, "-map", "[v]", "-map", "[a]", ...CODEC, "-t", totalSec.toFixed(3), "-movflags", "+faststart", out], { nice: true });
  const loud = await measureLoudness(out);
  await run("ffmpeg", [...FF, "-i", out, "-vf", `fps=1.5,scale=180:320,tile=${Math.min(12, Math.ceil(totalSec * 1.5 / 3))}x3`, "-frames:v", "1", "-q:v", "3", out.replace(/\.mp4$/, "-review.jpg")], { nice: true });
  const credits = ep.clips.flatMap((c) => (c.rights?.kind === "cc-by" ? [c.rights.attribution] : []));
  fs.writeFileSync(out.replace(/\.mp4$/, ".json"), JSON.stringify({ id: ep.id, seconds: Math.round(totalSec * 100) / 100, lufs: loud.lufs, truePeakDb: loud.truePeakDb, segments: segments.map((s) => (s.kind === "clip" ? { clip: s.clip.file, start: s.start, sec: s.sec, reaction: s.clip.reaction, impactAt: s.start + s.impactAt, rights: s.clip.rights } : s.kind === "host" ? { host: s.line, start: s.start, sec: s.sec } : { tag: true, start: s.start, sec: s.sec })), credits }, null, 2) + "\n");
  console.log(`  ${path.relative(ROOT, out)}  ${totalSec.toFixed(2)} s  ${loud.lufs} LUFS, true peak ${loud.truePeakDb} dBTP  — LOOK at ${path.basename(out.replace(/\.mp4$/, "-review.jpg"))}`);
}
if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(import.meta.filename)) main().then(() => process.exit(0), (e) => { console.error(`\n✗ ${e instanceof Error ? e.message : e}`); process.exit(1); });
