/**
 * The sound of a gator short — made here, sample by sample, from sines and seeded noise. Nothing is
 * recorded, sampled, licensed or generated by a model: no music or audio of anyone else's can end up
 * in a clip. (The owner can lay a platform's own trending sound over it in the app.)
 *
 * A clip's track is a list of cues on the clip's clock. Deterministic: the same cues give the same samples.
 */
export const RATE = 48000;

export type Cue =
  /** A pickup at cruise: low engine drone with road noise. */
  | { type: "engine"; at: number; dur: number; gain?: number }
  /** A nail gun: a short crack over a low thump. `every` repeats it in rhythm until `until`. */
  | { type: "pop"; at: number; every?: number; until?: number; gain?: number }
  /** A bright two-note bell (a notification, an idea, "done"). */
  | { type: "ding"; at: number; gain?: number }
  /** Air: a swish for a cut or a head turn. */
  | { type: "whoosh"; at: number; dur?: number; gain?: number }
  /** Something heavy set down; a door; a full stop. */
  | { type: "thud"; at: number; gain?: number }
  /** A clock: one tick per `every` seconds until `until`. */
  | { type: "tick"; at: number; every?: number; until?: number; gain?: number }
  /** A plain four-on-the-floor bed — kick, off-beat hat — at `bpm`. Ours, and nobody's tune. */
  | { type: "beat"; at: number; dur: number; bpm?: number; gain?: number }
  /** Birds-at-dawn air: quiet filtered noise, so a still moment is not dead silent. */
  | { type: "air"; at: number; dur: number; gain?: number }
  /** A descending three-note "wah-wah" for a deflating moment. */
  | { type: "sad"; at: number; gain?: number }
  /** A tape being scrubbed backwards: the instant-replay rewind. */
  | { type: "rewind"; at: number; dur: number; gain?: number }
  /** An impact with weight: a crack on top of a deep thump (the replayed moment). */
  | { type: "hit"; at: number; gain?: number }
  /** A sub-bass drop: a low tone falling away under a slow-motion replay. */
  | { type: "bass"; at: number; dur?: number; gain?: number };

/** mulberry32: a small seeded generator — the noise is the same on every run. */
const rng = (seed: number) => () => { let t = (seed += 0x6d2b79f5); t = Math.imul(t ^ (t >>> 15), t | 1); t ^= t + Math.imul(t ^ (t >>> 7), t | 61); return ((t ^ (t >>> 14)) >>> 0) / 4294967296; };
const TAU = Math.PI * 2;

/** Mix the cues into `seconds` of mono float samples (roughly −1…1; the encoder normalises loudness). */
export function synth(cues: readonly Cue[], seconds: number): Float32Array {
  const out = new Float32Array(Math.ceil(seconds * RATE));
  const add = (at: number, dur: number, f: (t: number, i: number) => number) => {
    const a = Math.max(0, Math.round(at * RATE)), n = Math.round(dur * RATE);
    for (let i = 0; i < n && a + i < out.length; i++) out[a + i] += f(i / RATE, i);
  };
  const times = (c: { at: number; every?: number; until?: number }) => { const t: number[] = []; for (let x = c.at; x <= (c.until ?? c.at) + 1e-9; x += c.every ?? Infinity) { t.push(x); if (!c.every) break; } return t; };
  cues.forEach((c, ci) => {
    const g = c.gain ?? 1, rand = rng(1000 + ci * 7919);
    switch (c.type) {
      case "engine": {
        let lp = 0;
        add(c.at, c.dur, (t) => {
          const env = Math.min(1, t / 0.25, (c.dur - t) / 0.25), f = 62 + 3 * Math.sin(TAU * 0.35 * t);
          lp += 0.02 * ((rand() * 2 - 1) - lp);
          return g * env * (0.16 * Math.sin(TAU * f * t) + 0.09 * Math.sin(TAU * 2 * f * t + 0.6) + 0.05 * Math.sin(TAU * 3 * f * t) + 1.6 * lp);
        });
        break;
      }
      case "pop": for (const at of times(c)) { let lp = 0; add(at, 0.16, (t) => { lp += 0.35 * ((rand() * 2 - 1) - lp); return g * (0.55 * lp * Math.exp(-t * 60) + 0.5 * Math.sin(TAU * (150 - 400 * t) * t) * Math.exp(-t * 28)); }); } break;
      case "ding": add(c.at, 1.1, (t) => g * 0.3 * (Math.sin(TAU * 1318.5 * t) * Math.exp(-t * 5) + (t > 0.11 ? Math.sin(TAU * 1760 * (t - 0.11)) * Math.exp(-(t - 0.11) * 4.5) : 0))); break;
      case "whoosh": { const d = c.dur ?? 0.38; let lp = 0, hp = 0; add(c.at, d, (t) => { const x = t / d, n = rand() * 2 - 1, k = 0.04 + 0.5 * Math.sin(Math.PI * x) ** 2; lp += k * (n - lp); hp = lp - hp * 0.2; return g * 0.5 * Math.sin(Math.PI * x) ** 2 * hp; }); break; }
      case "thud": { let lp = 0; add(c.at, 0.35, (t) => { lp += 0.08 * ((rand() * 2 - 1) - lp); return g * (0.7 * Math.sin(TAU * (70 - 60 * t) * t) * Math.exp(-t * 14) + 0.8 * lp * Math.exp(-t * 30)); }); break; }
      case "tick": times(c).forEach((at, k) => add(at, 0.05, (t) => g * 0.35 * Math.sin(TAU * (k % 2 ? 1900 : 2300) * t) * Math.exp(-t * 110))); break;
      case "beat": {
        const step = 60 / (c.bpm ?? 112);
        for (let b = 0; c.at + b * step < c.at + c.dur - 0.05; b++) {
          add(c.at + b * step, 0.22, (t) => g * 0.55 * Math.sin(TAU * (48 + 90 * Math.exp(-t * 30)) * t) * Math.exp(-t * 13));
          let prev = 0; add(c.at + (b + 0.5) * step, 0.06, (t) => { const n = rand() * 2 - 1, hi = n - prev; prev = n; return g * 0.16 * hi * Math.exp(-t * 70); });
        }
        break;
      }
      case "air": { let lp = 0; add(c.at, c.dur, (t) => { lp += 0.01 * ((rand() * 2 - 1) - lp); return g * 0.9 * Math.min(1, t / 0.3, (c.dur - t) / 0.3) * lp; }); break; }
      case "rewind": { let ph = 0; add(c.at, c.dur, (t) => { const x = t / c.dur, f = 500 + 2600 * x + 300 * Math.sin(TAU * 13 * t); ph += (TAU * f) / RATE; return g * 0.22 * Math.min(1, t / 0.03, (c.dur - t) / 0.04) * (Math.sin(ph) * (0.6 + 0.4 * Math.sin(TAU * 31 * t)) + 0.5 * (rand() * 2 - 1) * (0.5 + 0.5 * Math.sin(TAU * 17 * t))); }); break; }
      case "hit": { let lp = 0; add(c.at, 0.5, (t) => { lp += 0.25 * ((rand() * 2 - 1) - lp); return g * (0.9 * Math.sin(TAU * (55 + 120 * Math.exp(-t * 26)) * t) * Math.exp(-t * 9) + 0.7 * lp * Math.exp(-t * 45) + 0.25 * (rand() * 2 - 1) * Math.exp(-t * 160)); }); break; }
      case "bass": { const d = c.dur ?? 1.0; let ph = 0; add(c.at, d, (t) => { const f = 34 + 62 * Math.exp(-t * 3.2); ph += (TAU * f) / RATE; return g * 0.8 * Math.min(1, t / 0.01, (d - t) / 0.15) * (Math.sin(ph) + 0.25 * Math.sin(2 * ph)); }); break; }
      case "sad": [392, 370, 330].forEach((f, k) => add(c.at + k * 0.34, k === 2 ? 0.8 : 0.32, (t) => { const d = k === 2 ? 0.8 : 0.32, w = f * (1 - (k === 2 ? 0.06 * t / d : 0)); return g * 0.22 * Math.min(1, t / 0.02, (d - t) / 0.06) * (Math.sin(TAU * w * t) + 0.4 * Math.sin(TAU * 2 * w * t) + 0.2 * Math.sin(TAU * 3 * w * t)) * (1 + 0.08 * Math.sin(TAU * 6 * t)); })); break;
    }
  });
  return out;
}

/** Float samples → 16-bit PCM, peak brought to −3 dBFS (the encoder's loudnorm sets the final level). */
export function toPcm(samples: Float32Array): Int16Array {
  let peak = 0;
  for (const s of samples) peak = Math.max(peak, Math.abs(s));
  const k = peak > 0 ? 0.708 / peak : 0, out = new Int16Array(samples.length);
  for (let i = 0; i < samples.length; i++) out[i] = Math.round(samples[i] * k * 32767);
  return out;
}
