/**
 * The styles of the gator stream's experiment (docs/gator/STYLES.md is written from this list): the owner's
 * plan is to try many distinct styles, measure, and double down on what works (scoreboard.ts).
 */
export type Style = { id: number; name: string; definition: string; recipe: string; model: string; creditsPerClip: number; example: string; linkedin: boolean; clips: string[] };
const K3 = "Kling 3.0 Standard image-to-video, own sound (2.016 credits per second)", K25 = "Kling 2.5 Turbo Standard image-to-video, 5 s (3.36 credits a shot), sound synthesised";
export const STYLES: Style[] = [
  { id: 1, name: "Selfie vlog goes wrong — live gator", definition: "The photoreal gator films himself, talking fast and cocky; the disaster happens mid-sentence; he never stops talking.", recipe: "Selfie still from the live model sheet → one 9–10 s take with the dialogue and the fixed voice description in the prompt; two takes, keep the better; pure + subtitled.", model: K3, creditsPerClip: 42, example: "“Day one. New deck. Solid.” — the deck goes.", linkedin: false, clips: ["selfie-deck", "selfie-roof", "selfie-leak"] },
  { id: 2, name: "Selfie vlog goes wrong — cartoon mascot", definition: "The same format with the brand mascot, drawn.", recipe: "Selfie still from the mascot references → one take as style 1. Watch his sunglasses: the talking model tends to make them see-through.", model: K3, creditsPerClip: 22, example: "The mascot on the two-day job: “Two days, he says—” (the tarp takes him).", linkedin: false, clips: [] },
  { id: 3, name: "One-shot found footage — the impossible skill", definition: "A phone clip of the live gator doing a trade job absurdly well; nothing burned in.", recipe: "Live still → one 8–10 s take, natural sound; pure only.", model: K3, creditsPerClip: 19, example: "He walks the ridge with a bundle of shingles on his shoulder like he has done it for thirty years.", linkedin: true, clips: [] },
  { id: 4, name: "One-shot found footage — the fail he walks away from", definition: "A phone clip of a clean slapstick fail; he is fine and it shows.", recipe: "Live still → one 8–10 s take; pure; optional replay edit.", model: K3, creditsPerClip: 19, example: "The wheelbarrow, the ramp, the flat tyre.", linkedin: false, clips: [] },
  { id: 5, name: "CCTV / doorbell / dashcam", definition: "Fixed high camera, timestamp and camera name in the corner; something happens in frame.", recipe: "High-angle still → one take; the overlay (CAM 03, a clock) is drawn in the edit, never by the model.", model: K3, creditsPerClip: 19, example: "CAM 03: he rides the sliding ladder down like a surfboard and lands on his feet.", linkedin: false, clips: [] },
  { id: 6, name: "Cartoon slapstick with a meme caption", definition: "The mascot, two shots, big caption, a 1.5 s end tag — the pilot's look.", recipe: "Stills from the mascot references → Kling 2.5 shots → captions, synthesised foley.", model: K25, creditsPerClip: 10, example: "“While you're here…”", linkedin: true, clips: ["while-youre-here", "two-day-job", "shingle-rhythm"] },
  { id: 7, name: "Screaming-goat smash cut", definition: "A contractor cliché line, then a hard cut to OUR goat screaming.", recipe: "Gator shot (the line) + our own photoreal goat, one 3 s take with its own scream; the scream is the model's, never the meme's audio.", model: K3, creditsPerClip: 24, example: "“My cousin can do it cheaper.” — goat.", linkedin: false, clips: [] },
  { id: 8, name: "POV: the coworker's phone", definition: "“Bro look at the new guy” — handheld, a coworker filming the gator at work.", recipe: "Over-the-shoulder live still → one take; a one-line caption in the phone-caption style in the captioned variant.", model: K3, creditsPerClip: 19, example: "New guy's first day: the nail gun, a whole row, perfectly straight, in two seconds.", linkedin: false, clips: [] },
  { id: 9, name: "Satisfying craft loop", definition: "No joke: perfect work, hypnotic, loops.", recipe: "Live or cartoon still → one take, natural sound; cut to loop.", model: K3, creditsPerClip: 19, example: "Chalk line: one snap, dead straight.", linkedin: true, clips: [] },
  { id: 10, name: "Hot take to camera", definition: "The gator, one trade cliché, one dry line.", recipe: "Live still, three-quarter, coffee → one 5 s take with the line; subtitled.", model: K3, creditsPerClip: 12, example: "“Measure once, cut twice. That's the trade.”", linkedin: true, clips: [] },
  { id: 11, name: "Expectation vs reality", definition: "Two shots, two words: the estimate / the change orders; day 1 / day 9.", recipe: "Two stills → two shots, split by a hard cut with a label on each.", model: K25, creditsPerClip: 10, example: "The quote. / The house.", linkedin: true, clips: [] },
  { id: 12, name: "Recurring-cast sketch", definition: "The gator with the cast: the rooster apprentice, the possum inspector, the beaver framer, the raccoons.", recipe: "Cast still from text → one take with dialogue; subtitled.", model: K3, creditsPerClip: 22, example: "The rooster comes back with the board stretcher.", linkedin: false, clips: [] },
  { id: 13, name: "Viral moment + gator button", definition: "A cast member stalls with total confidence right up to the drop; then the gator's dry line.", recipe: "Cast scene 10 s + gator button 5 s, both with their own sound; subtitles from the heard words; 0.8 s tag.", model: K3, creditsPerClip: 33, example: "“Lemme tell you somethin' about ladders—” / “Tie off.”", linkedin: false, clips: ["moment-ladders", "moment-video"] },
  { id: 14, name: "The fall + instant replay", definition: "The viewer sees the trap first; he walks into it; the impact is replayed four ways with music.", recipe: "One static shot, 10 s → replay.ts (rewind, punch-in, mirror + freeze, slow motion) with CC0 music and a no-music export.", model: K3, creditsPerClip: 22, example: "The bucket was full of concrete.", linkedin: false, clips: ["fall-bucket", "fall-wetfloor"] },
  { id: 15, name: "Tiny gator, giant opponent", definition: "A cat-sized gator in a tiny hard hat, an enormous invented man, one slap, a timber-fall, a deadpan look.", recipe: "Still from text → one 10 s take; pure + replay edit. The man is invented, unbranded, and shown fine at the end.", model: K3, creditsPerClip: 22, example: "Lunch break. The big guy said go ahead.", linkedin: false, clips: ["slap-arena", "slap-jobsite"] },
];
