import { AppPage, Section, Notice, appTable, appTableCards } from "@/components/app-ui";
import { GoogleSectionHeader, GooglePill } from "@/components/google";
import { Search } from 'lucide-react';
import { useState, useEffect } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { apiRequest, apiErrorMessage } from '@/lib/queryClient';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Badge } from '@/components/ui/badge';
import { useUrlParam } from '@/hooks/use-url-param';
import { PlanRequired, planRequiredFrom, pollUnlessPlanRequired } from '@/components/plan-required';
type Tab='accounts'|'invitations'|'plans'|'jobs'|'findings';
const labels:Record<Tab,string>={accounts:'Client accounts',invitations:'Access invitations',plans:'Protection previews',jobs:'Queue',findings:'Health audit'};
const defaults=['jobs','careers','salary','training','DIY','tutorial','free','cheap'];
function Pager({page,total,setPage}:{page:number;total:number;setPage:(n:number)=>void}) {return <div className="flex flex-wrap items-center gap-3 text-sm"><Button variant="outline" disabled={page<=1} onClick={()=>setPage(page-1)}>Previous</Button><span>Page {page} · {total} results</span><Button variant="outline" disabled={page*25>=total} onClick={()=>setPage(page+1)}>Next</Button></div>;}
export default function AdsManagerPage() {
  const qc=useQueryClient();
  // The section lives in the URL (?tab=jobs) so a reload or a shared link keeps it.
  const [tabParam,setTabParam]=useUrlParam('tab');
  const tab:Tab=(Object.keys(labels) as string[]).includes(tabParam??'')?tabParam as Tab:'accounts';
  const setTab=(t:Tab)=>setTabParam(t==='accounts'?null:t);
  const [q,setQ]=useState(''),[filter,setFilter]=useState(''),[lsa,setLsa]=useState(''),[page,setPage]=useState(1);
  const [selected,setSelected]=useState<string[]>([]),[all,setAll]=useState(false),[message,setMessage]=useState(''),[manager,setManager]=useState('');
  const [kind,setKind]=useState('presence'),[keywords,setKeywords]=useState(defaults.join('\n')),[listName,setListName]=useState('Contractor starter negatives'),[placements,setPlacements]=useState('');
  const [schedule,setSchedule]=useState('MONDAY,09:00,17:00\nTUESDAY,09:00,17:00\nWEDNESDAY,09:00,17:00\nTHURSDAY,09:00,17:00\nFRIDAY,09:00,17:00'),[campaignIds,setCampaignIds]=useState('');
  const [replaceList,setReplaceList]=useState(false);
  const [inviteText,setInviteText]=useState(''),[invitePreview,setInvitePreview]=useState(false),[reviewed,setReviewed]=useState(false),[mapping,setMapping]=useState('');
  const [operationQ,setOperationQ]=useState('');
  useEffect(()=>setReviewed(false),[selected]);
  const [previewId,setPreviewId]=useState<string|null>(null),[previewPage,setPreviewPage]=useState(1);
  const [domainQ,setDomainQ]=useState(''),[domainPage,setDomainPage]=useState(1),[campaignCustomer,setCampaignCustomer]=useState(''),[campaignQ,setCampaignQ]=useState(''),[campaignPage,setCampaignPage]=useState(1);
  const status=useQuery<any>({queryKey:['/api/ads/status'],refetchInterval:pollUnlessPlanRequired(10000)});
  const params=new URLSearchParams({page:String(page),q,status:filter,lsa});
  const data=useQuery<any>({queryKey:['ads-list',tab,params.toString()],queryFn:async()=> (await apiRequest('GET',`/api/ads/${tab}?${params}`)).json(),refetchInterval:pollUnlessPlanRequired(5000)});
  const detail=useQuery<any>({queryKey:['ads-preview',previewId,previewPage,operationQ],enabled:!!previewId,queryFn:async()=>(await apiRequest('GET',`/api/ads/plans/${previewId}?page=${previewPage}&limit=25&q=${encodeURIComponent(operationQ)}`)).json()});
  const domains=useQuery<any>({queryKey:['ads-domains',domainQ,domainPage],enabled:tab==='accounts',queryFn:async()=>(await apiRequest('GET',`/api/ads/domains?q=${encodeURIComponent(domainQ)}&page=${domainPage}`)).json()});
  const campaigns=useQuery<any>({queryKey:['ads-campaigns',campaignCustomer,campaignQ,campaignPage],enabled:!!campaignCustomer,queryFn:async()=>(await apiRequest('GET',`/api/ads/accounts/${campaignCustomer}/campaigns?q=${encodeURIComponent(campaignQ)}&page=${campaignPage}`)).json()});
  const action=useMutation({mutationFn:async({path,body}:{path:string;body:unknown})=>(await apiRequest('POST',`/api/ads${path}`,body)).json(),onSuccess:r=>{setMessage(r.message||`Queued ${r.queued??1}. Review progress in Queue.`);setSelected([]);setReviewed(false);setInvitePreview(false);qc.invalidateQueries({queryKey:['ads-list']});qc.invalidateQueries({queryKey:['/api/ads/status']});if(r.url)window.location.assign(r.url);},onError:e=>setMessage(apiErrorMessage(e))});
  const run=(path:string,body:unknown)=>action.mutate({path,body});
  const switchTab=(t:Tab)=>{setTab(t);setPage(1);setQ('');setFilter('');setLsa('');setSelected([]);setAll(false);setReviewed(false);};
  const select=(id:string)=>{setReviewed(false);setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);};
  const selection=all?{filter:{q,lsa}}:{ids:selected};
  const lines=(s:string)=>s.split('\n').map(s=>s.trim()).filter(Boolean);
  const previewProtection=()=>{
    try {
      let v:any={kind};if(kind!=='placement'&&campaignIds.trim())v.campaignIds=campaignIds.split(',').map(s=>s.trim());
      if(kind==='negative')v={...v,name:listName,keywords:lines(keywords),mode:replaceList?'replace':'add'};
      if(kind==='placement')v.urls=lines(placements);
      if(kind==='schedule')v.slots=lines(schedule).map(line=>{const [day,start,end]=line.split(',').map(s=>s.trim());if(!/^(?:[01]\d|2[0-4]):(?:00|15|30|45)$/.test(start)||!/^(?:[01]\d|2[0-4]):(?:00|15|30|45)$/.test(end))throw new Error('Invalid time');const [sh,sm]=start.split(':').map(Number),[eh,em]=end.split(':').map(Number);return {dayOfWeek:day,startHour:sh,startMinute:['ZERO','FIFTEEN','THIRTY','FORTY_FIVE'][sm/15],endHour:eh,endMinute:['ZERO','FIFTEEN','THIRTY','FORTY_FIVE'][em/15]};});
      run('/bulk',{selection,kind:'preview',action:v,requestId:crypto.randomUUID()});
    }catch{setMessage('Check schedule format: DAY,HH:MM,HH:MM with 15-minute boundaries.');}
  };
  const enabled=status.data?.connected&&status.data?.grant?.verified;
  const rows:any[]=data.data?.items||[];
  const planGate=[status.error,data.error].find(e=>planRequiredFrom(e));
  // Google's page format (owner, 2026-10-07): a quiet header, pill tabs and actions, hairline cards.
  const header=<GoogleSectionHeader as="h1" title="Agency Ads & LSA manager" description="Manage client access and review ad protections before applying them." flush actions={planGate ? null : status.data?.connected ? <GooglePill variant="solid" label="Discover clients" disabled={action.isPending} onClick={()=>run('/sync',{kind:'discover'})} /> : <GooglePill variant="solid" label="Connect MCC with Google" disabled={!status.data?.configured||action.isPending} onClick={()=>run('/connect',{managerId:manager||status.data?.defaultManagerId})} />} />;
  if(planGate)return <AppPage className="[&_select]:max-w-full [&_select]:min-h-10 [&_button]:min-h-10 [&_h3]:text-base [&_p]:text-sm">{header}<PlanRequired module="adsManager" error={planGate} className="max-w-3xl"/></AppPage>;
  return <AppPage className="[&_select]:max-w-full [&_select]:min-h-10 [&_button]:min-h-10 [&_h3]:text-base [&_p]:text-sm">
    {header}
    {message&&<p role="status" className="rounded border p-3">{message}</p>}
    {(status.error||data.error)&&<p role="alert">{apiErrorMessage(status.error||data.error)}</p>}
    {new URLSearchParams(window.location.search).get('connect')==='failed'&&<p role="alert">Google connection failed. Allow Ads access and try again.</p>}
    <Section flush id="agency-connection"><CardHeader><CardTitle className="g-card__title g-card__title--md">Agency connection</CardTitle></CardHeader><CardContent className="space-y-3">
      {!status.data?.configured&&<p>Google Ads setup is not configured. Ask the owner to enable the connection.</p>}
      <p>{status.data?.connected?`MCC ${status.data.grant.manager_id} · ${status.data.grant.verified?'Verified':'Verification queued'}`:'No connected MCC'}{status.data?.grant?.reconnect_required?' · Reconnect required':''}</p>
      {!status.data?.workerEnabled&&<Notice tone="warning">The Ads worker is off; jobs will stay queued.</Notice>}
      <div className="flex flex-wrap gap-2"><Input className="w-full sm:max-w-xs" aria-label="Manager customer ID" placeholder={status.data?.defaultManagerId||'123-456-7890'} value={manager} onChange={e=>setManager(e.target.value)}/>
        {status.data?.connected&&<><Button variant="outline" disabled={action.isPending||!enabled} onClick={()=>run('/sync',{kind:'poll'})}>Poll invitations</Button><Button variant="outline" disabled={action.isPending} onClick={()=>{if(window.confirm('Remove local MCC credentials and cancel queued work? Revoke Google access separately in your Google Account.'))run('/disconnect',{confirm:true});}}>Disconnect MCC</Button></>}
      </div>
    </CardContent></Section>
    <div className="-mx-4 overflow-x-auto px-4 scrollbar-none sm:mx-0 sm:px-0" role="tablist" aria-label="Ads manager sections"><div className="flex w-max gap-2">{(Object.keys(labels) as Tab[]).map(t=><GooglePill key={t} label={labels[t]} selected={tab===t} ariaPressed={tab===t} onClick={()=>switchTab(t)} />)}</div></div>
    <div className="flex flex-wrap gap-3"><div className="g-search w-full sm:max-w-sm" role="search"><Search aria-hidden="true" /><input type="search" aria-label="Search accounts or records" placeholder={tab==='findings'?'Search audit findings':'Search name or customer ID'} value={q} onChange={e=>{setQ(e.target.value);setPage(1);setAll(false);setSelected([]);}}/></div><details className="w-full sm:w-auto"><summary className="g-pill cursor-pointer list-none [&::-webkit-details-marker]:hidden">Filters</summary><div className="flex flex-col sm:flex-row gap-3 py-3">
      <label>Filter <select className="border rounded p-2 bg-background" aria-label="Status filter" value={filter} onChange={e=>{setFilter(e.target.value);setPage(1);setSelected([]);setAll(false);}}><option value="">All</option>{(tab==='accounts'?['ENABLED','SUSPENDED','CANCELED','UNLINKED']:tab==='findings'?['warning','unknown','info']:tab==='invitations'?['queued','pending','accepted','rejected','cancelled','unknown','failed']:tab==='plans'?['preview','queued','applying','applied','reversed','failed','unknown','expired','no_change']:['queued','running','done','failed','unknown','cancelled']).map(s=><option key={s}>{s}</option>)}</select></label>
      {tab==='accounts'&&<label>LSA <select className="border rounded p-2 bg-background" aria-label="LSA filter" value={lsa} onChange={e=>{setLsa(e.target.value);setPage(1);setAll(false);setSelected([]);}}><option value="">All accounts</option><option value="true">LSA identified</option><option value="false">No LSA campaigns found</option><option value="unknown">Not checked</option></select></label>}
    </div></details></div>
    <div className="flex flex-wrap gap-3 items-center">
      {['accounts','plans','invitations'].includes(tab)&&<><Button variant="outline" onClick={()=>setSelected([...new Set([...selected,...rows.filter(r=>tab!=='accounts'||(!r.manager&&r.status==='ENABLED')).map(r=>r.customer_id&&tab==='accounts'?r.customer_id:r.id)])])}>Select this page</Button><Button variant="ghost" onClick={()=>{setSelected([]);setAll(false);}}>Clear selection</Button><span>{selected.length} selected</span></>}
      {tab==='accounts'&&<><label className="flex gap-2"><input type="checkbox" checked={all} onChange={e=>{setAll(e.target.checked);setSelected([]);}}/>All active clients matching search / LSA filter (max 1,000)</label><Button variant="outline" disabled={!enabled||(!all&&!selected.length)||action.isPending} onClick={()=>run('/bulk',{selection,kind:'audit',requestId:crypto.randomUUID()})}>Queue health audit</Button></>}
    </div>
    {data.isLoading?<p>Loading…</p>:!rows.length?<p>No records. Connect and discover clients, or adjust the filter.</p>:<div className="overflow-x-auto border rounded"><table className={appTable.table}><thead className={appTableCards.thead}><tr className={appTableCards.tr + " border-b text-left"}><th className="p-3">Select / account</th><th>Details</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(r=>{const id=tab==='accounts'?r.customer_id:String(r.id);return <tr key={id} className={appTableCards.tr + " border-b"} data-testid="ads-row"><td className={appTableCards.td + " min-w-0 break-words"}><span className="mr-2 text-xs font-medium text-muted-foreground sm:hidden">Select / account: </span>{['accounts','plans','invitations'].includes(tab)&&<input aria-label={`Select ${id}`} disabled={tab==='accounts'&&(r.manager||r.status!=='ENABLED')} type="checkbox" checked={selected.includes(id)} onChange={()=>select(id)} className="mr-2"/>}{r.customer_id||'Agency'}{tab==='accounts'&&<p className="font-medium">{r.name||'Name unavailable'}</p>}</td><td className={appTableCards.td + " min-w-0 break-words"}><span className="mr-2 text-xs font-medium text-muted-foreground sm:hidden">Details: </span>{tab==='accounts'?<>{r.manager?'Manager':r.lsa===null?'LSA not checked':r.lsa?'LSA account':'No LSA campaigns found'}<p>{r.currency||'Currency unknown'} · {r.timezone||'Timezone unknown'}</p><p>Click Guard domain ID: {r.domain_id||'Not mapped'}</p><p>{r.synced_at?`Checked ${new Date(r.synced_at).toLocaleString()}`:'Never audited'}</p></>:tab==='findings'?<><strong>{r.title}</strong><p>{r.detail}</p></>:<>{r.kind||r.email}{r.email_status&&<p>Email: {r.email_status}</p>}<p className="text-muted-foreground break-all">{r.id}</p></>}{r.error&&<p role="alert" className="text-destructive">{r.error}</p>}</td><td className={appTableCards.td}><span className="mr-2 text-xs font-medium text-muted-foreground sm:hidden">Status: </span><Badge variant="outline">{r.status||r.severity}</Badge></td><td className={appTableCards.td + " min-w-0 break-words"}><span className="mr-2 text-xs font-medium text-muted-foreground sm:hidden">Actions: </span>{tab==='plans'&&<Button size="sm" variant="outline" onClick={()=>{setPreviewId(r.id);setPreviewPage(1);setOperationQ('');}}>Review preview</Button>}{tab==='accounts'&&!r.manager&&<Button size="sm" variant="outline" onClick={()=>{setCampaignCustomer(r.customer_id);setCampaignPage(1);setCampaignQ('');}}>Campaigns</Button>}{tab==='findings'&&r.fix&&(r.fix.url?<a className="underline text-primary" href={r.fix.url} target={r.fix.url.startsWith('https:')?'_blank':undefined} rel="noreferrer">{r.fix.label}</a>:<Button size="sm" variant="outline" onClick={()=>{switchTab('accounts');setSelected([r.customer_id]);setKind(r.fix.action.kind);setMessage('Review protection settings below, then queue a preview.');}}>{r.fix.label}</Button>)}</td></tr>;})}</tbody></table></div>}
    <Pager page={page} total={data.data?.total||0} setPage={setPage}/>
    {tab==='accounts'&&<>
      <details className="space-y-3"><summary className="cursor-pointer py-3 text-sm font-medium">Advanced · Bulk protections and domain mapping</summary><Section flush><CardHeader><CardTitle className="g-card__title g-card__title--md">Bulk protection preview</CardTitle></CardHeader><CardContent className="space-y-3">
        <p>Applies to selected clients. Each account gets its own preview. No Google settings change until you confirm those previews.</p>
        <label className="block">Protection <select aria-label="Protection" className="border rounded p-2 bg-background" value={kind} onChange={e=>setKind(e.target.value)}><option value="presence">Presence-only location targeting</option><option value="ip">Click Guard IP exclusions (rotate oldest)</option><option value="negative">Shared negative keywords</option><option value="placement">Account-wide placement exclusions (Display / PMax)</option><option value="schedule">Ad schedule</option></select></label>
        {kind!=='placement'&&<Input aria-label="Campaign IDs" placeholder="Optional campaign IDs, comma separated; otherwise all supported (max 100/client)" value={campaignIds} onChange={e=>setCampaignIds(e.target.value)}/>}
        {kind==='negative'&&<><Input aria-label="Negative list name" value={listName} onChange={e=>setListName(e.target.value)}/><Textarea aria-label="Negative keywords" value={keywords} onChange={e=>setKeywords(e.target.value)}/><label className="flex gap-2"><input type="checkbox" checked={replaceList} onChange={e=>setReplaceList(e.target.checked)}/>Replace the existing list contents (preview every removal)</label><p>Editable starter list, one phrase per line. “free” can exclude “free estimate”; review client intent. Entries are added to the named shared list, including its existing attached campaigns.</p></>}
        {kind==='placement'&&<><Textarea aria-label="Excluded placements" placeholder="example.com — one domain/path per line" value={placements} onChange={e=>setPlacements(e.target.value)}/><p>Account-wide: affects all supported campaigns in each selected account.</p></>}
        {kind==='schedule'&&<><Textarea aria-label="Ad schedule" value={schedule} onChange={e=>setSchedule(e.target.value)}/><p>DAY,HH:MM,HH:MM · 15-minute boundaries, max six intervals per day. Replaces existing schedules in each account’s timezone. Omitted days do not run.</p></>}
        {kind==='ip'&&<p>Uses the newest 500 flagged IPs from each client’s mapped domain. Rotates the oldest observed exclusions to stay within Google’s 500/campaign limit. Preview lists every addition and removal.</p>}
        <Button variant="outline" disabled={!enabled||action.isPending||(!all&&!selected.length)} onClick={previewProtection}>Queue protection previews</Button>
        <p className="text-muted-foreground text-sm">Alpine playbook: awaiting owner-approved steps. These are generic opt-in protections.</p>
      </CardContent></Section>
      <Section flush><CardHeader><CardTitle className="g-card__title g-card__title--md">Click Guard mapping</CardTitle></CardHeader><CardContent className="space-y-3"><p>Map each client to its own domain before using IP exclusions. Bulk format: customer ID,domain ID (one pair per line).</p><Input aria-label="Search Click Guard domains" value={domainQ} onChange={e=>{setDomainQ(e.target.value);setDomainPage(1);}}/>{domains.error&&<p role="alert">{apiErrorMessage(domains.error)}</p>}<p>{(domains.data?.items||[]).map((d:any)=>`${d.id}: ${d.domain}`).join(' · ')||'No matching Click Guard domains.'}</p><Pager page={domainPage} total={domains.data?.total||0} setPage={setDomainPage}/><Textarea aria-label="Client domain mappings" placeholder="1234567890,42" value={mapping} onChange={e=>setMapping(e.target.value)}/><Button variant="outline" disabled={action.isPending||!mapping.trim()} onClick={()=>{const parsed=lines(mapping).map(s=>s.split(',').map(s=>s.trim()));if(parsed.some(p=>p.length!==2||(p[1]&&!/^\d+$/.test(p[1])))){setMessage('Use customer ID,domain ID on each line. Leave domain ID blank to unmap.');return;}run('/domain-mappings',{mappings:parsed.map(([customerId,id])=>({customerId,domainId:id?Number(id):null}))});}}>Save domain mappings</Button></CardContent></Section>
    </details></>}
    {tab==='invitations'&&<Section flush><CardHeader><CardTitle className="g-card__title g-card__title--md">Request client account access</CardTitle></CardHeader><CardContent className="space-y-3"><p>One customer ID,email pair per line, up to 1,000 clients. Confirmation queues a PENDING Google manager invitation and a ConstructHUB instruction email to each address.</p><Textarea aria-label="Client invitation list" placeholder="123-456-7890,client@example.com" value={inviteText} onChange={e=>{setInviteText(e.target.value);setInvitePreview(false);}}/><Button variant="outline" disabled={!enabled||!inviteText.trim()} onClick={()=>setInvitePreview(true)}>Preview invitations</Button>
      {invitePreview&&<section className="border p-4 space-y-3" aria-label="Invitation preview"><strong>Review {lines(inviteText).length} invitation(s) from MCC {status.data?.grant?.manager_id}</strong><p>The recipients above will receive: “Your agency has requested Google Ads manager access. Sign in as a client account administrator, open Admin → Access and security → Managers, review the MCC ID, then accept only if this is your agency.” Google’s own notification goes to account administrators; check inbox and spam. This email does not itself grant access.</p><p>Clients can decline. A pending invitation can be cancelled below.</p><Button variant="outline" disabled={action.isPending} onClick={()=>run('/invitations',{confirm:true,requestId:crypto.randomUUID(),clients:lines(inviteText).map(line=>{const [customerId,email]=line.split(',').map(s=>s.trim());return {customerId,email};})})}>Confirm invitations and emails</Button></section>}
      <Button variant="outline" disabled={action.isPending||!selected.length} onClick={()=>{if(window.confirm(`Cancel ${selected.length} selected pending Google invitations?`))run('/invitations/cancel',{ids:selected,confirm:true});}}>Cancel selected pending invitations</Button>
    </CardContent></Section>}
    {tab==='plans'&&<section className="border rounded p-4 space-y-3"><p>Review each selected preview, including removals and warnings. Expired previews require a fresh snapshot. Google state is checked again before publishing.</p><label className="flex gap-2"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I reviewed the selected previews and authorize these Google Ads changes.</label><div className="flex gap-3"><Button variant="outline" disabled={!enabled||!reviewed||!selected.length||action.isPending} onClick={()=>run('/plans/confirm',{ids:selected,confirm:true})}>Confirm selected previews</Button><Button variant="outline" disabled={!enabled||!selected.length||action.isPending} onClick={()=>run('/plans/undo-preview',{ids:selected})}>Preview reversal of selected applied changes</Button></div><p>Unknown outcome: reconcile in Google Ads before creating another change. Reversal stops if the account has changed.</p></section>}
    <Dialog open={!!previewId} onOpenChange={open=>{if(!open)setPreviewId(null);}}><DialogContent className="max-w-3xl max-h-[85vh] overflow-y-auto"><DialogHeader><DialogTitle>Protection change preview</DialogTitle></DialogHeader>{detail.error?<p role="alert">{apiErrorMessage(detail.error)}</p>:detail.data?<><p>{detail.data.customer_id} · {detail.data.kind} · {detail.data.status}</p>{detail.data.summary.map((s:string,i:number)=><p key={i}>{s}</p>)}{detail.data.warnings.map((s:string,i:number)=><p key={i} className="text-amber-700">{s}</p>)}<p>{detail.data.total} operations · expires {new Date(detail.data.expires_at).toLocaleString()}</p><Input aria-label="Search preview operations" placeholder="Search IP, keyword, resource or setting" value={operationQ} onChange={e=>{setOperationQ(e.target.value);setPreviewPage(1);}}/><pre className="text-xs whitespace-pre-wrap break-all bg-muted rounded p-3">{JSON.stringify(detail.data.operations,null,2)}</pre><Pager page={previewPage} total={detail.data.total} setPage={setPreviewPage}/><Button variant="outline" onClick={()=>{setSelected(s=>[...new Set([...s,previewId!])]);setPreviewId(null);}}>Select this preview for bulk confirmation</Button></>:<p>Loading preview…</p>}</DialogContent></Dialog>
    <Dialog open={!!campaignCustomer} onOpenChange={open=>{if(!open)setCampaignCustomer('');}}><DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto"><DialogHeader><DialogTitle>Campaigns · {campaignCustomer}</DialogTitle></DialogHeader><Input aria-label="Search campaigns" value={campaignQ} onChange={e=>{setCampaignQ(e.target.value);setCampaignPage(1);}}/>{campaigns.error&&<p role="alert">{apiErrorMessage(campaigns.error)}</p>}{(campaigns.data?.items||[]).map((c:any)=><p key={c.id}>{c.id} · {c.name} · {c.advertisingChannelType}</p>)}<Pager page={campaignPage} total={campaigns.data?.total||0} setPage={setCampaignPage}/><p>Use these IDs in the protection form to narrow the campaign scope. Queue a health audit to refresh campaigns.</p></DialogContent></Dialog>
  </AppPage>;
}
