import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { apiRequest, apiErrorMessage, queryClient } from '@/lib/queryClient';
import { AgencyWorkspace, Pager, selectClass, useAgencyFilter } from '@/components/agency-workspace';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
export default function AgencyPage(){
  const [tab,setTab]=useState('locations'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[offset,setOffset]=useState(0),[search,setSearch]=useState('');
  const [name,setName]=useState(''),[email,setEmail]=useState(''),[notes,setNotes]=useState(''),[tags,setTags]=useState(''),[folder,setFolder]=useState(''),[editId,setEditId]=useState<number|null>(null);
  const [role,setRole]=useState('viewer'),[allClients,setAllClients]=useState(false),[clientIds,setClientIds]=useState('');
  const [client,setClient]=useState(''),[subject,setSubject]=useState(''),[business,setBusiness]=useState(''),[address,setAddress]=useState(''),[placeId,setPlaceId]=useState('');
  const [agencyName,setAgencyName]=useState(''),[acceptAll,setAcceptAll]=useState(false);
  const {data:me}=useQuery<any>({queryKey:['/api/agency/me']});
  const admin=me&&['owner','admin'].includes(me.role),write=me&&me.role!=='viewer';
  const {data:google}=useQuery<any>({queryKey:['/api/agency/google'],enabled:!!me});
  const {data:list,refetch}=useQuery<any>({queryKey:['/api/agency',tab,search,offset],enabled:tab!=='locations'&&tab!=='settings',queryFn:()=>apiRequest('GET',`/api/agency/${tab}?q=${encodeURIComponent(search)}&offset=${offset}`).then(r=>r.json()),refetchInterval:tab==='jobs'||tab==='onboarding'?10000:false});
  const {data:clients}=useQuery<any>({queryKey:[`/api/agency/clients?q=${encodeURIComponent(search)}`]});
  async function run(path:string,body?:any,method='POST'){setBusy(true);setMessage('');try{const r=await apiRequest(method,'/api/agency'+path,body);await r.json();setMessage('Saved. Queued work appears in Jobs or Onboarding.');await refetch();await queryClient.invalidateQueries({queryKey:['/api/agency/me']});}catch(e){setMessage(apiErrorMessage(e));}finally{setBusy(false);}}
  return <main className="p-6 max-w-7xl mx-auto space-y-5"><h1 className="text-3xl font-bold">Agency workspace</h1>
    <div className="flex gap-3 items-center"><label>Workspace <select className={selectClass} aria-label="Workspace" value={me?.owner||''} onChange={async e=>{await run('/workspace',{owner:Number(e.target.value)});queryClient.clear();window.location.reload();}}><option value={me?.actor}>My workspace</option>{me?.workspaces?.filter((w:any)=>w.user_id!==me.actor).map((w:any)=><option value={w.user_id} key={w.user_id}>{w.name}</option>)}</select></label><span>{me?.role}</span></div>
    <nav className="flex gap-2 flex-wrap">{['locations','clients',...(admin?['team']:[]),'onboarding','jobs',...(me?.role==='owner'?['settings']:[])].map(t=><Button key={t} variant={t===tab?'default':'outline'} onClick={()=>{setTab(t);setOffset(0);}}>{t[0].toUpperCase()+t.slice(1)}</Button>)}</nav>
    {message&&<p role="status">{message}</p>}
    {tab==='locations'?<AgencyWorkspace/>:<>
      {tab!=='settings'&&<Input aria-label="Search agency records" placeholder="Search records or clients…" value={search} onChange={e=>{setSearch(e.target.value);setOffset(0);}}/>}
      {tab==='settings'&&<fieldset disabled={busy} className="space-y-3"><legend>Agency settings</legend><Input aria-label="Agency name" placeholder={me?.workspace?.name||'Agency name'} value={agencyName} onChange={e=>setAgencyName(e.target.value)}/><label className="flex gap-2"><input type="checkbox" checked={acceptAll} onChange={e=>setAcceptAll(e.target.checked)}/>Auto-accept all location invitations for connected agency Google accounts</label><p>Unmatched invitations stay unassigned; they are never assigned to a guessed client. Current setting: {me?.workspace?.auto_accept_all?'enabled':'disabled'}.</p><Button onClick={()=>run('/settings',{name:agencyName||me?.workspace?.name||'Agency',autoAcceptAll:acceptAll},'PUT')}>Save agency settings</Button><a className="block text-primary underline" href="/api/gbp/connect">Connect agency Google account</a><Button variant="outline" onClick={()=>run('/google/refresh',{})}>Refresh Google listings in background</Button></fieldset>}
      {tab==='clients'&&<>
        {write&&<fieldset disabled={busy} className="grid gap-3 border p-4 rounded"><legend>{editId?'Edit client':'New client'}</legend><Input aria-label="Client name" placeholder="Client name" value={name} onChange={e=>setName(e.target.value)}/><Input aria-label="Contact email" placeholder="Contact email" value={email} onChange={e=>setEmail(e.target.value)}/><Input aria-label="Client folder" placeholder="Folder (optional)" value={folder} onChange={e=>setFolder(e.target.value)}/><Input aria-label="Client tags" placeholder="Tags, comma separated" value={tags} onChange={e=>setTags(e.target.value)}/><Textarea aria-label="Client notes" placeholder="Notes" value={notes} onChange={e=>setNotes(e.target.value)}/><Button onClick={()=>run('/clients'+(editId?'/'+editId:''),{name,contactEmail:email||null,notes,tags:tags.split(',').map(t=>t.trim()).filter(Boolean),folder:folder||null},editId?'PUT':'POST')}>{editId?'Save client':'Create client'}</Button>{editId&&<Button variant="ghost" onClick={()=>{setEditId(null);setName('');setEmail('');setNotes('');setTags('');setFolder('');}}>New client</Button>}</fieldset>}
        {list?.items?.map((c:any)=><article key={c.id} className="border p-3 rounded"><strong>{c.name}</strong><p>{c.contact_email} · {c.folder} · {c.tags.join(', ')}</p><p>{c.notes}</p>{write&&<Button variant="outline" onClick={()=>{setEditId(c.id);setName(c.name);setEmail(c.contact_email||'');setNotes(c.notes);setTags(c.tags.join(', '));setFolder(c.folder||'');}}>Edit {c.name}</Button>}</article>)}
      </>}
      {tab==='team'&&<><p>Members must have a ConstructHUB login. The owner manages membership. Admins manage accessible clients; managers manage their locations; viewers have read access. Unassigned locations require all-client access.</p>{me?.role==='owner'&&<fieldset disabled={busy} className="space-y-3 border rounded p-4"><legend>Add or update member</legend><Input aria-label="Member email" placeholder="Registered member email" value={email} onChange={e=>setEmail(e.target.value)}/><select className={selectClass} aria-label="Member role" value={role} onChange={e=>setRole(e.target.value)}>{['admin','manager','viewer'].map(r=><option key={r}>{r}</option>)}</select><label className="flex gap-2"><input type="checkbox" checked={allClients} onChange={e=>setAllClients(e.target.checked)}/>All clients</label><Input aria-label="Member client IDs" placeholder="Client IDs, comma separated" value={clientIds} onChange={e=>setClientIds(e.target.value)}/><p className="text-sm">{clients?.items?.map((c:any)=>`${c.id}: ${c.name}`).join(' · ')}</p><Button onClick={()=>run('/team',{email,role,allClients,clientIds:clientIds.split(',').filter(Boolean).map(Number)},'PUT')}>Save member</Button></fieldset>}{list?.items?.map((m:any)=><div key={m.member_id} className="border p-3">{m.email} · {m.role} · {m.all_clients?'All clients':m.client_ids.join(', ')}{me?.role==='owner'&&<Button variant="outline" onClick={()=>run('/team/'+m.member_id,undefined,'DELETE')}>Remove member</Button>}</div>)}</>}
      {tab==='onboarding'&&<>{write&&<fieldset disabled={busy} className="space-y-3 border rounded p-4"><legend>Email Google manager instructions</legend><select className={selectClass} aria-label="Onboarding client" value={client} onChange={e=>setClient(e.target.value)}><option value="">Choose client</option>{clients?.items?.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select className={selectClass} aria-label="Agency Google account" value={subject} onChange={e=>setSubject(e.target.value)}><option value="">Choose connected agency Google email</option>{google?.accounts?.filter((g:any)=>g.connected).map((g:any)=><option key={g.subject} value={g.subject}>{g.email}</option>)}</select><Input aria-label="Onboarding business name" placeholder="Exact business name on Google" value={business} onChange={e=>setBusiness(e.target.value)}/><Input aria-label="Onboarding address" placeholder="Full address" value={address} onChange={e=>setAddress(e.target.value)}/><Input aria-label="Onboarding Place ID" placeholder="Place ID (best match)" value={placeId} onChange={e=>setPlaceId(e.target.value)}/><Button onClick={()=>run('/onboarding',{clientId:Number(client),subject,businessName:business,address:address||undefined,placeId:placeId||undefined})}>Email manager instructions</Button><p>The client keeps ownership and adds the exact agency email as Manager. No client OAuth. Reminders follow after three and six days; requests expire after 30 days.</p></fieldset>}{list?.items?.map((r:any)=><article key={r.id} className="border p-3 rounded space-y-2"><strong>{r.business_name}</strong><p>{r.sent_at?r.status:'Email queued'} · {r.contact_email} → {r.agency_email}</p>{r.error&&<p role="alert">{r.error}</p>}<Input aria-label="Copyable onboarding link" readOnly value={r.link}/><Button variant="outline" onClick={()=>navigator.clipboard.writeText(r.link).then(()=>setMessage('Link copied'),()=>setMessage('Select the link and copy it manually'))}>Copy link</Button>{write&&<Button variant="outline" onClick={()=>run(`/onboarding/${r.id}/remind`,{})}>Send reminder</Button>}</article>)}</>}
      {tab==='jobs'&&<>{list?.items?.map((j:any)=><article key={j.id} className="border p-3 rounded"><strong>{j.business_name}</strong> · {j.action} · {j.status}{j.error&&<p role="alert">{j.error}</p>}</article>)}{!list?.items?.length&&<p>No queued actions.</p>}</>}
      {tab!=='settings'&&<Pager offset={offset} total={list?.total??(list?.items?.length===50?offset+51:offset+(list?.items?.length||0))} onChange={setOffset}/>}
    </>}
  </main>;
}
