name: ConstructHUB
options:
  minimumXcodeGenVersion: 2.44.0
  deploymentTarget:
    iOS: '16.0'
settings:
  base:
    SWIFT_VERSION: '5.0'
    TARGETED_DEVICE_FAMILY: '1'
    MARKETING_VERSION: '1.0'
    CURRENT_PROJECT_VERSION: '1'
    GENERATE_INFOPLIST_FILE: NO
    SUPPORTS_MACCATALYST: NO
    SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    CH_PUSH_ENABLED: YES
    CODE_SIGN_ENTITLEMENTS: Shared/Push.entitlements
  configs:
    Debug:
      APS_ENVIRONMENT: development
    Release:
      APS_ENVIRONMENT: production
targets:
  ConstructHUB:
    type: application
    platform: iOS
    sources: [Shared, ConstructHUB/Assets.xcassets]
    settings:
      base:
        TARGETED_DEVICE_FAMILY: '1'
        PRODUCT_BUNDLE_IDENTIFIER: us.constructhub.app
        INFOPLIST_FILE: ConstructHUB/Info.plist
    scheme: {}
  ConstructHUB CRM:
    type: application
    platform: iOS
    sources: [Shared, ConstructHUBCRM/Assets.xcassets]
    settings:
      base:
        TARGETED_DEVICE_FAMILY: '1'
        PRODUCT_BUNDLE_IDENTIFIER: us.constructhub.crm
        INFOPLIST_FILE: ConstructHUBCRM/Info.plist
    scheme: {}
