/**
 * The two generated indexes of the help system — so that every video and every new help entry is ONE
 * FILE of its own and two producers never edit the same line:
 *
 *   shared/help/videos/<helpKey>.json   → shared/help/videos/index.ts    (the manifest, a file per video)
 *   shared/help/entries/<group>/<key>.ts → shared/help/entries/index.ts   (help entries added after the first registry)
 *
 *   tsx scripts/tutorials/gen-index.ts [--check]
 *
 * Each index is one self-contained `export … from` line per file, sorted. Both are committed (the
 * client build, the server bundle, tsx and vitest all import them as plain modules) and carry
 * `merge=union` in .gitattributes: when two branches each add a line, git keeps both. If an index is
 * ever stale or conflicted, run this — it is rebuilt from the directory, never edited by hand.
 * server/help-registry.test.ts fails when an index does not match its directory.
 */
import fs from "fs";
import path from "path";

const ROOT = path.resolve(import.meta.dirname, "../..");
const ident = (prefix: string, name: string) => `${prefix}_${name.replace(/[^a-zA-Z0-9]/g, "_")}`;
const HEADER = (what: string) => `// GENERATED by scripts/tutorials/gen-index.ts from the files in this directory — do not edit.\n// ${what}\n`;

function walk(dir: string, ext: string, base = dir): string[] {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((d) =>
    d.isDirectory() ? walk(path.join(dir, d.name), ext, base)
      : d.name.endsWith(ext) && d.name !== "index.ts" ? [path.relative(base, path.join(dir, d.name)).split(path.sep).join("/")] : []);
}

/** [file, content] of both indexes, as they should be. */
export function indexes(): [string, string][] {
  const videosDir = path.join(ROOT, "shared/help/videos"), entriesDir = path.join(ROOT, "shared/help/entries");
  const videos = walk(videosDir, ".json").sort().map((f) => `export { default as ${ident("v", f.slice(0, -5))} } from "./${f}";`);
  const entries = walk(entriesDir, ".ts").sort().map((f) => `export { default as ${ident("e", path.basename(f, ".ts"))} } from "./${f.slice(0, -3)}";`);
  return [
    [path.join(videosDir, "index.ts"), `${HEADER("One line per recorded walkthrough (its manifest file).")}${videos.join("\n") || "export {};"}\n`],
    [path.join(entriesDir, "index.ts"), `${HEADER("One line per help entry file.")}${entries.join("\n") || "export {};"}\n`],
  ];
}

/** Write both indexes (atomically: producers in the same working copy may run this at the same moment). */
export function writeIndexes(): void {
  for (const [file, content] of indexes()) {
    if (fs.existsSync(file) && fs.readFileSync(file, "utf8") === content) continue;
    const tmp = `${file}.${process.pid}.tmp`;
    fs.writeFileSync(tmp, content); fs.renameSync(tmp, file);
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(import.meta.filename)) {
  if (process.argv.includes("--check")) {
    const stale = indexes().filter(([file, content]) => !fs.existsSync(file) || fs.readFileSync(file, "utf8") !== content).map(([f]) => path.relative(ROOT, f));
    if (stale.length) { console.error(`stale: ${stale.join(", ")} — run: npx tsx scripts/tutorials/gen-index.ts`); process.exit(1); }
    console.log("indexes are up to date");
  } else { writeIndexes(); console.log("indexes written"); }
}
