/**
 * Display names for county-equivalents that are not "<name> County" (Census Bureau names): Louisiana parishes,
 * Alaska boroughs and census areas, independent cities (Virginia, Baltimore, St. Louis, Carson City).
 * Key "ST:<counties.name>". Everything else is "<name> County". Generated from Census SUB-EST2024, 2026-10-05.
 */
export const COUNTY_LABELS: Readonly<Record<string, string>> = {
 "AK:Aleutians East": "Aleutians East Borough",
 "AK:Aleutians West": "Aleutians West Census Area",
 "AK:Anchorage": "Anchorage Municipality",
 "AK:Bethel": "Bethel Census Area",
 "AK:Bristol Bay": "Bristol Bay Borough",
 "AK:Chugach": "Chugach Census Area",
 "AK:Copper River": "Copper River Census Area",
 "AK:Denali": "Denali Borough",
 "AK:Dillingham": "Dillingham Census Area",
 "AK:Fairbanks North Star": "Fairbanks North Star Borough",
 "AK:Haines": "Haines Borough",
 "AK:Hoonah-Angoon": "Hoonah-Angoon Census Area",
 "AK:Juneau City and": "Juneau City and Borough",
 "AK:Kenai Peninsula": "Kenai Peninsula Borough",
 "AK:Ketchikan Gateway": "Ketchikan Gateway Borough",
 "AK:Kodiak Island": "Kodiak Island Borough",
 "AK:Kusilvak": "Kusilvak Census Area",
 "AK:Lake and Peninsula": "Lake and Peninsula Borough",
 "AK:Matanuska-Susitna": "Matanuska-Susitna Borough",
 "AK:Nome": "Nome Census Area",
 "AK:North Slope": "North Slope Borough",
 "AK:Northwest Arctic": "Northwest Arctic Borough",
 "AK:Petersburg": "Petersburg Borough",
 "AK:Prince of Wales-Hyder": "Prince of Wales-Hyder Census Area",
 "AK:Sitka City and": "Sitka City and Borough",
 "AK:Skagway": "Skagway Municipality",
 "AK:Southeast Fairbanks": "Southeast Fairbanks Census Area",
 "AK:Valdez-Cordova": "Chugach Census Area",
 "AK:Wade Hampton": "Kusilvak Census Area",
 "AK:Wrangell City and": "Wrangell City and Borough",
 "AK:Yakutat City and": "Yakutat City and Borough",
 "AK:Yukon-Koyukuk": "Yukon-Koyukuk Census Area",
 "DC:District of Columbia": "District of Columbia",
 "LA:Acadia": "Acadia Parish",
 "LA:Allen": "Allen Parish",
 "LA:Ascension": "Ascension Parish",
 "LA:Assumption": "Assumption Parish",
 "LA:Avoyelles": "Avoyelles Parish",
 "LA:Beauregard": "Beauregard Parish",
 "LA:Bienville": "Bienville Parish",
 "LA:Bossier": "Bossier Parish",
 "LA:Caddo": "Caddo Parish",
 "LA:Calcasieu": "Calcasieu Parish",
 "LA:Caldwell": "Caldwell Parish",
 "LA:Cameron": "Cameron Parish",
 "LA:Catahoula": "Catahoula Parish",
 "LA:Claiborne": "Claiborne Parish",
 "LA:Concordia": "Concordia Parish",
 "LA:De Soto": "De Soto Parish",
 "LA:East Baton Rouge": "East Baton Rouge Parish",
 "LA:East Carroll": "East Carroll Parish",
 "LA:East Feliciana": "East Feliciana Parish",
 "LA:Evangeline": "Evangeline Parish",
 "LA:Franklin": "Franklin Parish",
 "LA:Grant": "Grant Parish",
 "LA:Iberia": "Iberia Parish",
 "LA:Iberville": "Iberville Parish",
 "LA:Jackson": "Jackson Parish",
 "LA:Jefferson": "Jefferson Parish",
 "LA:Jefferson Davis": "Jefferson Davis Parish",
 "LA:La Salle": "LaSalle Parish",
 "LA:Lafayette": "Lafayette Parish",
 "LA:Lafourche": "Lafourche Parish",
 "LA:Lincoln": "Lincoln Parish",
 "LA:Livingston": "Livingston Parish",
 "LA:Madison": "Madison Parish",
 "LA:Morehouse": "Morehouse Parish",
 "LA:Natchitoches": "Natchitoches Parish",
 "LA:Orleans": "Orleans Parish",
 "LA:Ouachita": "Ouachita Parish",
 "LA:Plaquemines": "Plaquemines Parish",
 "LA:Pointe Coupee": "Pointe Coupee Parish",
 "LA:Rapides": "Rapides Parish",
 "LA:Red River": "Red River Parish",
 "LA:Richland": "Richland Parish",
 "LA:Sabine": "Sabine Parish",
 "LA:St. Bernard": "St. Bernard Parish",
 "LA:St. Charles": "St. Charles Parish",
 "LA:St. Helena": "St. Helena Parish",
 "LA:St. James": "St. James Parish",
 "LA:St. John the Baptist": "St. John the Baptist Parish",
 "LA:St. Landry": "St. Landry Parish",
 "LA:St. Martin": "St. Martin Parish",
 "LA:St. Mary": "St. Mary Parish",
 "LA:St. Tammany": "St. Tammany Parish",
 "LA:Tangipahoa": "Tangipahoa Parish",
 "LA:Tensas": "Tensas Parish",
 "LA:Terrebonne": "Terrebonne Parish",
 "LA:Union": "Union Parish",
 "LA:Vermilion": "Vermilion Parish",
 "LA:Vernon": "Vernon Parish",
 "LA:Washington": "Washington Parish",
 "LA:Webster": "Webster Parish",
 "LA:West Baton Rouge": "West Baton Rouge Parish",
 "LA:West Carroll": "West Carroll Parish",
 "LA:West Feliciana": "West Feliciana Parish",
 "LA:Winn": "Winn Parish",
 "NV:Carson": "Carson City",
 "NV:Carson City": "Carson City",
 "VA:Alexandria": "City of Alexandria",
 "VA:Bristol": "City of Bristol",
 "VA:Buena Vista": "City of Buena Vista",
 "VA:Charlottesville": "City of Charlottesville",
 "VA:Chesapeake": "City of Chesapeake",
 "VA:Colonial Heights": "City of Colonial Heights",
 "VA:Covington": "City of Covington",
 "VA:Danville": "City of Danville",
 "VA:Emporia": "City of Emporia",
 "VA:Falls Church": "City of Falls Church",
 "VA:Fredericksburg": "City of Fredericksburg",
 "VA:Galax": "City of Galax",
 "VA:Hampton": "City of Hampton",
 "VA:Harrisonburg": "City of Harrisonburg",
 "VA:Hopewell": "City of Hopewell",
 "VA:Lexington": "City of Lexington",
 "VA:Lynchburg": "City of Lynchburg",
 "VA:Manassas": "City of Manassas",
 "VA:Manassas Park": "City of Manassas Park",
 "VA:Martinsville": "City of Martinsville",
 "VA:Newport News": "City of Newport News",
 "VA:Norfolk": "City of Norfolk",
 "VA:Norton": "City of Norton",
 "VA:Petersburg": "City of Petersburg",
 "VA:Poquoson": "City of Poquoson",
 "VA:Portsmouth": "City of Portsmouth",
 "VA:Radford": "City of Radford",
 "VA:Salem": "City of Salem",
 "VA:Staunton": "City of Staunton",
 "VA:Suffolk": "City of Suffolk",
 "VA:Virginia Beach": "City of Virginia Beach",
 "VA:Waynesboro": "City of Waynesboro",
 "VA:Williamsburg": "City of Williamsburg",
 "VA:Winchester": "City of Winchester"
};

/** "Acadia Parish", "Kusilvak Census Area", "City of Alexandria", otherwise "<name> County". */
export function countyLabel(name: string, stateCode: string): string {
  return COUNTY_LABELS[`${stateCode}:${name}`] ?? `${name} County`;
}
