// GENERATED by scripts/tutorials/gen-index.ts from the files in this directory — do not edit.
// One line per recorded walkthrough (its manifest file).
export { default as v_crm_client_edit } from "./crm-client-edit.json";
export { default as v_crm_client_export } from "./crm-client-export.json";
export { default as v_crm_client_new } from "./crm-client-new.json";
export { default as v_crm_client_notes } from "./crm-client-notes.json";
export { default as v_crm_clients } from "./crm-clients.json";
export { default as v_crm_create_estimate } from "./crm-create-estimate.json";
export { default as v_crm_create_menu } from "./crm-create-menu.json";
export { default as v_crm_home } from "./crm-home.json";
export { default as v_crm_lead_new } from "./crm-lead-new.json";
export { default as v_crm_pipeline } from "./crm-pipeline.json";
export { default as v_crm_pipeline_move } from "./crm-pipeline-move.json";
export { default as v_crm_schedule } from "./crm-schedule.json";
export { default as v_database_directory } from "./database-directory.json";
