// GENERATED by scripts/tutorials/gen-index.ts from the files in this directory — do not edit.
// One line per recorded walkthrough (its manifest file).
export { default as v_crm_clients } from "./crm-clients.json";
export { default as v_crm_create_estimate } from "./crm-create-estimate.json";
export { default as v_crm_estimate_edit } from "./crm-estimate-edit.json";
export { default as v_crm_estimates } from "./crm-estimates.json";
export { default as v_crm_invoices } from "./crm-invoices.json";
export { default as v_crm_payment_record } from "./crm-payment-record.json";
export { default as v_crm_payment_reverse } from "./crm-payment-reverse.json";
export { default as v_crm_pricebook_add } from "./crm-pricebook-add.json";
export { default as v_crm_pricebook_template } from "./crm-pricebook-template.json";
export { default as v_crm_pricebook } from "./crm-pricebook.json";
export { default as v_crm_schedule } from "./crm-schedule.json";
export { default as v_database_directory } from "./database-directory.json";
